/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  TypesAnnouncement,
  TypesResponseArrayTypesAnnouncement,
  TypesResponseTypesAnnouncement,
  TypesResponseTypesStatusResponse,
} from '../models/index';
import {
    TypesAnnouncementFromJSON,
    TypesAnnouncementToJSON,
    TypesResponseArrayTypesAnnouncementFromJSON,
    TypesResponseArrayTypesAnnouncementToJSON,
    TypesResponseTypesAnnouncementFromJSON,
    TypesResponseTypesAnnouncementToJSON,
    TypesResponseTypesStatusResponseFromJSON,
    TypesResponseTypesStatusResponseToJSON,
} from '../models/index';

export interface ApiAnnouncementsIdDeleteRequest {
    id: number;
}

export interface ApiAnnouncementsIdPutRequest {
    id: number;
    TypesAnnouncement: TypesAnnouncement;
}

export interface ApiAnnouncementsPostRequest {
    TypesAnnouncement: TypesAnnouncement;
}

/**
 * 
 */
export class AnnouncementsApi extends runtime.BaseAPI {

    /**
     * List enabled announcements (for the banner)
     */
    async apiAnnouncementsActiveGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TypesResponseArrayTypesAnnouncement>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/api/announcements/active`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TypesResponseArrayTypesAnnouncementFromJSON(jsonValue));
    }

    /**
     * List enabled announcements (for the banner)
     */
    async apiAnnouncementsActiveGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TypesResponseArrayTypesAnnouncement> {
        const response = await this.apiAnnouncementsActiveGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * List all announcements
     */
    async apiAnnouncementsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TypesResponseArrayTypesAnnouncement>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/api/announcements`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TypesResponseArrayTypesAnnouncementFromJSON(jsonValue));
    }

    /**
     * List all announcements
     */
    async apiAnnouncementsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TypesResponseArrayTypesAnnouncement> {
        const response = await this.apiAnnouncementsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Delete an announcement
     */
    async apiAnnouncementsIdDeleteRaw(requestParameters: ApiAnnouncementsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TypesResponseTypesStatusResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiAnnouncementsIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/api/announcements/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TypesResponseTypesStatusResponseFromJSON(jsonValue));
    }

    /**
     * Delete an announcement
     */
    async apiAnnouncementsIdDelete(requestParameters: ApiAnnouncementsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TypesResponseTypesStatusResponse> {
        const response = await this.apiAnnouncementsIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update an announcement
     */
    async apiAnnouncementsIdPutRaw(requestParameters: ApiAnnouncementsIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TypesResponseTypesAnnouncement>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiAnnouncementsIdPut().'
            );
        }

        if (requestParameters['TypesAnnouncement'] == null) {
            throw new runtime.RequiredError(
                'TypesAnnouncement',
                'Required parameter "TypesAnnouncement" was null or undefined when calling apiAnnouncementsIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/api/announcements/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: TypesAnnouncementToJSON(requestParameters['TypesAnnouncement']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TypesResponseTypesAnnouncementFromJSON(jsonValue));
    }

    /**
     * Update an announcement
     */
    async apiAnnouncementsIdPut(requestParameters: ApiAnnouncementsIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TypesResponseTypesAnnouncement> {
        const response = await this.apiAnnouncementsIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create an announcement
     */
    async apiAnnouncementsPostRaw(requestParameters: ApiAnnouncementsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TypesResponseTypesAnnouncement>> {
        if (requestParameters['TypesAnnouncement'] == null) {
            throw new runtime.RequiredError(
                'TypesAnnouncement',
                'Required parameter "TypesAnnouncement" was null or undefined when calling apiAnnouncementsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/api/announcements`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TypesAnnouncementToJSON(requestParameters['TypesAnnouncement']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TypesResponseTypesAnnouncementFromJSON(jsonValue));
    }

    /**
     * Create an announcement
     */
    async apiAnnouncementsPost(requestParameters: ApiAnnouncementsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TypesResponseTypesAnnouncement> {
        const response = await this.apiAnnouncementsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
