/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  TypesChangePasswordRequest,
  TypesLoginRequest,
  TypesResponseTypesLoginResponse,
  TypesResponseTypesStatusResponse,
} from '../models/index';
import {
    TypesChangePasswordRequestFromJSON,
    TypesChangePasswordRequestToJSON,
    TypesLoginRequestFromJSON,
    TypesLoginRequestToJSON,
    TypesResponseTypesLoginResponseFromJSON,
    TypesResponseTypesLoginResponseToJSON,
    TypesResponseTypesStatusResponseFromJSON,
    TypesResponseTypesStatusResponseToJSON,
} from '../models/index';

export interface ApiAuthLoginPostRequest {
    TypesLoginRequest: TypesLoginRequest;
}

export interface ApiAuthPasswordPutRequest {
    TypesChangePasswordRequest: TypesChangePasswordRequest;
}

/**
 * 
 */
export class AuthApi extends runtime.BaseAPI {

    /**
     * Authenticate and obtain a token
     */
    async apiAuthLoginPostRaw(requestParameters: ApiAuthLoginPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TypesResponseTypesLoginResponse>> {
        if (requestParameters['TypesLoginRequest'] == null) {
            throw new runtime.RequiredError(
                'TypesLoginRequest',
                'Required parameter "TypesLoginRequest" was null or undefined when calling apiAuthLoginPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/auth/login`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TypesLoginRequestToJSON(requestParameters['TypesLoginRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TypesResponseTypesLoginResponseFromJSON(jsonValue));
    }

    /**
     * Authenticate and obtain a token
     */
    async apiAuthLoginPost(requestParameters: ApiAuthLoginPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TypesResponseTypesLoginResponse> {
        const response = await this.apiAuthLoginPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Change the current user\'s password
     */
    async apiAuthPasswordPutRaw(requestParameters: ApiAuthPasswordPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TypesResponseTypesStatusResponse>> {
        if (requestParameters['TypesChangePasswordRequest'] == null) {
            throw new runtime.RequiredError(
                'TypesChangePasswordRequest',
                'Required parameter "TypesChangePasswordRequest" was null or undefined when calling apiAuthPasswordPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/api/auth/password`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: TypesChangePasswordRequestToJSON(requestParameters['TypesChangePasswordRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TypesResponseTypesStatusResponseFromJSON(jsonValue));
    }

    /**
     * Change the current user\'s password
     */
    async apiAuthPasswordPut(requestParameters: ApiAuthPasswordPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TypesResponseTypesStatusResponse> {
        const response = await this.apiAuthPasswordPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
