/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DhcpReservationRequest,
  DhcpReserveFromLeaseRequest,
  DhcpTargetRequest,
  TypesResponseArrayDhcpLeaseView,
  TypesResponseArrayKeaSubnet,
  TypesResponseArrayKeaSubnetView,
  TypesResponseDhcpStatsResponse,
  TypesResponseString,
  TypesResponseTypesStatusResponse,
} from '../models/index';
import {
    DhcpReservationRequestFromJSON,
    DhcpReservationRequestToJSON,
    DhcpReserveFromLeaseRequestFromJSON,
    DhcpReserveFromLeaseRequestToJSON,
    DhcpTargetRequestFromJSON,
    DhcpTargetRequestToJSON,
    TypesResponseArrayDhcpLeaseViewFromJSON,
    TypesResponseArrayDhcpLeaseViewToJSON,
    TypesResponseArrayKeaSubnetFromJSON,
    TypesResponseArrayKeaSubnetToJSON,
    TypesResponseArrayKeaSubnetViewFromJSON,
    TypesResponseArrayKeaSubnetViewToJSON,
    TypesResponseDhcpStatsResponseFromJSON,
    TypesResponseDhcpStatsResponseToJSON,
    TypesResponseStringFromJSON,
    TypesResponseStringToJSON,
    TypesResponseTypesStatusResponseFromJSON,
    TypesResponseTypesStatusResponseToJSON,
} from '../models/index';

export interface ApiDhcpFreeIpGetRequest {
    target: string;
}

export interface ApiDhcpLeasesClearPostRequest {
    DhcpTargetRequest: DhcpTargetRequest;
}

export interface ApiDhcpLeasesGetRequest {
    q?: string;
}

export interface ApiDhcpLeasesStreamGetRequest {
    source?: ApiDhcpLeasesStreamGetSourceEnum;
}

export interface ApiDhcpReservationsDelPostRequest {
    DhcpTargetRequest: DhcpTargetRequest;
}

export interface ApiDhcpReservationsFromLeasePostRequest {
    DhcpReserveFromLeaseRequest: DhcpReserveFromLeaseRequest;
}

export interface ApiDhcpReservationsPersistPostRequest {
    DhcpTargetRequest: DhcpTargetRequest;
}

export interface ApiDhcpReservationsPostRequest {
    DhcpReservationRequest: DhcpReservationRequest;
}

/**
 * 
 */
export class DhcpApi extends runtime.BaseAPI {

    /**
     * Suggest a free address in a subnet\'s pools
     */
    async apiDhcpFreeIpGetRaw(requestParameters: ApiDhcpFreeIpGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TypesResponseTypesStatusResponse>> {
        if (requestParameters['target'] == null) {
            throw new runtime.RequiredError(
                'target',
                'Required parameter "target" was null or undefined when calling apiDhcpFreeIpGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['target'] != null) {
            queryParameters['target'] = requestParameters['target'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/api/dhcp/free-ip`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TypesResponseTypesStatusResponseFromJSON(jsonValue));
    }

    /**
     * Suggest a free address in a subnet\'s pools
     */
    async apiDhcpFreeIpGet(requestParameters: ApiDhcpFreeIpGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TypesResponseTypesStatusResponse> {
        const response = await this.apiDhcpFreeIpGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * DHCP subnets with their leases and reservations
     */
    async apiDhcpGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TypesResponseArrayKeaSubnetView>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/api/dhcp`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TypesResponseArrayKeaSubnetViewFromJSON(jsonValue));
    }

    /**
     * DHCP subnets with their leases and reservations
     */
    async apiDhcpGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TypesResponseArrayKeaSubnetView> {
        const response = await this.apiDhcpGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Delete an active lease
     */
    async apiDhcpLeasesClearPostRaw(requestParameters: ApiDhcpLeasesClearPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TypesResponseTypesStatusResponse>> {
        if (requestParameters['DhcpTargetRequest'] == null) {
            throw new runtime.RequiredError(
                'DhcpTargetRequest',
                'Required parameter "DhcpTargetRequest" was null or undefined when calling apiDhcpLeasesClearPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/api/dhcp/leases/clear`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DhcpTargetRequestToJSON(requestParameters['DhcpTargetRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TypesResponseTypesStatusResponseFromJSON(jsonValue));
    }

    /**
     * Delete an active lease
     */
    async apiDhcpLeasesClearPost(requestParameters: ApiDhcpLeasesClearPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TypesResponseTypesStatusResponse> {
        const response = await this.apiDhcpLeasesClearPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List active DHCP leases, optionally filtered
     */
    async apiDhcpLeasesGetRaw(requestParameters: ApiDhcpLeasesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TypesResponseArrayDhcpLeaseView>> {
        const queryParameters: any = {};

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/api/dhcp/leases`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TypesResponseArrayDhcpLeaseViewFromJSON(jsonValue));
    }

    /**
     * List active DHCP leases, optionally filtered
     */
    async apiDhcpLeasesGet(requestParameters: ApiDhcpLeasesGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TypesResponseArrayDhcpLeaseView> {
        const response = await this.apiDhcpLeasesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Tail Kea DHCP daemon logs (SSE)
     */
    async apiDhcpLeasesStreamGetRaw(requestParameters: ApiDhcpLeasesStreamGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const queryParameters: any = {};

        if (requestParameters['source'] != null) {
            queryParameters['source'] = requestParameters['source'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/api/dhcp/leases/stream`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Tail Kea DHCP daemon logs (SSE)
     */
    async apiDhcpLeasesStreamGet(requestParameters: ApiDhcpLeasesStreamGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.apiDhcpLeasesStreamGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete a reservation
     */
    async apiDhcpReservationsDelPostRaw(requestParameters: ApiDhcpReservationsDelPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TypesResponseTypesStatusResponse>> {
        if (requestParameters['DhcpTargetRequest'] == null) {
            throw new runtime.RequiredError(
                'DhcpTargetRequest',
                'Required parameter "DhcpTargetRequest" was null or undefined when calling apiDhcpReservationsDelPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/api/dhcp/reservations/del`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DhcpTargetRequestToJSON(requestParameters['DhcpTargetRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TypesResponseTypesStatusResponseFromJSON(jsonValue));
    }

    /**
     * Delete a reservation
     */
    async apiDhcpReservationsDelPost(requestParameters: ApiDhcpReservationsDelPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TypesResponseTypesStatusResponse> {
        const response = await this.apiDhcpReservationsDelPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Reserve a host from a dynamic lease
     */
    async apiDhcpReservationsFromLeasePostRaw(requestParameters: ApiDhcpReservationsFromLeasePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TypesResponseTypesStatusResponse>> {
        if (requestParameters['DhcpReserveFromLeaseRequest'] == null) {
            throw new runtime.RequiredError(
                'DhcpReserveFromLeaseRequest',
                'Required parameter "DhcpReserveFromLeaseRequest" was null or undefined when calling apiDhcpReservationsFromLeasePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/api/dhcp/reservations/from-lease`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DhcpReserveFromLeaseRequestToJSON(requestParameters['DhcpReserveFromLeaseRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TypesResponseTypesStatusResponseFromJSON(jsonValue));
    }

    /**
     * Reserve a host from a dynamic lease
     */
    async apiDhcpReservationsFromLeasePost(requestParameters: ApiDhcpReservationsFromLeasePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TypesResponseTypesStatusResponse> {
        const response = await this.apiDhcpReservationsFromLeasePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Promote an active lease to a reservation
     */
    async apiDhcpReservationsPersistPostRaw(requestParameters: ApiDhcpReservationsPersistPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TypesResponseTypesStatusResponse>> {
        if (requestParameters['DhcpTargetRequest'] == null) {
            throw new runtime.RequiredError(
                'DhcpTargetRequest',
                'Required parameter "DhcpTargetRequest" was null or undefined when calling apiDhcpReservationsPersistPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/api/dhcp/reservations/persist`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DhcpTargetRequestToJSON(requestParameters['DhcpTargetRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TypesResponseTypesStatusResponseFromJSON(jsonValue));
    }

    /**
     * Promote an active lease to a reservation
     */
    async apiDhcpReservationsPersistPost(requestParameters: ApiDhcpReservationsPersistPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TypesResponseTypesStatusResponse> {
        const response = await this.apiDhcpReservationsPersistPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Reserve an address for a MAC/DUID
     */
    async apiDhcpReservationsPostRaw(requestParameters: ApiDhcpReservationsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TypesResponseTypesStatusResponse>> {
        if (requestParameters['DhcpReservationRequest'] == null) {
            throw new runtime.RequiredError(
                'DhcpReservationRequest',
                'Required parameter "DhcpReservationRequest" was null or undefined when calling apiDhcpReservationsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/api/dhcp/reservations`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DhcpReservationRequestToJSON(requestParameters['DhcpReservationRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TypesResponseTypesStatusResponseFromJSON(jsonValue));
    }

    /**
     * Reserve an address for a MAC/DUID
     */
    async apiDhcpReservationsPost(requestParameters: ApiDhcpReservationsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TypesResponseTypesStatusResponse> {
        const response = await this.apiDhcpReservationsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Restart the running DHCP servers (Kea)
     */
    async apiDhcpRestartPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TypesResponseString>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/api/dhcp/restart`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TypesResponseStringFromJSON(jsonValue));
    }

    /**
     * Restart the running DHCP servers (Kea)
     */
    async apiDhcpRestartPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TypesResponseString> {
        const response = await this.apiDhcpRestartPostRaw(initOverrides);
        return await response.value();
    }

    /**
     * DHCP server state and Kea statistics
     */
    async apiDhcpStatsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TypesResponseDhcpStatsResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/api/dhcp/stats`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TypesResponseDhcpStatsResponseFromJSON(jsonValue));
    }

    /**
     * DHCP server state and Kea statistics
     */
    async apiDhcpStatsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TypesResponseDhcpStatsResponse> {
        const response = await this.apiDhcpStatsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * List configured DHCP subnets
     */
    async apiDhcpSubnetsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TypesResponseArrayKeaSubnet>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/api/dhcp/subnets`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TypesResponseArrayKeaSubnetFromJSON(jsonValue));
    }

    /**
     * List configured DHCP subnets
     */
    async apiDhcpSubnetsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TypesResponseArrayKeaSubnet> {
        const response = await this.apiDhcpSubnetsGetRaw(initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const ApiDhcpLeasesStreamGetSourceEnum = {
    KeaDhcp4: 'kea-dhcp4',
    KeaDhcp6: 'kea-dhcp6',
    KeaDhcpDdns: 'kea-dhcp-ddns'
} as const;
export type ApiDhcpLeasesStreamGetSourceEnum = typeof ApiDhcpLeasesStreamGetSourceEnum[keyof typeof ApiDhcpLeasesStreamGetSourceEnum];
