/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  TypesResponseTypesArtifactContent,
  TypesResponseTypesFailureRecord,
  TypesResponseTypesFailuresResponse,
  TypesResponseTypesStatusResponse,
} from '../models/index';
import {
    TypesResponseTypesArtifactContentFromJSON,
    TypesResponseTypesArtifactContentToJSON,
    TypesResponseTypesFailureRecordFromJSON,
    TypesResponseTypesFailureRecordToJSON,
    TypesResponseTypesFailuresResponseFromJSON,
    TypesResponseTypesFailuresResponseToJSON,
    TypesResponseTypesStatusResponseFromJSON,
    TypesResponseTypesStatusResponseToJSON,
} from '../models/index';

export interface ApiFailuresIdArtifactGetRequest {
    id: string;
    dest: string;
}

export interface ApiFailuresIdDeleteRequest {
    id: string;
}

export interface ApiFailuresIdExportGetRequest {
    id: string;
    redact?: boolean;
}

export interface ApiFailuresIdGetRequest {
    id: string;
}

/**
 * 
 */
export class FailuresApi extends runtime.BaseAPI {

    /**
     * List preserved failed-apply bundles
     */
    async apiFailuresGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TypesResponseTypesFailuresResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/api/failures`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TypesResponseTypesFailuresResponseFromJSON(jsonValue));
    }

    /**
     * List preserved failed-apply bundles
     */
    async apiFailuresGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TypesResponseTypesFailuresResponse> {
        const response = await this.apiFailuresGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Read a rendered artifact from a failed-apply bundle
     */
    async apiFailuresIdArtifactGetRaw(requestParameters: ApiFailuresIdArtifactGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TypesResponseTypesArtifactContent>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiFailuresIdArtifactGet().'
            );
        }

        if (requestParameters['dest'] == null) {
            throw new runtime.RequiredError(
                'dest',
                'Required parameter "dest" was null or undefined when calling apiFailuresIdArtifactGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['dest'] != null) {
            queryParameters['dest'] = requestParameters['dest'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/api/failures/{id}/artifact`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TypesResponseTypesArtifactContentFromJSON(jsonValue));
    }

    /**
     * Read a rendered artifact from a failed-apply bundle
     */
    async apiFailuresIdArtifactGet(requestParameters: ApiFailuresIdArtifactGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TypesResponseTypesArtifactContent> {
        const response = await this.apiFailuresIdArtifactGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete a failed-apply bundle
     */
    async apiFailuresIdDeleteRaw(requestParameters: ApiFailuresIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TypesResponseTypesStatusResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiFailuresIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/api/failures/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TypesResponseTypesStatusResponseFromJSON(jsonValue));
    }

    /**
     * Delete a failed-apply bundle
     */
    async apiFailuresIdDelete(requestParameters: ApiFailuresIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TypesResponseTypesStatusResponse> {
        const response = await this.apiFailuresIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Download a failed-apply bundle as a tar.gz
     */
    async apiFailuresIdExportGetRaw(requestParameters: ApiFailuresIdExportGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiFailuresIdExportGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['redact'] != null) {
            queryParameters['redact'] = requestParameters['redact'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/api/failures/{id}/export`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Download a failed-apply bundle as a tar.gz
     */
    async apiFailuresIdExportGet(requestParameters: ApiFailuresIdExportGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.apiFailuresIdExportGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a failed-apply bundle
     */
    async apiFailuresIdGetRaw(requestParameters: ApiFailuresIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TypesResponseTypesFailureRecord>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiFailuresIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/api/failures/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TypesResponseTypesFailureRecordFromJSON(jsonValue));
    }

    /**
     * Get a failed-apply bundle
     */
    async apiFailuresIdGet(requestParameters: ApiFailuresIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TypesResponseTypesFailureRecord> {
        const response = await this.apiFailuresIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
