/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  TypesAddFriendRequest,
  TypesConfigureConntrackRequest,
  TypesConfigureVRRPRequest,
  TypesDeriveTunnelRequest,
  TypesDeriveWireguardRequest,
  TypesFriendPairRequest,
  TypesFriendPreviewRequest,
  TypesResponseArrayManagersPushResult,
  TypesResponseArrayRenderNftVar,
  TypesResponseArrayTypesFriendInfo,
  TypesResponseArrayTypesFriendInterface,
  TypesResponseArrayTypesFriendStatus,
  TypesResponseArrayTypesFriendVar,
  TypesResponseConfigConfig,
  TypesResponseFriendcacheCachedState,
  TypesResponseTypesConfigureConntrackResult,
  TypesResponseTypesConfigureVRRPResult,
  TypesResponseTypesDeriveTunnelResult,
  TypesResponseTypesDeriveWireguardResult,
  TypesResponseTypesFriendDeleteResult,
  TypesResponseTypesFriendInfo,
  TypesResponseTypesFriendPairResponse,
  TypesResponseTypesFriendPoll,
  TypesResponseTypesFriendPreview,
  TypesResponseTypesFriendStatus,
  TypesResponseTypesFriendsHello,
  TypesUpdateFriendRequest,
  TypesVerifyFriendRequest,
} from '../models/index';
import {
    TypesAddFriendRequestFromJSON,
    TypesAddFriendRequestToJSON,
    TypesConfigureConntrackRequestFromJSON,
    TypesConfigureConntrackRequestToJSON,
    TypesConfigureVRRPRequestFromJSON,
    TypesConfigureVRRPRequestToJSON,
    TypesDeriveTunnelRequestFromJSON,
    TypesDeriveTunnelRequestToJSON,
    TypesDeriveWireguardRequestFromJSON,
    TypesDeriveWireguardRequestToJSON,
    TypesFriendPairRequestFromJSON,
    TypesFriendPairRequestToJSON,
    TypesFriendPreviewRequestFromJSON,
    TypesFriendPreviewRequestToJSON,
    TypesResponseArrayManagersPushResultFromJSON,
    TypesResponseArrayManagersPushResultToJSON,
    TypesResponseArrayRenderNftVarFromJSON,
    TypesResponseArrayRenderNftVarToJSON,
    TypesResponseArrayTypesFriendInfoFromJSON,
    TypesResponseArrayTypesFriendInfoToJSON,
    TypesResponseArrayTypesFriendInterfaceFromJSON,
    TypesResponseArrayTypesFriendInterfaceToJSON,
    TypesResponseArrayTypesFriendStatusFromJSON,
    TypesResponseArrayTypesFriendStatusToJSON,
    TypesResponseArrayTypesFriendVarFromJSON,
    TypesResponseArrayTypesFriendVarToJSON,
    TypesResponseConfigConfigFromJSON,
    TypesResponseConfigConfigToJSON,
    TypesResponseFriendcacheCachedStateFromJSON,
    TypesResponseFriendcacheCachedStateToJSON,
    TypesResponseTypesConfigureConntrackResultFromJSON,
    TypesResponseTypesConfigureConntrackResultToJSON,
    TypesResponseTypesConfigureVRRPResultFromJSON,
    TypesResponseTypesConfigureVRRPResultToJSON,
    TypesResponseTypesDeriveTunnelResultFromJSON,
    TypesResponseTypesDeriveTunnelResultToJSON,
    TypesResponseTypesDeriveWireguardResultFromJSON,
    TypesResponseTypesDeriveWireguardResultToJSON,
    TypesResponseTypesFriendDeleteResultFromJSON,
    TypesResponseTypesFriendDeleteResultToJSON,
    TypesResponseTypesFriendInfoFromJSON,
    TypesResponseTypesFriendInfoToJSON,
    TypesResponseTypesFriendPairResponseFromJSON,
    TypesResponseTypesFriendPairResponseToJSON,
    TypesResponseTypesFriendPollFromJSON,
    TypesResponseTypesFriendPollToJSON,
    TypesResponseTypesFriendPreviewFromJSON,
    TypesResponseTypesFriendPreviewToJSON,
    TypesResponseTypesFriendStatusFromJSON,
    TypesResponseTypesFriendStatusToJSON,
    TypesResponseTypesFriendsHelloFromJSON,
    TypesResponseTypesFriendsHelloToJSON,
    TypesUpdateFriendRequestFromJSON,
    TypesUpdateFriendRequestToJSON,
    TypesVerifyFriendRequestFromJSON,
    TypesVerifyFriendRequestToJSON,
} from '../models/index';

export interface ApiFriendsHelloGetRequest {
    challenge?: string;
}

export interface ApiFriendsNameCacheGetRequest {
    name: string;
}

export interface ApiFriendsNameCheckPostRequest {
    name: string;
}

export interface ApiFriendsNameConfigGetRequest {
    name: string;
}

export interface ApiFriendsNameConntrackPostRequest {
    name: string;
    TypesConfigureConntrackRequest: TypesConfigureConntrackRequest;
}

export interface ApiFriendsNameDeleteRequest {
    name: string;
    confirm?: boolean;
}

export interface ApiFriendsNameInterfacesGetRequest {
    name: string;
}

export interface ApiFriendsNameNftablesGetRequest {
    name: string;
}

export interface ApiFriendsNamePairPostRequest {
    name: string;
    TypesVerifyFriendRequest?: TypesVerifyFriendRequest;
}

export interface ApiFriendsNamePutRequest {
    name: string;
    TypesUpdateFriendRequest: TypesUpdateFriendRequest;
}

export interface ApiFriendsNameSyncPostRequest {
    name: string;
}

export interface ApiFriendsNameTunnelPostRequest {
    name: string;
    TypesDeriveTunnelRequest: TypesDeriveTunnelRequest;
}

export interface ApiFriendsNameVrrpPostRequest {
    name: string;
    TypesConfigureVRRPRequest: TypesConfigureVRRPRequest;
}

export interface ApiFriendsNameWireguardPostRequest {
    name: string;
    TypesDeriveWireguardRequest: TypesDeriveWireguardRequest;
}

export interface ApiFriendsPairPostRequest {
    TypesFriendPairRequest: TypesFriendPairRequest;
}

export interface ApiFriendsPollGetRequest {
    have?: string;
}

export interface ApiFriendsPostRequest {
    TypesAddFriendRequest: TypesAddFriendRequest;
}

export interface ApiFriendsPreviewPostRequest {
    TypesFriendPreviewRequest: TypesFriendPreviewRequest;
}

/**
 * 
 */
export class FriendsApi extends runtime.BaseAPI {

    /**
     * nft variables this node publishes to its friends
     */
    async apiFriendsExportsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TypesResponseArrayTypesFriendVar>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/api/friends/exports`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TypesResponseArrayTypesFriendVarFromJSON(jsonValue));
    }

    /**
     * nft variables this node publishes to its friends
     */
    async apiFriendsExportsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TypesResponseArrayTypesFriendVar> {
        const response = await this.apiFriendsExportsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * List configured friends
     */
    async apiFriendsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TypesResponseArrayTypesFriendInfo>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/api/friends`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TypesResponseArrayTypesFriendInfoFromJSON(jsonValue));
    }

    /**
     * List configured friends
     */
    async apiFriendsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TypesResponseArrayTypesFriendInfo> {
        const response = await this.apiFriendsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Friend hello/handshake
     */
    async apiFriendsHelloGetRaw(requestParameters: ApiFriendsHelloGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TypesResponseTypesFriendsHello>> {
        const queryParameters: any = {};

        if (requestParameters['challenge'] != null) {
            queryParameters['challenge'] = requestParameters['challenge'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/api/friends/hello`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TypesResponseTypesFriendsHelloFromJSON(jsonValue));
    }

    /**
     * Friend hello/handshake
     */
    async apiFriendsHelloGet(requestParameters: ApiFriendsHelloGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TypesResponseTypesFriendsHello> {
        const response = await this.apiFriendsHelloGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This node\'s interface addresses
     */
    async apiFriendsInterfacesGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TypesResponseArrayTypesFriendInterface>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/api/friends/interfaces`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TypesResponseArrayTypesFriendInterfaceFromJSON(jsonValue));
    }

    /**
     * This node\'s interface addresses
     */
    async apiFriendsInterfacesGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TypesResponseArrayTypesFriendInterface> {
        const response = await this.apiFriendsInterfacesGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Cached state we hold for a friend (status, interfaces, config)
     */
    async apiFriendsNameCacheGetRaw(requestParameters: ApiFriendsNameCacheGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TypesResponseFriendcacheCachedState>> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling apiFriendsNameCacheGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/api/friends/{name}/cache`.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TypesResponseFriendcacheCachedStateFromJSON(jsonValue));
    }

    /**
     * Cached state we hold for a friend (status, interfaces, config)
     */
    async apiFriendsNameCacheGet(requestParameters: ApiFriendsNameCacheGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TypesResponseFriendcacheCachedState> {
        const response = await this.apiFriendsNameCacheGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Force a health check + info refresh for one friend
     */
    async apiFriendsNameCheckPostRaw(requestParameters: ApiFriendsNameCheckPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TypesResponseTypesFriendStatus>> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling apiFriendsNameCheckPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/api/friends/{name}/check`.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TypesResponseTypesFriendStatusFromJSON(jsonValue));
    }

    /**
     * Force a health check + info refresh for one friend
     */
    async apiFriendsNameCheckPost(requestParameters: ApiFriendsNameCheckPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TypesResponseTypesFriendStatus> {
        const response = await this.apiFriendsNameCheckPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Fetch a friend\'s live config (falls back to cache when down)
     */
    async apiFriendsNameConfigGetRaw(requestParameters: ApiFriendsNameConfigGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TypesResponseConfigConfig>> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling apiFriendsNameConfigGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/api/friends/{name}/config`.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TypesResponseConfigConfigFromJSON(jsonValue));
    }

    /**
     * Fetch a friend\'s live config (falls back to cache when down)
     */
    async apiFriendsNameConfigGet(requestParameters: ApiFriendsNameConfigGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TypesResponseConfigConfig> {
        const response = await this.apiFriendsNameConfigGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Configure conntrackd HA with a friend (applies on both sides)
     */
    async apiFriendsNameConntrackPostRaw(requestParameters: ApiFriendsNameConntrackPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TypesResponseTypesConfigureConntrackResult>> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling apiFriendsNameConntrackPost().'
            );
        }

        if (requestParameters['TypesConfigureConntrackRequest'] == null) {
            throw new runtime.RequiredError(
                'TypesConfigureConntrackRequest',
                'Required parameter "TypesConfigureConntrackRequest" was null or undefined when calling apiFriendsNameConntrackPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/api/friends/{name}/conntrack`.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TypesConfigureConntrackRequestToJSON(requestParameters['TypesConfigureConntrackRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TypesResponseTypesConfigureConntrackResultFromJSON(jsonValue));
    }

    /**
     * Configure conntrackd HA with a friend (applies on both sides)
     */
    async apiFriendsNameConntrackPost(requestParameters: ApiFriendsNameConntrackPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TypesResponseTypesConfigureConntrackResult> {
        const response = await this.apiFriendsNameConntrackPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Remove a friend
     */
    async apiFriendsNameDeleteRaw(requestParameters: ApiFriendsNameDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TypesResponseTypesFriendDeleteResult>> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling apiFriendsNameDelete().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['confirm'] != null) {
            queryParameters['confirm'] = requestParameters['confirm'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/api/friends/{name}`.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TypesResponseTypesFriendDeleteResultFromJSON(jsonValue));
    }

    /**
     * Remove a friend
     */
    async apiFriendsNameDelete(requestParameters: ApiFriendsNameDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TypesResponseTypesFriendDeleteResult> {
        const response = await this.apiFriendsNameDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * A friend\'s interface addresses (cached fallback)
     */
    async apiFriendsNameInterfacesGetRaw(requestParameters: ApiFriendsNameInterfacesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TypesResponseArrayTypesFriendInterface>> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling apiFriendsNameInterfacesGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/api/friends/{name}/interfaces`.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TypesResponseArrayTypesFriendInterfaceFromJSON(jsonValue));
    }

    /**
     * A friend\'s interface addresses (cached fallback)
     */
    async apiFriendsNameInterfacesGet(requestParameters: ApiFriendsNameInterfacesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TypesResponseArrayTypesFriendInterface> {
        const response = await this.apiFriendsNameInterfacesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * nftables variables imported from a friend
     */
    async apiFriendsNameNftablesGetRaw(requestParameters: ApiFriendsNameNftablesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TypesResponseArrayRenderNftVar>> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling apiFriendsNameNftablesGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/api/friends/{name}/nftables`.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TypesResponseArrayRenderNftVarFromJSON(jsonValue));
    }

    /**
     * nftables variables imported from a friend
     */
    async apiFriendsNameNftablesGet(requestParameters: ApiFriendsNameNftablesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TypesResponseArrayRenderNftVar> {
        const response = await this.apiFriendsNameNftablesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Validate a friend\'s fingerprint and complete pairing
     */
    async apiFriendsNamePairPostRaw(requestParameters: ApiFriendsNamePairPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TypesResponseTypesFriendInfo>> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling apiFriendsNamePairPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/api/friends/{name}/pair`.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TypesVerifyFriendRequestToJSON(requestParameters['TypesVerifyFriendRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TypesResponseTypesFriendInfoFromJSON(jsonValue));
    }

    /**
     * Validate a friend\'s fingerprint and complete pairing
     */
    async apiFriendsNamePairPost(requestParameters: ApiFriendsNamePairPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TypesResponseTypesFriendInfo> {
        const response = await this.apiFriendsNamePairPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update a friend
     */
    async apiFriendsNamePutRaw(requestParameters: ApiFriendsNamePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TypesResponseTypesFriendInfo>> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling apiFriendsNamePut().'
            );
        }

        if (requestParameters['TypesUpdateFriendRequest'] == null) {
            throw new runtime.RequiredError(
                'TypesUpdateFriendRequest',
                'Required parameter "TypesUpdateFriendRequest" was null or undefined when calling apiFriendsNamePut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/api/friends/{name}`.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: TypesUpdateFriendRequestToJSON(requestParameters['TypesUpdateFriendRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TypesResponseTypesFriendInfoFromJSON(jsonValue));
    }

    /**
     * Update a friend
     */
    async apiFriendsNamePut(requestParameters: ApiFriendsNamePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TypesResponseTypesFriendInfo> {
        const response = await this.apiFriendsNamePutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Sync HA state to one friend
     */
    async apiFriendsNameSyncPostRaw(requestParameters: ApiFriendsNameSyncPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TypesResponseArrayManagersPushResult>> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling apiFriendsNameSyncPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/api/friends/{name}/sync`.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TypesResponseArrayManagersPushResultFromJSON(jsonValue));
    }

    /**
     * Sync HA state to one friend
     */
    async apiFriendsNameSyncPost(requestParameters: ApiFriendsNameSyncPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TypesResponseArrayManagersPushResult> {
        const response = await this.apiFriendsNameSyncPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Derive an IP tunnel to a friend
     */
    async apiFriendsNameTunnelPostRaw(requestParameters: ApiFriendsNameTunnelPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TypesResponseTypesDeriveTunnelResult>> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling apiFriendsNameTunnelPost().'
            );
        }

        if (requestParameters['TypesDeriveTunnelRequest'] == null) {
            throw new runtime.RequiredError(
                'TypesDeriveTunnelRequest',
                'Required parameter "TypesDeriveTunnelRequest" was null or undefined when calling apiFriendsNameTunnelPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/api/friends/{name}/tunnel`.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TypesDeriveTunnelRequestToJSON(requestParameters['TypesDeriveTunnelRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TypesResponseTypesDeriveTunnelResultFromJSON(jsonValue));
    }

    /**
     * Derive an IP tunnel to a friend
     */
    async apiFriendsNameTunnelPost(requestParameters: ApiFriendsNameTunnelPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TypesResponseTypesDeriveTunnelResult> {
        const response = await this.apiFriendsNameTunnelPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Configure a VRRP instance shared with a friend (applies on both sides)
     */
    async apiFriendsNameVrrpPostRaw(requestParameters: ApiFriendsNameVrrpPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TypesResponseTypesConfigureVRRPResult>> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling apiFriendsNameVrrpPost().'
            );
        }

        if (requestParameters['TypesConfigureVRRPRequest'] == null) {
            throw new runtime.RequiredError(
                'TypesConfigureVRRPRequest',
                'Required parameter "TypesConfigureVRRPRequest" was null or undefined when calling apiFriendsNameVrrpPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/api/friends/{name}/vrrp`.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TypesConfigureVRRPRequestToJSON(requestParameters['TypesConfigureVRRPRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TypesResponseTypesConfigureVRRPResultFromJSON(jsonValue));
    }

    /**
     * Configure a VRRP instance shared with a friend (applies on both sides)
     */
    async apiFriendsNameVrrpPost(requestParameters: ApiFriendsNameVrrpPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TypesResponseTypesConfigureVRRPResult> {
        const response = await this.apiFriendsNameVrrpPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Derive a WireGuard tunnel to a friend
     */
    async apiFriendsNameWireguardPostRaw(requestParameters: ApiFriendsNameWireguardPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TypesResponseTypesDeriveWireguardResult>> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling apiFriendsNameWireguardPost().'
            );
        }

        if (requestParameters['TypesDeriveWireguardRequest'] == null) {
            throw new runtime.RequiredError(
                'TypesDeriveWireguardRequest',
                'Required parameter "TypesDeriveWireguardRequest" was null or undefined when calling apiFriendsNameWireguardPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/api/friends/{name}/wireguard`.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TypesDeriveWireguardRequestToJSON(requestParameters['TypesDeriveWireguardRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TypesResponseTypesDeriveWireguardResultFromJSON(jsonValue));
    }

    /**
     * Derive a WireGuard tunnel to a friend
     */
    async apiFriendsNameWireguardPost(requestParameters: ApiFriendsNameWireguardPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TypesResponseTypesDeriveWireguardResult> {
        const response = await this.apiFriendsNameWireguardPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Complete identity pairing (friend-token)
     */
    async apiFriendsPairPostRaw(requestParameters: ApiFriendsPairPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TypesResponseTypesFriendPairResponse>> {
        if (requestParameters['TypesFriendPairRequest'] == null) {
            throw new runtime.RequiredError(
                'TypesFriendPairRequest',
                'Required parameter "TypesFriendPairRequest" was null or undefined when calling apiFriendsPairPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/api/friends/pair`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TypesFriendPairRequestToJSON(requestParameters['TypesFriendPairRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TypesResponseTypesFriendPairResponseFromJSON(jsonValue));
    }

    /**
     * Complete identity pairing (friend-token)
     */
    async apiFriendsPairPost(requestParameters: ApiFriendsPairPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TypesResponseTypesFriendPairResponse> {
        const response = await this.apiFriendsPairPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Batched, shared-key-encrypted friend poll
     */
    async apiFriendsPollGetRaw(requestParameters: ApiFriendsPollGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TypesResponseTypesFriendPoll>> {
        const queryParameters: any = {};

        if (requestParameters['have'] != null) {
            queryParameters['have'] = requestParameters['have'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/api/friends/poll`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TypesResponseTypesFriendPollFromJSON(jsonValue));
    }

    /**
     * Batched, shared-key-encrypted friend poll
     */
    async apiFriendsPollGet(requestParameters: ApiFriendsPollGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TypesResponseTypesFriendPoll> {
        const response = await this.apiFriendsPollGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Add a friend
     */
    async apiFriendsPostRaw(requestParameters: ApiFriendsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TypesResponseTypesFriendInfo>> {
        if (requestParameters['TypesAddFriendRequest'] == null) {
            throw new runtime.RequiredError(
                'TypesAddFriendRequest',
                'Required parameter "TypesAddFriendRequest" was null or undefined when calling apiFriendsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/api/friends`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TypesAddFriendRequestToJSON(requestParameters['TypesAddFriendRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TypesResponseTypesFriendInfoFromJSON(jsonValue));
    }

    /**
     * Add a friend
     */
    async apiFriendsPost(requestParameters: ApiFriendsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TypesResponseTypesFriendInfo> {
        const response = await this.apiFriendsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Preview a prospective friend\'s identity
     */
    async apiFriendsPreviewPostRaw(requestParameters: ApiFriendsPreviewPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TypesResponseTypesFriendPreview>> {
        if (requestParameters['TypesFriendPreviewRequest'] == null) {
            throw new runtime.RequiredError(
                'TypesFriendPreviewRequest',
                'Required parameter "TypesFriendPreviewRequest" was null or undefined when calling apiFriendsPreviewPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/api/friends/preview`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TypesFriendPreviewRequestToJSON(requestParameters['TypesFriendPreviewRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TypesResponseTypesFriendPreviewFromJSON(jsonValue));
    }

    /**
     * Preview a prospective friend\'s identity
     */
    async apiFriendsPreviewPost(requestParameters: ApiFriendsPreviewPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TypesResponseTypesFriendPreview> {
        const response = await this.apiFriendsPreviewPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Friend liveness/status snapshot
     */
    async apiFriendsStatusGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TypesResponseArrayTypesFriendStatus>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/api/friends/status`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TypesResponseArrayTypesFriendStatusFromJSON(jsonValue));
    }

    /**
     * Friend liveness/status snapshot
     */
    async apiFriendsStatusGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TypesResponseArrayTypesFriendStatus> {
        const response = await this.apiFriendsStatusGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Sync HA state to all friends
     */
    async apiFriendsSyncPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TypesResponseArrayManagersPushResult>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/api/friends/sync`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TypesResponseArrayManagersPushResultFromJSON(jsonValue));
    }

    /**
     * Sync HA state to all friends
     */
    async apiFriendsSyncPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TypesResponseArrayManagersPushResult> {
        const response = await this.apiFriendsSyncPostRaw(initOverrides);
        return await response.value();
    }

}
