/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  TypesCreateMacroRequest,
  TypesMacroApplyRequest,
  TypesResponseArrayTypesDiffLine,
  TypesResponseArrayTypesMacroInfo,
  TypesResponseTypesApplyResult,
  TypesResponseTypesMacroInfo,
  TypesResponseTypesStatusResponse,
} from '../models/index';
import {
    TypesCreateMacroRequestFromJSON,
    TypesCreateMacroRequestToJSON,
    TypesMacroApplyRequestFromJSON,
    TypesMacroApplyRequestToJSON,
    TypesResponseArrayTypesDiffLineFromJSON,
    TypesResponseArrayTypesDiffLineToJSON,
    TypesResponseArrayTypesMacroInfoFromJSON,
    TypesResponseArrayTypesMacroInfoToJSON,
    TypesResponseTypesApplyResultFromJSON,
    TypesResponseTypesApplyResultToJSON,
    TypesResponseTypesMacroInfoFromJSON,
    TypesResponseTypesMacroInfoToJSON,
    TypesResponseTypesStatusResponseFromJSON,
    TypesResponseTypesStatusResponseToJSON,
} from '../models/index';

export interface ApiMacrosIdApplyPostRequest {
    id: string;
    TypesMacroApplyRequest?: TypesMacroApplyRequest;
}

export interface ApiMacrosIdDeleteRequest {
    id: string;
}

export interface ApiMacrosIdDiffGetRequest {
    id: string;
}

export interface ApiMacrosIdGetRequest {
    id: string;
}

export interface ApiMacrosPostRequest {
    TypesCreateMacroRequest: TypesCreateMacroRequest;
}

/**
 * 
 */
export class MacrosApi extends runtime.BaseAPI {

    /**
     * List saved macros
     */
    async apiMacrosGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TypesResponseArrayTypesMacroInfo>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/api/macros`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TypesResponseArrayTypesMacroInfoFromJSON(jsonValue));
    }

    /**
     * List saved macros
     */
    async apiMacrosGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TypesResponseArrayTypesMacroInfo> {
        const response = await this.apiMacrosGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Apply a macro to the live config
     */
    async apiMacrosIdApplyPostRaw(requestParameters: ApiMacrosIdApplyPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TypesResponseTypesApplyResult>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiMacrosIdApplyPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/api/macros/{id}/apply`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TypesMacroApplyRequestToJSON(requestParameters['TypesMacroApplyRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TypesResponseTypesApplyResultFromJSON(jsonValue));
    }

    /**
     * Apply a macro to the live config
     */
    async apiMacrosIdApplyPost(requestParameters: ApiMacrosIdApplyPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TypesResponseTypesApplyResult> {
        const response = await this.apiMacrosIdApplyPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete a macro
     */
    async apiMacrosIdDeleteRaw(requestParameters: ApiMacrosIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TypesResponseTypesStatusResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiMacrosIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/api/macros/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TypesResponseTypesStatusResponseFromJSON(jsonValue));
    }

    /**
     * Delete a macro
     */
    async apiMacrosIdDelete(requestParameters: ApiMacrosIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TypesResponseTypesStatusResponse> {
        const response = await this.apiMacrosIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Diff a macro against the live config
     */
    async apiMacrosIdDiffGetRaw(requestParameters: ApiMacrosIdDiffGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TypesResponseArrayTypesDiffLine>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiMacrosIdDiffGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/api/macros/{id}/diff`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TypesResponseArrayTypesDiffLineFromJSON(jsonValue));
    }

    /**
     * Diff a macro against the live config
     */
    async apiMacrosIdDiffGet(requestParameters: ApiMacrosIdDiffGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TypesResponseArrayTypesDiffLine> {
        const response = await this.apiMacrosIdDiffGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a macro
     */
    async apiMacrosIdGetRaw(requestParameters: ApiMacrosIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TypesResponseTypesMacroInfo>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiMacrosIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/api/macros/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TypesResponseTypesMacroInfoFromJSON(jsonValue));
    }

    /**
     * Get a macro
     */
    async apiMacrosIdGet(requestParameters: ApiMacrosIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TypesResponseTypesMacroInfo> {
        const response = await this.apiMacrosIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Save current staged changes as a macro
     */
    async apiMacrosPostRaw(requestParameters: ApiMacrosPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TypesResponseTypesMacroInfo>> {
        if (requestParameters['TypesCreateMacroRequest'] == null) {
            throw new runtime.RequiredError(
                'TypesCreateMacroRequest',
                'Required parameter "TypesCreateMacroRequest" was null or undefined when calling apiMacrosPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/api/macros`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TypesCreateMacroRequestToJSON(requestParameters['TypesCreateMacroRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TypesResponseTypesMacroInfoFromJSON(jsonValue));
    }

    /**
     * Save current staged changes as a macro
     */
    async apiMacrosPost(requestParameters: ApiMacrosPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TypesResponseTypesMacroInfo> {
        const response = await this.apiMacrosPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
