/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  TypesResponseTypesLearnedRoutesResponse,
  TypesResponseTypesNeighborsResponse,
  TypesResponseTypesRoutesResponse,
} from '../models/index';
import {
    TypesResponseTypesLearnedRoutesResponseFromJSON,
    TypesResponseTypesLearnedRoutesResponseToJSON,
    TypesResponseTypesNeighborsResponseFromJSON,
    TypesResponseTypesNeighborsResponseToJSON,
    TypesResponseTypesRoutesResponseFromJSON,
    TypesResponseTypesRoutesResponseToJSON,
} from '../models/index';

export interface ApiRoutingNeighborsGetRequest {
    q?: string;
    family?: string;
}

export interface ApiRoutingRoutesGetRequest {
    q?: string;
    family?: string;
    proto?: string;
    offset?: number;
    limit?: number;
    default_only?: boolean;
}

/**
 * 
 */
export class RoutingApi extends runtime.BaseAPI {

    /**
     * Learned OSPF/BGP routes
     */
    async apiRoutingLearnedGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TypesResponseTypesLearnedRoutesResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/api/routing/learned`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TypesResponseTypesLearnedRoutesResponseFromJSON(jsonValue));
    }

    /**
     * Learned OSPF/BGP routes
     */
    async apiRoutingLearnedGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TypesResponseTypesLearnedRoutesResponse> {
        const response = await this.apiRoutingLearnedGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Kernel neighbor (ARP/NDP) table
     */
    async apiRoutingNeighborsGetRaw(requestParameters: ApiRoutingNeighborsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TypesResponseTypesNeighborsResponse>> {
        const queryParameters: any = {};

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        if (requestParameters['family'] != null) {
            queryParameters['family'] = requestParameters['family'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/api/routing/neighbors`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TypesResponseTypesNeighborsResponseFromJSON(jsonValue));
    }

    /**
     * Kernel neighbor (ARP/NDP) table
     */
    async apiRoutingNeighborsGet(requestParameters: ApiRoutingNeighborsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TypesResponseTypesNeighborsResponse> {
        const response = await this.apiRoutingNeighborsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Kernel routing table (filtered, paged)
     */
    async apiRoutingRoutesGetRaw(requestParameters: ApiRoutingRoutesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TypesResponseTypesRoutesResponse>> {
        const queryParameters: any = {};

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        if (requestParameters['family'] != null) {
            queryParameters['family'] = requestParameters['family'];
        }

        if (requestParameters['proto'] != null) {
            queryParameters['proto'] = requestParameters['proto'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['default_only'] != null) {
            queryParameters['default_only'] = requestParameters['default_only'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/api/routing/routes`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TypesResponseTypesRoutesResponseFromJSON(jsonValue));
    }

    /**
     * Kernel routing table (filtered, paged)
     */
    async apiRoutingRoutesGet(requestParameters: ApiRoutingRoutesGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TypesResponseTypesRoutesResponse> {
        const response = await this.apiRoutingRoutesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
