/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  TypesResponseArrayTypesSystemNic,
  TypesResponseTypesSetupStatus,
  TypesResponseTypesStatusResponse,
} from '../models/index';
import {
    TypesResponseArrayTypesSystemNicFromJSON,
    TypesResponseArrayTypesSystemNicToJSON,
    TypesResponseTypesSetupStatusFromJSON,
    TypesResponseTypesSetupStatusToJSON,
    TypesResponseTypesStatusResponseFromJSON,
    TypesResponseTypesStatusResponseToJSON,
} from '../models/index';

export interface ApiSetupOnboardingPutRequest {
    body?: object;
}

/**
 * 
 */
export class SetupApi extends runtime.BaseAPI {

    /**
     * Mark onboarding complete
     */
    async apiSetupCompletePostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TypesResponseTypesStatusResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/api/setup/complete`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TypesResponseTypesStatusResponseFromJSON(jsonValue));
    }

    /**
     * Mark onboarding complete
     */
    async apiSetupCompletePost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TypesResponseTypesStatusResponse> {
        const response = await this.apiSetupCompletePostRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get saved onboarding state
     */
    async apiSetupOnboardingGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/api/setup/onboarding`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get saved onboarding state
     */
    async apiSetupOnboardingGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.apiSetupOnboardingGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Save onboarding state
     */
    async apiSetupOnboardingPutRaw(requestParameters: ApiSetupOnboardingPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TypesResponseTypesStatusResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/api/setup/onboarding`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TypesResponseTypesStatusResponseFromJSON(jsonValue));
    }

    /**
     * Save onboarding state
     */
    async apiSetupOnboardingPut(requestParameters: ApiSetupOnboardingPutRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TypesResponseTypesStatusResponse> {
        const response = await this.apiSetupOnboardingPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Onboarding / setup status
     */
    async apiSetupStatusGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TypesResponseTypesSetupStatus>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/api/setup/status`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TypesResponseTypesSetupStatusFromJSON(jsonValue));
    }

    /**
     * Onboarding / setup status
     */
    async apiSetupStatusGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TypesResponseTypesSetupStatus> {
        const response = await this.apiSetupStatusGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * List physical system NICs
     */
    async apiSystemNicsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TypesResponseArrayTypesSystemNic>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/api/system/nics`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TypesResponseArrayTypesSystemNicFromJSON(jsonValue));
    }

    /**
     * List physical system NICs
     */
    async apiSystemNicsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TypesResponseArrayTypesSystemNic> {
        const response = await this.apiSystemNicsGetRaw(initOverrides);
        return await response.value();
    }

}
