/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  TypesResponseTypesNeighborStatsResponse,
  TypesResponseTypesProcessesResponse,
  TypesResponseTypesStatsHistoryResponse,
  TypesResponseTypesStatsResponse,
} from '../models/index';
import {
    TypesResponseTypesNeighborStatsResponseFromJSON,
    TypesResponseTypesNeighborStatsResponseToJSON,
    TypesResponseTypesProcessesResponseFromJSON,
    TypesResponseTypesProcessesResponseToJSON,
    TypesResponseTypesStatsHistoryResponseFromJSON,
    TypesResponseTypesStatsHistoryResponseToJSON,
    TypesResponseTypesStatsResponseFromJSON,
    TypesResponseTypesStatsResponseToJSON,
} from '../models/index';

export interface ApiStatsHistoryGetRequest {
    minutes?: number;
    iface?: string;
    series?: string;
}

/**
 * 
 */
export class StatsApi extends runtime.BaseAPI {

    /**
     * Live system / interface / routing stats
     */
    async apiStatsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TypesResponseTypesStatsResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/api/stats`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TypesResponseTypesStatsResponseFromJSON(jsonValue));
    }

    /**
     * Live system / interface / routing stats
     */
    async apiStatsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TypesResponseTypesStatsResponse> {
        const response = await this.apiStatsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Historical stats
     */
    async apiStatsHistoryGetRaw(requestParameters: ApiStatsHistoryGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TypesResponseTypesStatsHistoryResponse>> {
        const queryParameters: any = {};

        if (requestParameters['minutes'] != null) {
            queryParameters['minutes'] = requestParameters['minutes'];
        }

        if (requestParameters['iface'] != null) {
            queryParameters['iface'] = requestParameters['iface'];
        }

        if (requestParameters['series'] != null) {
            queryParameters['series'] = requestParameters['series'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/api/stats/history`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TypesResponseTypesStatsHistoryResponseFromJSON(jsonValue));
    }

    /**
     * Historical stats
     */
    async apiStatsHistoryGet(requestParameters: ApiStatsHistoryGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TypesResponseTypesStatsHistoryResponse> {
        const response = await this.apiStatsHistoryGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Latest stored neighbor stats
     */
    async apiStatsNeighborsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TypesResponseTypesNeighborStatsResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/api/stats/neighbors`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TypesResponseTypesNeighborStatsResponseFromJSON(jsonValue));
    }

    /**
     * Latest stored neighbor stats
     */
    async apiStatsNeighborsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TypesResponseTypesNeighborStatsResponse> {
        const response = await this.apiStatsNeighborsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Live process list
     */
    async apiStatsProcessesGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TypesResponseTypesProcessesResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/api/stats/processes`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TypesResponseTypesProcessesResponseFromJSON(jsonValue));
    }

    /**
     * Live process list
     */
    async apiStatsProcessesGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TypesResponseTypesProcessesResponse> {
        const response = await this.apiStatsProcessesGetRaw(initOverrides);
        return await response.value();
    }

}
