# routier:{{ .Hostname }} override in /etc/routier/templates/radvd/radvd.conf
{{ with .Routing }}{{ with .RADVD }}
{{- range $name, $iface := .Interfaces }}
interface {{ iface $name }} {
    AdvSendAdvert {{ if $iface.AdvSendAdvert }}on{{ else }}off{{ end }};
{{- if $iface.MaxRtrAdvInterval }}
    MaxRtrAdvInterval {{ $iface.MaxRtrAdvInterval }};
{{- end }}
{{- if $iface.MinRtrAdvInterval }}
    MinRtrAdvInterval {{ $iface.MinRtrAdvInterval }};
{{- end }}
{{- if $iface.AdvManagedFlag }}
    AdvManagedFlag on;
{{- end }}
{{- if $iface.AdvOtherConfigFlag }}
    AdvOtherConfigFlag on;
{{- end }}
{{- if $iface.AdvDefaultLifetime }}
    AdvDefaultLifetime {{ $iface.AdvDefaultLifetime }};
{{- end }}
{{- if $iface.AdvDefaultPreference }}
    AdvDefaultPreference {{ $iface.AdvDefaultPreference }};
{{- end }}
{{- if $iface.AdvLinkMTU }}
    AdvLinkMTU {{ $iface.AdvLinkMTU }};
{{- end }}
{{- range $iface.Prefixes }}

    prefix {{ .Prefix }} {
        AdvOnLink {{ if .AdvOnLink }}on{{ else }}off{{ end }};
        AdvAutonomous {{ if .AdvAutonomous }}on{{ else }}off{{ end }};
{{- if .AdvRouterAddr }}
        AdvRouterAddr on;
{{- end }}
{{- if .AdvValidLifetime }}
        AdvValidLifetime {{ .AdvValidLifetime }};
{{- end }}
{{- if .AdvPreferredLifetime }}
        AdvPreferredLifetime {{ .AdvPreferredLifetime }};
{{- end }}
    };
{{- end }}
{{- with $iface.RDNSS }}

    RDNSS {{ join .Servers " " }} {
{{- if .Lifetime }}
        AdvRDNSSLifetime {{ .Lifetime }};
{{- end }}
    };
{{- end }}
{{- range $iface.Routes }}

    route {{ .Prefix }} {
{{- if .Lifetime }}
        AdvRouteLifetime {{ .Lifetime }};
{{- end }}
{{- if .Preference }}
        AdvRoutePreference {{ .Preference }};
{{- end }}
    };
{{- end }}
};
{{ end }}
{{- end }}{{ end }}
