# routier:{{ .Hostname }}
{{- range $k, $v := .Sysctl }}
{{ renderStr $k }} = {{ renderStr $v }}
{{- end }}
{{- if dnsNeedsNonlocalBind }}
net.ipv4.ip_nonlocal_bind = 1
net.ipv6.ip_nonlocal_bind = 1
{{- end }}
