package main

import (
	"go/format"
	"testing"
)

type styleCase struct {
	name   string
	source string
	rule   string
}

func TestStyleRules(t *testing.T) {
	cases := []styleCase{
		{name: "adjacent error check", source: "package fixture\nfunc run() {\nx, err := load()\nif err != nil { return }\n\nuse(x)\n}\n"},
		{name: "missing separator", source: "package fixture\nfunc run() {\nif ready { use() }\nnext()\n}\n", rule: "block-spacing"},
		{name: "separator across comment", source: "package fixture\nfunc run() {\nif ready { use() }\n//nolint:unused\nnext()\n}\n", rule: "block-spacing"},
		{name: "split error check", source: "package fixture\nfunc run() {\nx, parseErr := load()\n\nif parseErr != nil { return }\n\nuse(x)\n}\n", rule: "error-spacing"},
		{name: "switch body separator", source: "package fixture\nfunc run() { switch mode { case 1:\nif ready { use() }\nnext()\n} }\n", rule: "block-spacing"},
		{name: "select body separator", source: "package fixture\nfunc run() { select { case <-done:\nif ready { use() }\nnext()\n} }\n", rule: "block-spacing"},
		{name: "named type", source: "package fixture\ntype request struct { Name string }\n"},
		{name: "anonymous model", source: "package fixture\nvar request struct { Name string }\n", rule: "named-struct"},
		{name: "anonymous elements", source: "package fixture\nvar requests []struct { Name string }\n", rule: "named-struct"},
		{name: "prose", source: "package fixture\n// explain the code\nfunc run() {}\n", rule: "comments"},
		{name: "swag", source: "package fixture\n// @Summary run\nfunc run() {}\n"},
		{name: "generated", source: "// Code generated by fixture. DO NOT EDIT.\n\npackage fixture\n// generator prose\nvar request struct { Name string }\n"},
		{name: "directive", source: "//go:build linux\n\npackage fixture\n"},
		{name: "cgo preamble", source: "package fixture\n/*\n#include <stdlib.h>\n*/\nimport \"C\"\n"},
		{name: "long callback", source: "package fixture\nvar run = func() {\none()\ntwo()\nthree()\nfour()\n}\n", rule: "named-function"},
		{name: "short callback", source: "package fixture\nfunc run() { defer func() { cleanup() }() }\n"},
		{name: "unrelated RunE", source: "package fixture\nvar command = Command{RunE: func() {\none()\ntwo()\nthree()\nfour()\n}}\n", rule: "named-function"},
		{name: "cobra handler", source: "package fixture\nimport \"github.com/spf13/cobra\"\nvar command = cobra.Command{RunE: func() {\none()\ntwo()\nthree()\nfour()\n}}\n"},
	}
	for _, test := range cases {
		formatted, err := format.Source([]byte(test.source))
		if err != nil {
			t.Fatalf("%s: %v", test.name, err)
		}

		issues := checkSource(test.name+".go", formatted)
		if test.rule == "" {
			if len(issues) != 0 {
				t.Errorf("%s: unexpected issues: %+v", test.name, issues)
			}

			continue
		}

		found := false
		for _, issue := range issues {
			if issue.rule == test.rule {
				found = true
			}
		}

		if !found {
			t.Errorf("%s: missing %s: %+v", test.name, test.rule, issues)
		}
	}
}

func TestGofmtRule(t *testing.T) {
	issues := checkSource("fixture.go", []byte("package fixture\nfunc run( ){ }\n"))
	if len(issues) == 0 || issues[0].rule != "gofmt" {
		t.Fatalf("missing formatting diagnostic: %+v", issues)
	}
}
