package render

import (
	"strings"

	"github.com/ChevalRouting/routier/pkg/config"
)

const (
	lldpdConfDest    = "/etc/lldpd.conf"
	lldpdOptsDest    = "/etc/conf.d/lldpd"
	lldpdConfName    = "lldp/lldpd.conf"
	lldpdOptsName    = "lldp/conf.d"
	lldpdDescription = "Routier"
)

func lldpEnabled(cfg *config.Config) bool {
	return cfg.Monitoring != nil && cfg.Monitoring.LLDP != nil && cfg.Monitoring.LLDP.Enabled
}

func renderLLDP(cfg *config.Config) ([]Output, error) {
	if !lldpEnabled(cfg) {
		return nil, nil
	}

	lldp := cfg.Monitoring.LLDP

	var opts []string
	if lldp.CDP {
		opts = append(opts, "-c")
	}

	if !lldp.Transmit {
		opts = append(opts, "-r")
	}

	if len(lldp.Interfaces) > 0 {
		opts = append(opts, "-I "+strings.Join(lldp.Interfaces, ","))
	}

	confd := "# Generated by Routier - do not edit\nLLDPD_OPTS=\"" + strings.Join(opts, " ") + "\"\n"

	return []Output{
		{Name: lldpdOptsName, Dest: lldpdOptsDest, Content: confd},
		{Name: lldpdConfName, Dest: lldpdConfDest, Content: lldpdConf(cfg.Hostname)},
	}, nil
}

func lldpdConf(hostname string) string {
	var b strings.Builder
	b.WriteString("# Generated by Routier - do not edit\n")
	b.WriteString("configure lldp portidsubtype ifname\n")
	b.WriteString("configure system description \"" + lldpdDescription + "\"\n")
	b.WriteString("configure system platform \"" + lldpdDescription + "\"\n")
	if hostname != "" {
		b.WriteString("configure system hostname \"" + hostname + "\"\n")
	}

	return b.String()
}
