/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BindZoneRecord } from './BindZoneRecord';
import {
    BindZoneRecordFromJSON,
    BindZoneRecordFromJSONTyped,
    BindZoneRecordToJSON,
    BindZoneRecordToJSONTyped,
} from './BindZoneRecord';

/**
 * 
 * @export
 * @interface BindZoneView
 */
export interface BindZoneView {
    /**
     * 
     * @type {boolean}
     * @memberof BindZoneView
     */
    answered: boolean;
    /**
     * 
     * @type {string}
     * @memberof BindZoneView
     */
    name: string;
    /**
     * 
     * @type {Array<BindZoneRecord>}
     * @memberof BindZoneView
     */
    records?: Array<BindZoneRecord>;
    /**
     * 
     * @type {number}
     * @memberof BindZoneView
     */
    serial: number;
}

/**
 * Check if a given object implements the BindZoneView interface.
 */
export function instanceOfBindZoneView(value: object): value is BindZoneView {
    if (!('answered' in value) || value['answered'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('serial' in value) || value['serial'] === undefined) return false;
    return true;
}

export function BindZoneViewFromJSON(json: any): BindZoneView {
    return BindZoneViewFromJSONTyped(json, false);
}

export function BindZoneViewFromJSONTyped(json: any, ignoreDiscriminator: boolean): BindZoneView {
    if (json == null) {
        return json;
    }
    return {
        
        'answered': json['answered'],
        'name': json['name'],
        'records': json['records'] == null ? undefined : ((json['records'] as Array<any>).map(BindZoneRecordFromJSON)),
        'serial': json['serial'],
    };
}

export function BindZoneViewToJSON(json: any): BindZoneView {
    return BindZoneViewToJSONTyped(json, false);
}

export function BindZoneViewToJSONTyped(value?: BindZoneView | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'answered': value['answered'],
        'name': value['name'],
        'records': value['records'] == null ? undefined : ((value['records'] as Array<any>).map(BindZoneRecordToJSON)),
        'serial': value['serial'],
    };
}

