/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BindZoneRecord
 */
export interface BindZoneRecord {
    /**
     * 
     * @type {string}
     * @memberof BindZoneRecord
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof BindZoneRecord
     */
    priority?: number;
    /**
     * 
     * @type {number}
     * @memberof BindZoneRecord
     */
    ttl?: number;
    /**
     * 
     * @type {string}
     * @memberof BindZoneRecord
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof BindZoneRecord
     */
    value: string;
}

/**
 * Check if a given object implements the BindZoneRecord interface.
 */
export function instanceOfBindZoneRecord(value: object): value is BindZoneRecord {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function BindZoneRecordFromJSON(json: any): BindZoneRecord {
    return BindZoneRecordFromJSONTyped(json, false);
}

export function BindZoneRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): BindZoneRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'priority': json['priority'] == null ? undefined : json['priority'],
        'ttl': json['ttl'] == null ? undefined : json['ttl'],
        'type': json['type'],
        'value': json['value'],
    };
}

export function BindZoneRecordToJSON(json: any): BindZoneRecord {
    return BindZoneRecordToJSONTyped(json, false);
}

export function BindZoneRecordToJSONTyped(value?: BindZoneRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'priority': value['priority'],
        'ttl': value['ttl'],
        'type': value['type'],
        'value': value['value'],
    };
}

