/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BindStatus
 */
export interface BindStatus {
    /**
     * 
     * @type {string}
     * @memberof BindStatus
     */
    boot_time?: string;
    /**
     * 
     * @type {string}
     * @memberof BindStatus
     */
    config_time?: string;
    /**
     * 
     * @type {number}
     * @memberof BindStatus
     */
    recursive_high_water: number;
    /**
     * 
     * @type {boolean}
     * @memberof BindStatus
     */
    running: boolean;
    /**
     * 
     * @type {string}
     * @memberof BindStatus
     */
    version?: string;
    /**
     * 
     * @type {number}
     * @memberof BindStatus
     */
    zones: number;
}

/**
 * Check if a given object implements the BindStatus interface.
 */
export function instanceOfBindStatus(value: object): value is BindStatus {
    if (!('recursive_high_water' in value) || value['recursive_high_water'] === undefined) return false;
    if (!('running' in value) || value['running'] === undefined) return false;
    if (!('zones' in value) || value['zones'] === undefined) return false;
    return true;
}

export function BindStatusFromJSON(json: any): BindStatus {
    return BindStatusFromJSONTyped(json, false);
}

export function BindStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): BindStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'boot_time': json['boot_time'] == null ? undefined : json['boot_time'],
        'config_time': json['config_time'] == null ? undefined : json['config_time'],
        'recursive_high_water': json['recursive_high_water'],
        'running': json['running'],
        'version': json['version'] == null ? undefined : json['version'],
        'zones': json['zones'],
    };
}

export function BindStatusToJSON(json: any): BindStatus {
    return BindStatusToJSONTyped(json, false);
}

export function BindStatusToJSONTyped(value?: BindStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'boot_time': value['boot_time'],
        'config_time': value['config_time'],
        'recursive_high_water': value['recursive_high_water'],
        'running': value['running'],
        'version': value['version'],
        'zones': value['zones'],
    };
}

