/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BindAnswer
 */
export interface BindAnswer {
    /**
     * 
     * @type {string}
     * @memberof BindAnswer
     */
    _class: string;
    /**
     * 
     * @type {string}
     * @memberof BindAnswer
     */
    data: string;
    /**
     * 
     * @type {string}
     * @memberof BindAnswer
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof BindAnswer
     */
    ttl: number;
    /**
     * 
     * @type {string}
     * @memberof BindAnswer
     */
    type: string;
}

/**
 * Check if a given object implements the BindAnswer interface.
 */
export function instanceOfBindAnswer(value: object): value is BindAnswer {
    if (!('_class' in value) || value['_class'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('ttl' in value) || value['ttl'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function BindAnswerFromJSON(json: any): BindAnswer {
    return BindAnswerFromJSONTyped(json, false);
}

export function BindAnswerFromJSONTyped(json: any, ignoreDiscriminator: boolean): BindAnswer {
    if (json == null) {
        return json;
    }
    return {
        
        '_class': json['class'],
        'data': json['data'],
        'name': json['name'],
        'ttl': json['ttl'],
        'type': json['type'],
    };
}

export function BindAnswerToJSON(json: any): BindAnswer {
    return BindAnswerToJSONTyped(json, false);
}

export function BindAnswerToJSONTyped(value?: BindAnswer | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'class': value['_class'],
        'data': value['data'],
        'name': value['name'],
        'ttl': value['ttl'],
        'type': value['type'],
    };
}

