/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BindZoneView } from './BindZoneView';
import {
    BindZoneViewFromJSON,
    BindZoneViewFromJSONTyped,
    BindZoneViewToJSON,
    BindZoneViewToJSONTyped,
} from './BindZoneView';
import type { BindStat } from './BindStat';
import {
    BindStatFromJSON,
    BindStatFromJSONTyped,
    BindStatToJSON,
    BindStatToJSONTyped,
} from './BindStat';
import type { BindStatus } from './BindStatus';
import {
    BindStatusFromJSON,
    BindStatusFromJSONTyped,
    BindStatusToJSON,
    BindStatusToJSONTyped,
} from './BindStatus';

/**
 * 
 * @export
 * @interface BindOverview
 */
export interface BindOverview {
    /**
     * 
     * @type {Array<string>}
     * @memberof BindOverview
     */
    listen?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof BindOverview
     */
    running: boolean;
    /**
     * 
     * @type {Array<BindStat>}
     * @memberof BindOverview
     */
    stats?: Array<BindStat>;
    /**
     * 
     * @type {BindStatus}
     * @memberof BindOverview
     */
    status?: BindStatus;
    /**
     * 
     * @type {Array<BindZoneView>}
     * @memberof BindOverview
     */
    zones?: Array<BindZoneView>;
}

/**
 * Check if a given object implements the BindOverview interface.
 */
export function instanceOfBindOverview(value: object): value is BindOverview {
    if (!('running' in value) || value['running'] === undefined) return false;
    return true;
}

export function BindOverviewFromJSON(json: any): BindOverview {
    return BindOverviewFromJSONTyped(json, false);
}

export function BindOverviewFromJSONTyped(json: any, ignoreDiscriminator: boolean): BindOverview {
    if (json == null) {
        return json;
    }
    return {
        
        'listen': json['listen'] == null ? undefined : json['listen'],
        'running': json['running'],
        'stats': json['stats'] == null ? undefined : ((json['stats'] as Array<any>).map(BindStatFromJSON)),
        'status': json['status'] == null ? undefined : BindStatusFromJSON(json['status']),
        'zones': json['zones'] == null ? undefined : ((json['zones'] as Array<any>).map(BindZoneViewFromJSON)),
    };
}

export function BindOverviewToJSON(json: any): BindOverview {
    return BindOverviewToJSONTyped(json, false);
}

export function BindOverviewToJSONTyped(value?: BindOverview | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'listen': value['listen'],
        'running': value['running'],
        'stats': value['stats'] == null ? undefined : ((value['stats'] as Array<any>).map(BindStatToJSON)),
        'status': BindStatusToJSON(value['status']),
        'zones': value['zones'] == null ? undefined : ((value['zones'] as Array<any>).map(BindZoneViewToJSON)),
    };
}

