/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConfigDNSZone } from './ConfigDNSZone';
import {
    ConfigDNSZoneFromJSON,
    ConfigDNSZoneFromJSONTyped,
    ConfigDNSZoneToJSON,
    ConfigDNSZoneToJSONTyped,
} from './ConfigDNSZone';
import type { ConfigDNSForward } from './ConfigDNSForward';
import {
    ConfigDNSForwardFromJSON,
    ConfigDNSForwardFromJSONTyped,
    ConfigDNSForwardToJSON,
    ConfigDNSForwardToJSONTyped,
} from './ConfigDNSForward';

/**
 * 
 * @export
 * @interface ConfigDNSView
 */
export interface ConfigDNSView {
    /**
     * 
     * @type {Array<string>}
     * @memberof ConfigDNSView
     */
    extra?: Array<string>;
    /**
     * 
     * @type {Array<ConfigDNSForward>}
     * @memberof ConfigDNSView
     */
    forward?: Array<ConfigDNSForward>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ConfigDNSView
     */
    match_from?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ConfigDNSView
     */
    name: string;
    /**
     * 
     * @type {boolean}
     * @memberof ConfigDNSView
     */
    recursion?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof ConfigDNSView
     */
    upstreams?: Array<string>;
    /**
     * 
     * @type {Array<ConfigDNSZone>}
     * @memberof ConfigDNSView
     */
    zones?: Array<ConfigDNSZone>;
}

/**
 * Check if a given object implements the ConfigDNSView interface.
 */
export function instanceOfConfigDNSView(value: object): value is ConfigDNSView {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function ConfigDNSViewFromJSON(json: any): ConfigDNSView {
    return ConfigDNSViewFromJSONTyped(json, false);
}

export function ConfigDNSViewFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigDNSView {
    if (json == null) {
        return json;
    }
    return {
        
        'extra': json['extra'] == null ? undefined : json['extra'],
        'forward': json['forward'] == null ? undefined : ((json['forward'] as Array<any>).map(ConfigDNSForwardFromJSON)),
        'match_from': json['match_from'] == null ? undefined : json['match_from'],
        'name': json['name'],
        'recursion': json['recursion'] == null ? undefined : json['recursion'],
        'upstreams': json['upstreams'] == null ? undefined : json['upstreams'],
        'zones': json['zones'] == null ? undefined : ((json['zones'] as Array<any>).map(ConfigDNSZoneFromJSON)),
    };
}

export function ConfigDNSViewToJSON(json: any): ConfigDNSView {
    return ConfigDNSViewToJSONTyped(json, false);
}

export function ConfigDNSViewToJSONTyped(value?: ConfigDNSView | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'extra': value['extra'],
        'forward': value['forward'] == null ? undefined : ((value['forward'] as Array<any>).map(ConfigDNSForwardToJSON)),
        'match_from': value['match_from'],
        'name': value['name'],
        'recursion': value['recursion'],
        'upstreams': value['upstreams'],
        'zones': value['zones'] == null ? undefined : ((value['zones'] as Array<any>).map(ConfigDNSZoneToJSON)),
    };
}

