/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfigDNSForward
 */
export interface ConfigDNSForward {
    /**
     * 
     * @type {boolean}
     * @memberof ConfigDNSForward
     */
    dnssec?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ConfigDNSForward
     */
    domain: string;
    /**
     * 
     * @type {boolean}
     * @memberof ConfigDNSForward
     */
    first_try?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof ConfigDNSForward
     */
    servers?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof ConfigDNSForward
     */
    tls_upstream?: boolean;
}

/**
 * Check if a given object implements the ConfigDNSForward interface.
 */
export function instanceOfConfigDNSForward(value: object): value is ConfigDNSForward {
    if (!('domain' in value) || value['domain'] === undefined) return false;
    return true;
}

export function ConfigDNSForwardFromJSON(json: any): ConfigDNSForward {
    return ConfigDNSForwardFromJSONTyped(json, false);
}

export function ConfigDNSForwardFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigDNSForward {
    if (json == null) {
        return json;
    }
    return {
        
        'dnssec': json['dnssec'] == null ? undefined : json['dnssec'],
        'domain': json['domain'],
        'first_try': json['first_try'] == null ? undefined : json['first_try'],
        'servers': json['servers'] == null ? undefined : json['servers'],
        'tls_upstream': json['tls_upstream'] == null ? undefined : json['tls_upstream'],
    };
}

export function ConfigDNSForwardToJSON(json: any): ConfigDNSForward {
    return ConfigDNSForwardToJSONTyped(json, false);
}

export function ConfigDNSForwardToJSONTyped(value?: ConfigDNSForward | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'dnssec': value['dnssec'],
        'domain': value['domain'],
        'first_try': value['first_try'],
        'servers': value['servers'],
        'tls_upstream': value['tls_upstream'],
    };
}

