/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfigTunnel
 */
export interface ConfigTunnel {
    /**
     * 
     * @type {Array<string>}
     * @memberof ConfigTunnel
     */
    addresses?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ConfigTunnel
     */
    friend?: string;
    /**
     * 
     * @type {string}
     * @memberof ConfigTunnel
     */
    local?: string;
    /**
     * 
     * @type {string}
     * @memberof ConfigTunnel
     */
    mode: string;
    /**
     * 
     * @type {number}
     * @memberof ConfigTunnel
     */
    mtu?: number;
    /**
     * 
     * @type {string}
     * @memberof ConfigTunnel
     */
    remote?: string;
    /**
     * 
     * @type {number}
     * @memberof ConfigTunnel
     */
    ttl?: number;
}

/**
 * Check if a given object implements the ConfigTunnel interface.
 */
export function instanceOfConfigTunnel(value: object): value is ConfigTunnel {
    if (!('mode' in value) || value['mode'] === undefined) return false;
    return true;
}

export function ConfigTunnelFromJSON(json: any): ConfigTunnel {
    return ConfigTunnelFromJSONTyped(json, false);
}

export function ConfigTunnelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigTunnel {
    if (json == null) {
        return json;
    }
    return {
        
        'addresses': json['addresses'] == null ? undefined : json['addresses'],
        'friend': json['friend'] == null ? undefined : json['friend'],
        'local': json['local'] == null ? undefined : json['local'],
        'mode': json['mode'],
        'mtu': json['mtu'] == null ? undefined : json['mtu'],
        'remote': json['remote'] == null ? undefined : json['remote'],
        'ttl': json['ttl'] == null ? undefined : json['ttl'],
    };
}

export function ConfigTunnelToJSON(json: any): ConfigTunnel {
    return ConfigTunnelToJSONTyped(json, false);
}

export function ConfigTunnelToJSONTyped(value?: ConfigTunnel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'addresses': value['addresses'],
        'friend': value['friend'],
        'local': value['local'],
        'mode': value['mode'],
        'mtu': value['mtu'],
        'remote': value['remote'],
        'ttl': value['ttl'],
    };
}

