/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfigFriendIdentity
 */
export interface ConfigFriendIdentity {
    /**
     * 
     * @type {string}
     * @memberof ConfigFriendIdentity
     */
    fingerprint?: string;
    /**
     * 
     * @type {string}
     * @memberof ConfigFriendIdentity
     */
    public_key?: string;
    /**
     * 
     * @type {string}
     * @memberof ConfigFriendIdentity
     */
    x25519_public_key?: string;
}

/**
 * Check if a given object implements the ConfigFriendIdentity interface.
 */
export function instanceOfConfigFriendIdentity(value: object): value is ConfigFriendIdentity {
    return true;
}

export function ConfigFriendIdentityFromJSON(json: any): ConfigFriendIdentity {
    return ConfigFriendIdentityFromJSONTyped(json, false);
}

export function ConfigFriendIdentityFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigFriendIdentity {
    if (json == null) {
        return json;
    }
    return {
        
        'fingerprint': json['fingerprint'] == null ? undefined : json['fingerprint'],
        'public_key': json['public_key'] == null ? undefined : json['public_key'],
        'x25519_public_key': json['x25519_public_key'] == null ? undefined : json['x25519_public_key'],
    };
}

export function ConfigFriendIdentityToJSON(json: any): ConfigFriendIdentity {
    return ConfigFriendIdentityToJSONTyped(json, false);
}

export function ConfigFriendIdentityToJSONTyped(value?: ConfigFriendIdentity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fingerprint': value['fingerprint'],
        'public_key': value['public_key'],
        'x25519_public_key': value['x25519_public_key'],
    };
}

