/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfigVXLAN
 */
export interface ConfigVXLAN {
    /**
     * 
     * @type {boolean}
     * @memberof ConfigVXLAN
     */
    external?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ConfigVXLAN
     */
    group?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ConfigVXLAN
     */
    learning?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ConfigVXLAN
     */
    local?: string;
    /**
     * 
     * @type {number}
     * @memberof ConfigVXLAN
     */
    port?: number;
    /**
     * 
     * @type {string}
     * @memberof ConfigVXLAN
     */
    remote?: string;
    /**
     * 
     * @type {number}
     * @memberof ConfigVXLAN
     */
    vni?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ConfigVXLAN
     */
    vnifilter?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ConfigVXLAN
     */
    vtep?: string;
}

/**
 * Check if a given object implements the ConfigVXLAN interface.
 */
export function instanceOfConfigVXLAN(value: object): value is ConfigVXLAN {
    return true;
}

export function ConfigVXLANFromJSON(json: any): ConfigVXLAN {
    return ConfigVXLANFromJSONTyped(json, false);
}

export function ConfigVXLANFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigVXLAN {
    if (json == null) {
        return json;
    }
    return {
        
        'external': json['external'] == null ? undefined : json['external'],
        'group': json['group'] == null ? undefined : json['group'],
        'learning': json['learning'] == null ? undefined : json['learning'],
        'local': json['local'] == null ? undefined : json['local'],
        'port': json['port'] == null ? undefined : json['port'],
        'remote': json['remote'] == null ? undefined : json['remote'],
        'vni': json['vni'] == null ? undefined : json['vni'],
        'vnifilter': json['vnifilter'] == null ? undefined : json['vnifilter'],
        'vtep': json['vtep'] == null ? undefined : json['vtep'],
    };
}

export function ConfigVXLANToJSON(json: any): ConfigVXLAN {
    return ConfigVXLANToJSONTyped(json, false);
}

export function ConfigVXLANToJSONTyped(value?: ConfigVXLAN | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'external': value['external'],
        'group': value['group'],
        'learning': value['learning'],
        'local': value['local'],
        'port': value['port'],
        'remote': value['remote'],
        'vni': value['vni'],
        'vnifilter': value['vnifilter'],
        'vtep': value['vtep'],
    };
}

