/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConfigGAIEntry } from './ConfigGAIEntry';
import {
    ConfigGAIEntryFromJSON,
    ConfigGAIEntryFromJSONTyped,
    ConfigGAIEntryToJSON,
    ConfigGAIEntryToJSONTyped,
} from './ConfigGAIEntry';

/**
 * 
 * @export
 * @interface ConfigGAIConfig
 */
export interface ConfigGAIConfig {
    /**
     * 
     * @type {Array<ConfigGAIEntry>}
     * @memberof ConfigGAIConfig
     */
    label?: Array<ConfigGAIEntry>;
    /**
     * 
     * @type {Array<ConfigGAIEntry>}
     * @memberof ConfigGAIConfig
     */
    precedence?: Array<ConfigGAIEntry>;
}

/**
 * Check if a given object implements the ConfigGAIConfig interface.
 */
export function instanceOfConfigGAIConfig(value: object): value is ConfigGAIConfig {
    return true;
}

export function ConfigGAIConfigFromJSON(json: any): ConfigGAIConfig {
    return ConfigGAIConfigFromJSONTyped(json, false);
}

export function ConfigGAIConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigGAIConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'label': json['label'] == null ? undefined : ((json['label'] as Array<any>).map(ConfigGAIEntryFromJSON)),
        'precedence': json['precedence'] == null ? undefined : ((json['precedence'] as Array<any>).map(ConfigGAIEntryFromJSON)),
    };
}

export function ConfigGAIConfigToJSON(json: any): ConfigGAIConfig {
    return ConfigGAIConfigToJSONTyped(json, false);
}

export function ConfigGAIConfigToJSONTyped(value?: ConfigGAIConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'label': value['label'] == null ? undefined : ((value['label'] as Array<any>).map(ConfigGAIEntryToJSON)),
        'precedence': value['precedence'] == null ? undefined : ((value['precedence'] as Array<any>).map(ConfigGAIEntryToJSON)),
    };
}

