/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfigBFDProfile
 */
export interface ConfigBFDProfile {
    /**
     * 
     * @type {number}
     * @memberof ConfigBFDProfile
     */
    detect_multiplier?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ConfigBFDProfile
     */
    echo_mode?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof ConfigBFDProfile
     */
    extra?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof ConfigBFDProfile
     */
    minimum_ttl?: number;
    /**
     * 
     * @type {string}
     * @memberof ConfigBFDProfile
     */
    name: string;
    /**
     * 
     * @type {boolean}
     * @memberof ConfigBFDProfile
     */
    passive_mode?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ConfigBFDProfile
     */
    receive_interval?: number;
    /**
     * 
     * @type {number}
     * @memberof ConfigBFDProfile
     */
    transmit_interval?: number;
}

/**
 * Check if a given object implements the ConfigBFDProfile interface.
 */
export function instanceOfConfigBFDProfile(value: object): value is ConfigBFDProfile {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function ConfigBFDProfileFromJSON(json: any): ConfigBFDProfile {
    return ConfigBFDProfileFromJSONTyped(json, false);
}

export function ConfigBFDProfileFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigBFDProfile {
    if (json == null) {
        return json;
    }
    return {
        
        'detect_multiplier': json['detect_multiplier'] == null ? undefined : json['detect_multiplier'],
        'echo_mode': json['echo_mode'] == null ? undefined : json['echo_mode'],
        'extra': json['extra'] == null ? undefined : json['extra'],
        'minimum_ttl': json['minimum_ttl'] == null ? undefined : json['minimum_ttl'],
        'name': json['name'],
        'passive_mode': json['passive_mode'] == null ? undefined : json['passive_mode'],
        'receive_interval': json['receive_interval'] == null ? undefined : json['receive_interval'],
        'transmit_interval': json['transmit_interval'] == null ? undefined : json['transmit_interval'],
    };
}

export function ConfigBFDProfileToJSON(json: any): ConfigBFDProfile {
    return ConfigBFDProfileToJSONTyped(json, false);
}

export function ConfigBFDProfileToJSONTyped(value?: ConfigBFDProfile | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'detect_multiplier': value['detect_multiplier'],
        'echo_mode': value['echo_mode'],
        'extra': value['extra'],
        'minimum_ttl': value['minimum_ttl'],
        'name': value['name'],
        'passive_mode': value['passive_mode'],
        'receive_interval': value['receive_interval'],
        'transmit_interval': value['transmit_interval'],
    };
}

