/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfigStaticRoute
 */
export interface ConfigStaticRoute {
    /**
     * 
     * @type {string}
     * @memberof ConfigStaticRoute
     */
    destination: string;
    /**
     * 
     * @type {string}
     * @memberof ConfigStaticRoute
     */
    dev?: string;
    /**
     * 
     * @type {number}
     * @memberof ConfigStaticRoute
     */
    metric?: number;
    /**
     * 
     * @type {string}
     * @memberof ConfigStaticRoute
     */
    via?: string;
}

/**
 * Check if a given object implements the ConfigStaticRoute interface.
 */
export function instanceOfConfigStaticRoute(value: object): value is ConfigStaticRoute {
    if (!('destination' in value) || value['destination'] === undefined) return false;
    return true;
}

export function ConfigStaticRouteFromJSON(json: any): ConfigStaticRoute {
    return ConfigStaticRouteFromJSONTyped(json, false);
}

export function ConfigStaticRouteFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigStaticRoute {
    if (json == null) {
        return json;
    }
    return {
        
        'destination': json['destination'],
        'dev': json['dev'] == null ? undefined : json['dev'],
        'metric': json['metric'] == null ? undefined : json['metric'],
        'via': json['via'] == null ? undefined : json['via'],
    };
}

export function ConfigStaticRouteToJSON(json: any): ConfigStaticRoute {
    return ConfigStaticRouteToJSONTyped(json, false);
}

export function ConfigStaticRouteToJSONTyped(value?: ConfigStaticRoute | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'destination': value['destination'],
        'dev': value['dev'],
        'metric': value['metric'],
        'via': value['via'],
    };
}

