/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConfigBGPNeighborAF } from './ConfigBGPNeighborAF';
import {
    ConfigBGPNeighborAFFromJSON,
    ConfigBGPNeighborAFFromJSONTyped,
    ConfigBGPNeighborAFToJSON,
    ConfigBGPNeighborAFToJSONTyped,
} from './ConfigBGPNeighborAF';

/**
 * 
 * @export
 * @interface ConfigBGPNeighbor
 */
export interface ConfigBGPNeighbor {
    /**
     * 
     * @type {string}
     * @memberof ConfigBGPNeighbor
     */
    address: string;
    /**
     * 
     * @type {{ [key: string]: ConfigBGPNeighborAF; }}
     * @memberof ConfigBGPNeighbor
     */
    address_families?: { [key: string]: ConfigBGPNeighborAF; };
    /**
     * 
     * @type {boolean}
     * @memberof ConfigBGPNeighbor
     */
    bfd?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ConfigBGPNeighbor
     */
    bfd_profile?: string;
    /**
     * 
     * @type {string}
     * @memberof ConfigBGPNeighbor
     */
    description?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ConfigBGPNeighbor
     */
    disable_connected_check?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ConfigBGPNeighbor
     */
    ebgp_multihop?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof ConfigBGPNeighbor
     */
    extra?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof ConfigBGPNeighbor
     */
    passive?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ConfigBGPNeighbor
     */
    password?: string;
    /**
     * 
     * @type {number}
     * @memberof ConfigBGPNeighbor
     */
    remote_asn: number;
    /**
     * 
     * @type {boolean}
     * @memberof ConfigBGPNeighbor
     */
    shutdown?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ConfigBGPNeighbor
     */
    update_source?: string;
}

/**
 * Check if a given object implements the ConfigBGPNeighbor interface.
 */
export function instanceOfConfigBGPNeighbor(value: object): value is ConfigBGPNeighbor {
    if (!('address' in value) || value['address'] === undefined) return false;
    if (!('remote_asn' in value) || value['remote_asn'] === undefined) return false;
    return true;
}

export function ConfigBGPNeighborFromJSON(json: any): ConfigBGPNeighbor {
    return ConfigBGPNeighborFromJSONTyped(json, false);
}

export function ConfigBGPNeighborFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigBGPNeighbor {
    if (json == null) {
        return json;
    }
    return {
        
        'address': json['address'],
        'address_families': json['address_families'] == null ? undefined : (mapValues(json['address_families'], ConfigBGPNeighborAFFromJSON)),
        'bfd': json['bfd'] == null ? undefined : json['bfd'],
        'bfd_profile': json['bfd_profile'] == null ? undefined : json['bfd_profile'],
        'description': json['description'] == null ? undefined : json['description'],
        'disable_connected_check': json['disable_connected_check'] == null ? undefined : json['disable_connected_check'],
        'ebgp_multihop': json['ebgp_multihop'] == null ? undefined : json['ebgp_multihop'],
        'extra': json['extra'] == null ? undefined : json['extra'],
        'passive': json['passive'] == null ? undefined : json['passive'],
        'password': json['password'] == null ? undefined : json['password'],
        'remote_asn': json['remote_asn'],
        'shutdown': json['shutdown'] == null ? undefined : json['shutdown'],
        'update_source': json['update_source'] == null ? undefined : json['update_source'],
    };
}

export function ConfigBGPNeighborToJSON(json: any): ConfigBGPNeighbor {
    return ConfigBGPNeighborToJSONTyped(json, false);
}

export function ConfigBGPNeighborToJSONTyped(value?: ConfigBGPNeighbor | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'address': value['address'],
        'address_families': value['address_families'] == null ? undefined : (mapValues(value['address_families'], ConfigBGPNeighborAFToJSON)),
        'bfd': value['bfd'],
        'bfd_profile': value['bfd_profile'],
        'description': value['description'],
        'disable_connected_check': value['disable_connected_check'],
        'ebgp_multihop': value['ebgp_multihop'],
        'extra': value['extra'],
        'passive': value['passive'],
        'password': value['password'],
        'remote_asn': value['remote_asn'],
        'shutdown': value['shutdown'],
        'update_source': value['update_source'],
    };
}

