/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConfigRuleMatch } from './ConfigRuleMatch';
import {
    ConfigRuleMatchFromJSON,
    ConfigRuleMatchFromJSONTyped,
    ConfigRuleMatchToJSON,
    ConfigRuleMatchToJSONTyped,
} from './ConfigRuleMatch';

/**
 * 
 * @export
 * @interface ConfigManagedRule
 */
export interface ConfigManagedRule {
    /**
     * 
     * @type {string}
     * @memberof ConfigManagedRule
     */
    action: string;
    /**
     * 
     * @type {string}
     * @memberof ConfigManagedRule
     */
    action_to?: string;
    /**
     * 
     * @type {string}
     * @memberof ConfigManagedRule
     */
    comment?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ConfigManagedRule
     */
    disabled?: boolean;
    /**
     * 
     * @type {ConfigRuleMatch}
     * @memberof ConfigManagedRule
     */
    match?: ConfigRuleMatch;
    /**
     * 
     * @type {string}
     * @memberof ConfigManagedRule
     */
    tag?: string;
}

/**
 * Check if a given object implements the ConfigManagedRule interface.
 */
export function instanceOfConfigManagedRule(value: object): value is ConfigManagedRule {
    if (!('action' in value) || value['action'] === undefined) return false;
    return true;
}

export function ConfigManagedRuleFromJSON(json: any): ConfigManagedRule {
    return ConfigManagedRuleFromJSONTyped(json, false);
}

export function ConfigManagedRuleFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigManagedRule {
    if (json == null) {
        return json;
    }
    return {
        
        'action': json['action'],
        'action_to': json['action_to'] == null ? undefined : json['action_to'],
        'comment': json['comment'] == null ? undefined : json['comment'],
        'disabled': json['disabled'] == null ? undefined : json['disabled'],
        'match': json['match'] == null ? undefined : ConfigRuleMatchFromJSON(json['match']),
        'tag': json['tag'] == null ? undefined : json['tag'],
    };
}

export function ConfigManagedRuleToJSON(json: any): ConfigManagedRule {
    return ConfigManagedRuleToJSONTyped(json, false);
}

export function ConfigManagedRuleToJSONTyped(value?: ConfigManagedRule | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'action': value['action'],
        'action_to': value['action_to'],
        'comment': value['comment'],
        'disabled': value['disabled'],
        'match': ConfigRuleMatchToJSON(value['match']),
        'tag': value['tag'],
    };
}

