/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConfigRADVDInterface } from './ConfigRADVDInterface';
import {
    ConfigRADVDInterfaceFromJSON,
    ConfigRADVDInterfaceFromJSONTyped,
    ConfigRADVDInterfaceToJSON,
    ConfigRADVDInterfaceToJSONTyped,
} from './ConfigRADVDInterface';

/**
 * 
 * @export
 * @interface ConfigRADVDConfig
 */
export interface ConfigRADVDConfig {
    /**
     * 
     * @type {{ [key: string]: ConfigRADVDInterface; }}
     * @memberof ConfigRADVDConfig
     */
    interfaces?: { [key: string]: ConfigRADVDInterface; };
}

/**
 * Check if a given object implements the ConfigRADVDConfig interface.
 */
export function instanceOfConfigRADVDConfig(value: object): value is ConfigRADVDConfig {
    return true;
}

export function ConfigRADVDConfigFromJSON(json: any): ConfigRADVDConfig {
    return ConfigRADVDConfigFromJSONTyped(json, false);
}

export function ConfigRADVDConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigRADVDConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'interfaces': json['interfaces'] == null ? undefined : (mapValues(json['interfaces'], ConfigRADVDInterfaceFromJSON)),
    };
}

export function ConfigRADVDConfigToJSON(json: any): ConfigRADVDConfig {
    return ConfigRADVDConfigToJSONTyped(json, false);
}

export function ConfigRADVDConfigToJSONTyped(value?: ConfigRADVDConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'interfaces': value['interfaces'] == null ? undefined : (mapValues(value['interfaces'], ConfigRADVDInterfaceToJSON)),
    };
}

