/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfigUser
 */
export interface ConfigUser {
    /**
     * 
     * @type {Array<string>}
     * @memberof ConfigUser
     */
    groups?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ConfigUser
     */
    home?: string;
    /**
     * 
     * @type {string}
     * @memberof ConfigUser
     */
    password_hash?: string;
    /**
     * 
     * @type {string}
     * @memberof ConfigUser
     */
    shell?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ConfigUser
     */
    ssh_keys?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof ConfigUser
     */
    system?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ConfigUser
     */
    uid?: number;
}

/**
 * Check if a given object implements the ConfigUser interface.
 */
export function instanceOfConfigUser(value: object): value is ConfigUser {
    return true;
}

export function ConfigUserFromJSON(json: any): ConfigUser {
    return ConfigUserFromJSONTyped(json, false);
}

export function ConfigUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigUser {
    if (json == null) {
        return json;
    }
    return {
        
        'groups': json['groups'] == null ? undefined : json['groups'],
        'home': json['home'] == null ? undefined : json['home'],
        'password_hash': json['password_hash'] == null ? undefined : json['password_hash'],
        'shell': json['shell'] == null ? undefined : json['shell'],
        'ssh_keys': json['ssh_keys'] == null ? undefined : json['ssh_keys'],
        'system': json['system'] == null ? undefined : json['system'],
        'uid': json['uid'] == null ? undefined : json['uid'],
    };
}

export function ConfigUserToJSON(json: any): ConfigUser {
    return ConfigUserToJSONTyped(json, false);
}

export function ConfigUserToJSONTyped(value?: ConfigUser | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'groups': value['groups'],
        'home': value['home'],
        'password_hash': value['password_hash'],
        'shell': value['shell'],
        'ssh_keys': value['ssh_keys'],
        'system': value['system'],
        'uid': value['uid'],
    };
}

