/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConfigAnycastService } from './ConfigAnycastService';
import {
    ConfigAnycastServiceFromJSON,
    ConfigAnycastServiceFromJSONTyped,
    ConfigAnycastServiceToJSON,
    ConfigAnycastServiceToJSONTyped,
} from './ConfigAnycastService';

/**
 * 
 * @export
 * @interface ConfigAnycastConfig
 */
export interface ConfigAnycastConfig {
    /**
     * 
     * @type {Array<ConfigAnycastService>}
     * @memberof ConfigAnycastConfig
     */
    services?: Array<ConfigAnycastService>;
}

/**
 * Check if a given object implements the ConfigAnycastConfig interface.
 */
export function instanceOfConfigAnycastConfig(value: object): value is ConfigAnycastConfig {
    return true;
}

export function ConfigAnycastConfigFromJSON(json: any): ConfigAnycastConfig {
    return ConfigAnycastConfigFromJSONTyped(json, false);
}

export function ConfigAnycastConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigAnycastConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'services': json['services'] == null ? undefined : ((json['services'] as Array<any>).map(ConfigAnycastServiceFromJSON)),
    };
}

export function ConfigAnycastConfigToJSON(json: any): ConfigAnycastConfig {
    return ConfigAnycastConfigToJSONTyped(json, false);
}

export function ConfigAnycastConfigToJSONTyped(value?: ConfigAnycastConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'services': value['services'] == null ? undefined : ((value['services'] as Array<any>).map(ConfigAnycastServiceToJSON)),
    };
}

