/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfigRuleMatch
 */
export interface ConfigRuleMatch {
    /**
     * 
     * @type {string}
     * @memberof ConfigRuleMatch
     */
    addr_family?: string;
    /**
     * 
     * @type {string}
     * @memberof ConfigRuleMatch
     */
    ct_state?: string;
    /**
     * 
     * @type {string}
     * @memberof ConfigRuleMatch
     */
    daddr?: string;
    /**
     * 
     * @type {string}
     * @memberof ConfigRuleMatch
     */
    dport?: string;
    /**
     * 
     * @type {string}
     * @memberof ConfigRuleMatch
     */
    iif?: string;
    /**
     * 
     * @type {string}
     * @memberof ConfigRuleMatch
     */
    oif?: string;
    /**
     * 
     * @type {string}
     * @memberof ConfigRuleMatch
     */
    protocol?: string;
    /**
     * 
     * @type {string}
     * @memberof ConfigRuleMatch
     */
    saddr?: string;
    /**
     * 
     * @type {string}
     * @memberof ConfigRuleMatch
     */
    sport?: string;
}

/**
 * Check if a given object implements the ConfigRuleMatch interface.
 */
export function instanceOfConfigRuleMatch(value: object): value is ConfigRuleMatch {
    return true;
}

export function ConfigRuleMatchFromJSON(json: any): ConfigRuleMatch {
    return ConfigRuleMatchFromJSONTyped(json, false);
}

export function ConfigRuleMatchFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigRuleMatch {
    if (json == null) {
        return json;
    }
    return {
        
        'addr_family': json['addr_family'] == null ? undefined : json['addr_family'],
        'ct_state': json['ct_state'] == null ? undefined : json['ct_state'],
        'daddr': json['daddr'] == null ? undefined : json['daddr'],
        'dport': json['dport'] == null ? undefined : json['dport'],
        'iif': json['iif'] == null ? undefined : json['iif'],
        'oif': json['oif'] == null ? undefined : json['oif'],
        'protocol': json['protocol'] == null ? undefined : json['protocol'],
        'saddr': json['saddr'] == null ? undefined : json['saddr'],
        'sport': json['sport'] == null ? undefined : json['sport'],
    };
}

export function ConfigRuleMatchToJSON(json: any): ConfigRuleMatch {
    return ConfigRuleMatchToJSONTyped(json, false);
}

export function ConfigRuleMatchToJSONTyped(value?: ConfigRuleMatch | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'addr_family': value['addr_family'],
        'ct_state': value['ct_state'],
        'daddr': value['daddr'],
        'dport': value['dport'],
        'iif': value['iif'],
        'oif': value['oif'],
        'protocol': value['protocol'],
        'saddr': value['saddr'],
        'sport': value['sport'],
    };
}

