/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConfigRADVDRDNSS } from './ConfigRADVDRDNSS';
import {
    ConfigRADVDRDNSSFromJSON,
    ConfigRADVDRDNSSFromJSONTyped,
    ConfigRADVDRDNSSToJSON,
    ConfigRADVDRDNSSToJSONTyped,
} from './ConfigRADVDRDNSS';
import type { ConfigRADVDRoute } from './ConfigRADVDRoute';
import {
    ConfigRADVDRouteFromJSON,
    ConfigRADVDRouteFromJSONTyped,
    ConfigRADVDRouteToJSON,
    ConfigRADVDRouteToJSONTyped,
} from './ConfigRADVDRoute';
import type { ConfigRADVDPrefix } from './ConfigRADVDPrefix';
import {
    ConfigRADVDPrefixFromJSON,
    ConfigRADVDPrefixFromJSONTyped,
    ConfigRADVDPrefixToJSON,
    ConfigRADVDPrefixToJSONTyped,
} from './ConfigRADVDPrefix';

/**
 * 
 * @export
 * @interface ConfigRADVDInterface
 */
export interface ConfigRADVDInterface {
    /**
     * 
     * @type {number}
     * @memberof ConfigRADVDInterface
     */
    adv_default_lifetime?: number;
    /**
     * 
     * @type {string}
     * @memberof ConfigRADVDInterface
     */
    adv_default_preference?: string;
    /**
     * 
     * @type {number}
     * @memberof ConfigRADVDInterface
     */
    adv_link_mtu?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ConfigRADVDInterface
     */
    adv_managed_flag?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ConfigRADVDInterface
     */
    adv_other_config_flag?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ConfigRADVDInterface
     */
    adv_send_advert?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ConfigRADVDInterface
     */
    max_rtr_adv_interval?: number;
    /**
     * 
     * @type {number}
     * @memberof ConfigRADVDInterface
     */
    min_rtr_adv_interval?: number;
    /**
     * 
     * @type {Array<ConfigRADVDPrefix>}
     * @memberof ConfigRADVDInterface
     */
    prefixes?: Array<ConfigRADVDPrefix>;
    /**
     * 
     * @type {ConfigRADVDRDNSS}
     * @memberof ConfigRADVDInterface
     */
    rdnss?: ConfigRADVDRDNSS;
    /**
     * 
     * @type {Array<ConfigRADVDRoute>}
     * @memberof ConfigRADVDInterface
     */
    routes?: Array<ConfigRADVDRoute>;
}

/**
 * Check if a given object implements the ConfigRADVDInterface interface.
 */
export function instanceOfConfigRADVDInterface(value: object): value is ConfigRADVDInterface {
    return true;
}

export function ConfigRADVDInterfaceFromJSON(json: any): ConfigRADVDInterface {
    return ConfigRADVDInterfaceFromJSONTyped(json, false);
}

export function ConfigRADVDInterfaceFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigRADVDInterface {
    if (json == null) {
        return json;
    }
    return {
        
        'adv_default_lifetime': json['adv_default_lifetime'] == null ? undefined : json['adv_default_lifetime'],
        'adv_default_preference': json['adv_default_preference'] == null ? undefined : json['adv_default_preference'],
        'adv_link_mtu': json['adv_link_mtu'] == null ? undefined : json['adv_link_mtu'],
        'adv_managed_flag': json['adv_managed_flag'] == null ? undefined : json['adv_managed_flag'],
        'adv_other_config_flag': json['adv_other_config_flag'] == null ? undefined : json['adv_other_config_flag'],
        'adv_send_advert': json['adv_send_advert'] == null ? undefined : json['adv_send_advert'],
        'max_rtr_adv_interval': json['max_rtr_adv_interval'] == null ? undefined : json['max_rtr_adv_interval'],
        'min_rtr_adv_interval': json['min_rtr_adv_interval'] == null ? undefined : json['min_rtr_adv_interval'],
        'prefixes': json['prefixes'] == null ? undefined : ((json['prefixes'] as Array<any>).map(ConfigRADVDPrefixFromJSON)),
        'rdnss': json['rdnss'] == null ? undefined : ConfigRADVDRDNSSFromJSON(json['rdnss']),
        'routes': json['routes'] == null ? undefined : ((json['routes'] as Array<any>).map(ConfigRADVDRouteFromJSON)),
    };
}

export function ConfigRADVDInterfaceToJSON(json: any): ConfigRADVDInterface {
    return ConfigRADVDInterfaceToJSONTyped(json, false);
}

export function ConfigRADVDInterfaceToJSONTyped(value?: ConfigRADVDInterface | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'adv_default_lifetime': value['adv_default_lifetime'],
        'adv_default_preference': value['adv_default_preference'],
        'adv_link_mtu': value['adv_link_mtu'],
        'adv_managed_flag': value['adv_managed_flag'],
        'adv_other_config_flag': value['adv_other_config_flag'],
        'adv_send_advert': value['adv_send_advert'],
        'max_rtr_adv_interval': value['max_rtr_adv_interval'],
        'min_rtr_adv_interval': value['min_rtr_adv_interval'],
        'prefixes': value['prefixes'] == null ? undefined : ((value['prefixes'] as Array<any>).map(ConfigRADVDPrefixToJSON)),
        'rdnss': ConfigRADVDRDNSSToJSON(value['rdnss']),
        'routes': value['routes'] == null ? undefined : ((value['routes'] as Array<any>).map(ConfigRADVDRouteToJSON)),
    };
}

