/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfigRADVDPrefix
 */
export interface ConfigRADVDPrefix {
    /**
     * 
     * @type {boolean}
     * @memberof ConfigRADVDPrefix
     */
    adv_autonomous?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ConfigRADVDPrefix
     */
    adv_on_link?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ConfigRADVDPrefix
     */
    adv_preferred_lifetime?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ConfigRADVDPrefix
     */
    adv_router_addr?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ConfigRADVDPrefix
     */
    adv_valid_lifetime?: string;
    /**
     * 
     * @type {string}
     * @memberof ConfigRADVDPrefix
     */
    prefix: string;
}

/**
 * Check if a given object implements the ConfigRADVDPrefix interface.
 */
export function instanceOfConfigRADVDPrefix(value: object): value is ConfigRADVDPrefix {
    if (!('prefix' in value) || value['prefix'] === undefined) return false;
    return true;
}

export function ConfigRADVDPrefixFromJSON(json: any): ConfigRADVDPrefix {
    return ConfigRADVDPrefixFromJSONTyped(json, false);
}

export function ConfigRADVDPrefixFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigRADVDPrefix {
    if (json == null) {
        return json;
    }
    return {
        
        'adv_autonomous': json['adv_autonomous'] == null ? undefined : json['adv_autonomous'],
        'adv_on_link': json['adv_on_link'] == null ? undefined : json['adv_on_link'],
        'adv_preferred_lifetime': json['adv_preferred_lifetime'] == null ? undefined : json['adv_preferred_lifetime'],
        'adv_router_addr': json['adv_router_addr'] == null ? undefined : json['adv_router_addr'],
        'adv_valid_lifetime': json['adv_valid_lifetime'] == null ? undefined : json['adv_valid_lifetime'],
        'prefix': json['prefix'],
    };
}

export function ConfigRADVDPrefixToJSON(json: any): ConfigRADVDPrefix {
    return ConfigRADVDPrefixToJSONTyped(json, false);
}

export function ConfigRADVDPrefixToJSONTyped(value?: ConfigRADVDPrefix | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'adv_autonomous': value['adv_autonomous'],
        'adv_on_link': value['adv_on_link'],
        'adv_preferred_lifetime': value['adv_preferred_lifetime'],
        'adv_router_addr': value['adv_router_addr'],
        'adv_valid_lifetime': value['adv_valid_lifetime'],
        'prefix': value['prefix'],
    };
}

