/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfigPBRMapEntry
 */
export interface ConfigPBRMapEntry {
    /**
     * 
     * @type {string}
     * @memberof ConfigPBRMapEntry
     */
    match_dst?: string;
    /**
     * 
     * @type {string}
     * @memberof ConfigPBRMapEntry
     */
    match_src?: string;
    /**
     * 
     * @type {number}
     * @memberof ConfigPBRMapEntry
     */
    seq: number;
    /**
     * 
     * @type {string}
     * @memberof ConfigPBRMapEntry
     */
    set_nexthop?: string;
    /**
     * 
     * @type {string}
     * @memberof ConfigPBRMapEntry
     */
    set_nexthop_group?: string;
}

/**
 * Check if a given object implements the ConfigPBRMapEntry interface.
 */
export function instanceOfConfigPBRMapEntry(value: object): value is ConfigPBRMapEntry {
    if (!('seq' in value) || value['seq'] === undefined) return false;
    return true;
}

export function ConfigPBRMapEntryFromJSON(json: any): ConfigPBRMapEntry {
    return ConfigPBRMapEntryFromJSONTyped(json, false);
}

export function ConfigPBRMapEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigPBRMapEntry {
    if (json == null) {
        return json;
    }
    return {
        
        'match_dst': json['match_dst'] == null ? undefined : json['match_dst'],
        'match_src': json['match_src'] == null ? undefined : json['match_src'],
        'seq': json['seq'],
        'set_nexthop': json['set_nexthop'] == null ? undefined : json['set_nexthop'],
        'set_nexthop_group': json['set_nexthop_group'] == null ? undefined : json['set_nexthop_group'],
    };
}

export function ConfigPBRMapEntryToJSON(json: any): ConfigPBRMapEntry {
    return ConfigPBRMapEntryToJSONTyped(json, false);
}

export function ConfigPBRMapEntryToJSONTyped(value?: ConfigPBRMapEntry | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'match_dst': value['match_dst'],
        'match_src': value['match_src'],
        'seq': value['seq'],
        'set_nexthop': value['set_nexthop'],
        'set_nexthop_group': value['set_nexthop_group'],
    };
}

