/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConfigDNSZone } from './ConfigDNSZone';
import {
    ConfigDNSZoneFromJSON,
    ConfigDNSZoneFromJSONTyped,
    ConfigDNSZoneToJSON,
    ConfigDNSZoneToJSONTyped,
} from './ConfigDNSZone';
import type { ConfigDNSView } from './ConfigDNSView';
import {
    ConfigDNSViewFromJSON,
    ConfigDNSViewFromJSONTyped,
    ConfigDNSViewToJSON,
    ConfigDNSViewToJSONTyped,
} from './ConfigDNSView';
import type { ConfigDNSForward } from './ConfigDNSForward';
import {
    ConfigDNSForwardFromJSON,
    ConfigDNSForwardFromJSONTyped,
    ConfigDNSForwardToJSON,
    ConfigDNSForwardToJSONTyped,
} from './ConfigDNSForward';
import type { ConfigDNSCache } from './ConfigDNSCache';
import {
    ConfigDNSCacheFromJSON,
    ConfigDNSCacheFromJSONTyped,
    ConfigDNSCacheToJSON,
    ConfigDNSCacheToJSONTyped,
} from './ConfigDNSCache';

/**
 * 
 * @export
 * @interface ConfigDNSServer
 */
export interface ConfigDNSServer {
    /**
     * 
     * @type {Array<string>}
     * @memberof ConfigDNSServer
     */
    allow_from?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ConfigDNSServer
     */
    allow_inbound?: Array<string>;
    /**
     * 
     * @type {ConfigDNSCache}
     * @memberof ConfigDNSServer
     */
    cache?: ConfigDNSCache;
    /**
     * 
     * @type {boolean}
     * @memberof ConfigDNSServer
     */
    dnssec?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ConfigDNSServer
     */
    enabled?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof ConfigDNSServer
     */
    extra?: Array<string>;
    /**
     * 
     * @type {Array<ConfigDNSForward>}
     * @memberof ConfigDNSServer
     */
    forward?: Array<ConfigDNSForward>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ConfigDNSServer
     */
    listen?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof ConfigDNSServer
     */
    log_queries?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ConfigDNSServer
     */
    mode?: string;
    /**
     * 
     * @type {number}
     * @memberof ConfigDNSServer
     */
    port?: number;
    /**
     * 
     * @type {number}
     * @memberof ConfigDNSServer
     */
    threads?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof ConfigDNSServer
     */
    upstreams?: Array<string>;
    /**
     * 
     * @type {Array<ConfigDNSView>}
     * @memberof ConfigDNSServer
     */
    views?: Array<ConfigDNSView>;
    /**
     * 
     * @type {Array<ConfigDNSZone>}
     * @memberof ConfigDNSServer
     */
    zones?: Array<ConfigDNSZone>;
}

/**
 * Check if a given object implements the ConfigDNSServer interface.
 */
export function instanceOfConfigDNSServer(value: object): value is ConfigDNSServer {
    return true;
}

export function ConfigDNSServerFromJSON(json: any): ConfigDNSServer {
    return ConfigDNSServerFromJSONTyped(json, false);
}

export function ConfigDNSServerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigDNSServer {
    if (json == null) {
        return json;
    }
    return {
        
        'allow_from': json['allow_from'] == null ? undefined : json['allow_from'],
        'allow_inbound': json['allow_inbound'] == null ? undefined : json['allow_inbound'],
        'cache': json['cache'] == null ? undefined : ConfigDNSCacheFromJSON(json['cache']),
        'dnssec': json['dnssec'] == null ? undefined : json['dnssec'],
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'extra': json['extra'] == null ? undefined : json['extra'],
        'forward': json['forward'] == null ? undefined : ((json['forward'] as Array<any>).map(ConfigDNSForwardFromJSON)),
        'listen': json['listen'] == null ? undefined : json['listen'],
        'log_queries': json['log_queries'] == null ? undefined : json['log_queries'],
        'mode': json['mode'] == null ? undefined : json['mode'],
        'port': json['port'] == null ? undefined : json['port'],
        'threads': json['threads'] == null ? undefined : json['threads'],
        'upstreams': json['upstreams'] == null ? undefined : json['upstreams'],
        'views': json['views'] == null ? undefined : ((json['views'] as Array<any>).map(ConfigDNSViewFromJSON)),
        'zones': json['zones'] == null ? undefined : ((json['zones'] as Array<any>).map(ConfigDNSZoneFromJSON)),
    };
}

export function ConfigDNSServerToJSON(json: any): ConfigDNSServer {
    return ConfigDNSServerToJSONTyped(json, false);
}

export function ConfigDNSServerToJSONTyped(value?: ConfigDNSServer | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'allow_from': value['allow_from'],
        'allow_inbound': value['allow_inbound'],
        'cache': ConfigDNSCacheToJSON(value['cache']),
        'dnssec': value['dnssec'],
        'enabled': value['enabled'],
        'extra': value['extra'],
        'forward': value['forward'] == null ? undefined : ((value['forward'] as Array<any>).map(ConfigDNSForwardToJSON)),
        'listen': value['listen'],
        'log_queries': value['log_queries'],
        'mode': value['mode'],
        'port': value['port'],
        'threads': value['threads'],
        'upstreams': value['upstreams'],
        'views': value['views'] == null ? undefined : ((value['views'] as Array<any>).map(ConfigDNSViewToJSON)),
        'zones': value['zones'] == null ? undefined : ((value['zones'] as Array<any>).map(ConfigDNSZoneToJSON)),
    };
}

