/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConfigWGPeer } from './ConfigWGPeer';
import {
    ConfigWGPeerFromJSON,
    ConfigWGPeerFromJSONTyped,
    ConfigWGPeerToJSON,
    ConfigWGPeerToJSONTyped,
} from './ConfigWGPeer';

/**
 * 
 * @export
 * @interface ConfigWireguard
 */
export interface ConfigWireguard {
    /**
     * 
     * @type {Array<string>}
     * @memberof ConfigWireguard
     */
    addresses?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof ConfigWireguard
     */
    allow_inbound?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ConfigWireguard
     */
    friend?: string;
    /**
     * 
     * @type {number}
     * @memberof ConfigWireguard
     */
    listen_port?: number;
    /**
     * 
     * @type {number}
     * @memberof ConfigWireguard
     */
    mtu?: number;
    /**
     * 
     * @type {Array<ConfigWGPeer>}
     * @memberof ConfigWireguard
     */
    peers?: Array<ConfigWGPeer>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ConfigWireguard
     */
    post_down?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ConfigWireguard
     */
    post_up?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ConfigWireguard
     */
    pre_down?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ConfigWireguard
     */
    pre_up?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ConfigWireguard
     */
    private_key?: string;
    /**
     * 
     * @type {string}
     * @memberof ConfigWireguard
     */
    private_key_file?: string;
    /**
     * 
     * @type {string}
     * @memberof ConfigWireguard
     */
    table?: string;
}

/**
 * Check if a given object implements the ConfigWireguard interface.
 */
export function instanceOfConfigWireguard(value: object): value is ConfigWireguard {
    return true;
}

export function ConfigWireguardFromJSON(json: any): ConfigWireguard {
    return ConfigWireguardFromJSONTyped(json, false);
}

export function ConfigWireguardFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigWireguard {
    if (json == null) {
        return json;
    }
    return {
        
        'addresses': json['addresses'] == null ? undefined : json['addresses'],
        'allow_inbound': json['allow_inbound'] == null ? undefined : json['allow_inbound'],
        'friend': json['friend'] == null ? undefined : json['friend'],
        'listen_port': json['listen_port'] == null ? undefined : json['listen_port'],
        'mtu': json['mtu'] == null ? undefined : json['mtu'],
        'peers': json['peers'] == null ? undefined : ((json['peers'] as Array<any>).map(ConfigWGPeerFromJSON)),
        'post_down': json['post_down'] == null ? undefined : json['post_down'],
        'post_up': json['post_up'] == null ? undefined : json['post_up'],
        'pre_down': json['pre_down'] == null ? undefined : json['pre_down'],
        'pre_up': json['pre_up'] == null ? undefined : json['pre_up'],
        'private_key': json['private_key'] == null ? undefined : json['private_key'],
        'private_key_file': json['private_key_file'] == null ? undefined : json['private_key_file'],
        'table': json['table'] == null ? undefined : json['table'],
    };
}

export function ConfigWireguardToJSON(json: any): ConfigWireguard {
    return ConfigWireguardToJSONTyped(json, false);
}

export function ConfigWireguardToJSONTyped(value?: ConfigWireguard | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'addresses': value['addresses'],
        'allow_inbound': value['allow_inbound'],
        'friend': value['friend'],
        'listen_port': value['listen_port'],
        'mtu': value['mtu'],
        'peers': value['peers'] == null ? undefined : ((value['peers'] as Array<any>).map(ConfigWGPeerToJSON)),
        'post_down': value['post_down'],
        'post_up': value['post_up'],
        'pre_down': value['pre_down'],
        'pre_up': value['pre_up'],
        'private_key': value['private_key'],
        'private_key_file': value['private_key_file'],
        'table': value['table'],
    };
}

