/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfigBond
 */
export interface ConfigBond {
    /**
     * 
     * @type {number}
     * @memberof ConfigBond
     */
    downdelay?: number;
    /**
     * 
     * @type {string}
     * @memberof ConfigBond
     */
    lacp_rate?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ConfigBond
     */
    members?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof ConfigBond
     */
    miimon?: number;
    /**
     * 
     * @type {number}
     * @memberof ConfigBond
     */
    min_links?: number;
    /**
     * 
     * @type {string}
     * @memberof ConfigBond
     */
    mode?: string;
    /**
     * 
     * @type {string}
     * @memberof ConfigBond
     */
    primary?: string;
    /**
     * 
     * @type {number}
     * @memberof ConfigBond
     */
    updelay?: number;
    /**
     * 
     * @type {string}
     * @memberof ConfigBond
     */
    xmit_hash_policy?: string;
}

/**
 * Check if a given object implements the ConfigBond interface.
 */
export function instanceOfConfigBond(value: object): value is ConfigBond {
    return true;
}

export function ConfigBondFromJSON(json: any): ConfigBond {
    return ConfigBondFromJSONTyped(json, false);
}

export function ConfigBondFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigBond {
    if (json == null) {
        return json;
    }
    return {
        
        'downdelay': json['downdelay'] == null ? undefined : json['downdelay'],
        'lacp_rate': json['lacp_rate'] == null ? undefined : json['lacp_rate'],
        'members': json['members'] == null ? undefined : json['members'],
        'miimon': json['miimon'] == null ? undefined : json['miimon'],
        'min_links': json['min_links'] == null ? undefined : json['min_links'],
        'mode': json['mode'] == null ? undefined : json['mode'],
        'primary': json['primary'] == null ? undefined : json['primary'],
        'updelay': json['updelay'] == null ? undefined : json['updelay'],
        'xmit_hash_policy': json['xmit_hash_policy'] == null ? undefined : json['xmit_hash_policy'],
    };
}

export function ConfigBondToJSON(json: any): ConfigBond {
    return ConfigBondToJSONTyped(json, false);
}

export function ConfigBondToJSONTyped(value?: ConfigBond | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'downdelay': value['downdelay'],
        'lacp_rate': value['lacp_rate'],
        'members': value['members'],
        'miimon': value['miimon'],
        'min_links': value['min_links'],
        'mode': value['mode'],
        'primary': value['primary'],
        'updelay': value['updelay'],
        'xmit_hash_policy': value['xmit_hash_policy'],
    };
}

