/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfigPBRNexthop
 */
export interface ConfigPBRNexthop {
    /**
     * 
     * @type {string}
     * @memberof ConfigPBRNexthop
     */
    address?: string;
    /**
     * 
     * @type {string}
     * @memberof ConfigPBRNexthop
     */
    dev?: string;
    /**
     * 
     * @type {string}
     * @memberof ConfigPBRNexthop
     */
    nexthop_vrf?: string;
}

/**
 * Check if a given object implements the ConfigPBRNexthop interface.
 */
export function instanceOfConfigPBRNexthop(value: object): value is ConfigPBRNexthop {
    return true;
}

export function ConfigPBRNexthopFromJSON(json: any): ConfigPBRNexthop {
    return ConfigPBRNexthopFromJSONTyped(json, false);
}

export function ConfigPBRNexthopFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigPBRNexthop {
    if (json == null) {
        return json;
    }
    return {
        
        'address': json['address'] == null ? undefined : json['address'],
        'dev': json['dev'] == null ? undefined : json['dev'],
        'nexthop_vrf': json['nexthop_vrf'] == null ? undefined : json['nexthop_vrf'],
    };
}

export function ConfigPBRNexthopToJSON(json: any): ConfigPBRNexthop {
    return ConfigPBRNexthopToJSONTyped(json, false);
}

export function ConfigPBRNexthopToJSONTyped(value?: ConfigPBRNexthop | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'address': value['address'],
        'dev': value['dev'],
        'nexthop_vrf': value['nexthop_vrf'],
    };
}

