/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConfigBridge } from './ConfigBridge';
import {
    ConfigBridgeFromJSON,
    ConfigBridgeFromJSONTyped,
    ConfigBridgeToJSON,
    ConfigBridgeToJSONTyped,
} from './ConfigBridge';
import type { ConfigVRRPInstance } from './ConfigVRRPInstance';
import {
    ConfigVRRPInstanceFromJSON,
    ConfigVRRPInstanceFromJSONTyped,
    ConfigVRRPInstanceToJSON,
    ConfigVRRPInstanceToJSONTyped,
} from './ConfigVRRPInstance';
import type { ConfigVLAN } from './ConfigVLAN';
import {
    ConfigVLANFromJSON,
    ConfigVLANFromJSONTyped,
    ConfigVLANToJSON,
    ConfigVLANToJSONTyped,
} from './ConfigVLAN';

/**
 * 
 * @export
 * @interface ConfigInterface
 */
export interface ConfigInterface {
    /**
     * 
     * @type {Array<string>}
     * @memberof ConfigInterface
     */
    addresses?: Array<string>;
    /**
     * 
     * @type {ConfigBridge}
     * @memberof ConfigInterface
     */
    bridge?: ConfigBridge;
    /**
     * 
     * @type {Array<string>}
     * @memberof ConfigInterface
     */
    dhcp_options?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof ConfigInterface
     */
    mtu?: number;
    /**
     * 
     * @type {string}
     * @memberof ConfigInterface
     */
    select: string;
    /**
     * 
     * @type {string}
     * @memberof ConfigInterface
     */
    type?: string;
    /**
     * 
     * @type {{ [key: string]: ConfigVLAN; }}
     * @memberof ConfigInterface
     */
    vlans?: { [key: string]: ConfigVLAN; };
    /**
     * 
     * @type {string}
     * @memberof ConfigInterface
     */
    vrf?: string;
    /**
     * 
     * @type {Array<ConfigVRRPInstance>}
     * @memberof ConfigInterface
     */
    vrrp?: Array<ConfigVRRPInstance>;
}

/**
 * Check if a given object implements the ConfigInterface interface.
 */
export function instanceOfConfigInterface(value: object): value is ConfigInterface {
    if (!('select' in value) || value['select'] === undefined) return false;
    return true;
}

export function ConfigInterfaceFromJSON(json: any): ConfigInterface {
    return ConfigInterfaceFromJSONTyped(json, false);
}

export function ConfigInterfaceFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigInterface {
    if (json == null) {
        return json;
    }
    return {
        
        'addresses': json['addresses'] == null ? undefined : json['addresses'],
        'bridge': json['bridge'] == null ? undefined : ConfigBridgeFromJSON(json['bridge']),
        'dhcp_options': json['dhcp_options'] == null ? undefined : json['dhcp_options'],
        'mtu': json['mtu'] == null ? undefined : json['mtu'],
        'select': json['select'],
        'type': json['type'] == null ? undefined : json['type'],
        'vlans': json['vlans'] == null ? undefined : (mapValues(json['vlans'], ConfigVLANFromJSON)),
        'vrf': json['vrf'] == null ? undefined : json['vrf'],
        'vrrp': json['vrrp'] == null ? undefined : ((json['vrrp'] as Array<any>).map(ConfigVRRPInstanceFromJSON)),
    };
}

export function ConfigInterfaceToJSON(json: any): ConfigInterface {
    return ConfigInterfaceToJSONTyped(json, false);
}

export function ConfigInterfaceToJSONTyped(value?: ConfigInterface | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'addresses': value['addresses'],
        'bridge': ConfigBridgeToJSON(value['bridge']),
        'dhcp_options': value['dhcp_options'],
        'mtu': value['mtu'],
        'select': value['select'],
        'type': value['type'],
        'vlans': value['vlans'] == null ? undefined : (mapValues(value['vlans'], ConfigVLANToJSON)),
        'vrf': value['vrf'],
        'vrrp': value['vrrp'] == null ? undefined : ((value['vrrp'] as Array<any>).map(ConfigVRRPInstanceToJSON)),
    };
}

