/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfigBGPAddressFamily
 */
export interface ConfigBGPAddressFamily {
    /**
     * 
     * @type {boolean}
     * @memberof ConfigBGPAddressFamily
     */
    default_originate?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof ConfigBGPAddressFamily
     */
    extra?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ConfigBGPAddressFamily
     */
    import_vrf?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof ConfigBGPAddressFamily
     */
    maximum_paths?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof ConfigBGPAddressFamily
     */
    networks?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ConfigBGPAddressFamily
     */
    redistribute?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ConfigBGPAddressFamily
     */
    route_map_in?: string;
    /**
     * 
     * @type {string}
     * @memberof ConfigBGPAddressFamily
     */
    route_map_out?: string;
}

/**
 * Check if a given object implements the ConfigBGPAddressFamily interface.
 */
export function instanceOfConfigBGPAddressFamily(value: object): value is ConfigBGPAddressFamily {
    return true;
}

export function ConfigBGPAddressFamilyFromJSON(json: any): ConfigBGPAddressFamily {
    return ConfigBGPAddressFamilyFromJSONTyped(json, false);
}

export function ConfigBGPAddressFamilyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigBGPAddressFamily {
    if (json == null) {
        return json;
    }
    return {
        
        'default_originate': json['default_originate'] == null ? undefined : json['default_originate'],
        'extra': json['extra'] == null ? undefined : json['extra'],
        'import_vrf': json['import_vrf'] == null ? undefined : json['import_vrf'],
        'maximum_paths': json['maximum_paths'] == null ? undefined : json['maximum_paths'],
        'networks': json['networks'] == null ? undefined : json['networks'],
        'redistribute': json['redistribute'] == null ? undefined : json['redistribute'],
        'route_map_in': json['route_map_in'] == null ? undefined : json['route_map_in'],
        'route_map_out': json['route_map_out'] == null ? undefined : json['route_map_out'],
    };
}

export function ConfigBGPAddressFamilyToJSON(json: any): ConfigBGPAddressFamily {
    return ConfigBGPAddressFamilyToJSONTyped(json, false);
}

export function ConfigBGPAddressFamilyToJSONTyped(value?: ConfigBGPAddressFamily | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'default_originate': value['default_originate'],
        'extra': value['extra'],
        'import_vrf': value['import_vrf'],
        'maximum_paths': value['maximum_paths'],
        'networks': value['networks'],
        'redistribute': value['redistribute'],
        'route_map_in': value['route_map_in'],
        'route_map_out': value['route_map_out'],
    };
}

