/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfigVRRPInstance
 */
export interface ConfigVRRPInstance {
    /**
     * 
     * @type {boolean}
     * @memberof ConfigVRRPInstance
     */
    allow_inbound?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ConfigVRRPInstance
     */
    friend?: string;
    /**
     * 
     * @type {number}
     * @memberof ConfigVRRPInstance
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof ConfigVRRPInstance
     */
    interface: string;
    /**
     * 
     * @type {string}
     * @memberof ConfigVRRPInstance
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ConfigVRRPInstance
     */
    password?: string;
    /**
     * 
     * @type {number}
     * @memberof ConfigVRRPInstance
     */
    priority?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ConfigVRRPInstance
     */
    switchover?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof ConfigVRRPInstance
     */
    track_interfaces?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ConfigVRRPInstance
     */
    transport?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ConfigVRRPInstance
     */
    vips?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ConfigVRRPInstance
     */
    virtual_routes?: Array<string>;
}

/**
 * Check if a given object implements the ConfigVRRPInstance interface.
 */
export function instanceOfConfigVRRPInstance(value: object): value is ConfigVRRPInstance {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('interface' in value) || value['interface'] === undefined) return false;
    return true;
}

export function ConfigVRRPInstanceFromJSON(json: any): ConfigVRRPInstance {
    return ConfigVRRPInstanceFromJSONTyped(json, false);
}

export function ConfigVRRPInstanceFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigVRRPInstance {
    if (json == null) {
        return json;
    }
    return {
        
        'allow_inbound': json['allow_inbound'] == null ? undefined : json['allow_inbound'],
        'friend': json['friend'] == null ? undefined : json['friend'],
        'id': json['id'],
        'interface': json['interface'],
        'name': json['name'] == null ? undefined : json['name'],
        'password': json['password'] == null ? undefined : json['password'],
        'priority': json['priority'] == null ? undefined : json['priority'],
        'switchover': json['switchover'] == null ? undefined : json['switchover'],
        'track_interfaces': json['track_interfaces'] == null ? undefined : json['track_interfaces'],
        'transport': json['transport'] == null ? undefined : json['transport'],
        'vips': json['vips'] == null ? undefined : json['vips'],
        'virtual_routes': json['virtual_routes'] == null ? undefined : json['virtual_routes'],
    };
}

export function ConfigVRRPInstanceToJSON(json: any): ConfigVRRPInstance {
    return ConfigVRRPInstanceToJSONTyped(json, false);
}

export function ConfigVRRPInstanceToJSONTyped(value?: ConfigVRRPInstance | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'allow_inbound': value['allow_inbound'],
        'friend': value['friend'],
        'id': value['id'],
        'interface': value['interface'],
        'name': value['name'],
        'password': value['password'],
        'priority': value['priority'],
        'switchover': value['switchover'],
        'track_interfaces': value['track_interfaces'],
        'transport': value['transport'],
        'vips': value['vips'],
        'virtual_routes': value['virtual_routes'],
    };
}

