/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DhcpReserveFromLeaseRequest
 */
export interface DhcpReserveFromLeaseRequest {
    /**
     * 
     * @type {string}
     * @memberof DhcpReserveFromLeaseRequest
     */
    hostname: string;
    /**
     * 
     * @type {string}
     * @memberof DhcpReserveFromLeaseRequest
     */
    ip: string;
    /**
     * 
     * @type {string}
     * @memberof DhcpReserveFromLeaseRequest
     */
    lease_ip: string;
}

/**
 * Check if a given object implements the DhcpReserveFromLeaseRequest interface.
 */
export function instanceOfDhcpReserveFromLeaseRequest(value: object): value is DhcpReserveFromLeaseRequest {
    if (!('hostname' in value) || value['hostname'] === undefined) return false;
    if (!('ip' in value) || value['ip'] === undefined) return false;
    if (!('lease_ip' in value) || value['lease_ip'] === undefined) return false;
    return true;
}

export function DhcpReserveFromLeaseRequestFromJSON(json: any): DhcpReserveFromLeaseRequest {
    return DhcpReserveFromLeaseRequestFromJSONTyped(json, false);
}

export function DhcpReserveFromLeaseRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DhcpReserveFromLeaseRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'hostname': json['hostname'],
        'ip': json['ip'],
        'lease_ip': json['lease_ip'],
    };
}

export function DhcpReserveFromLeaseRequestToJSON(json: any): DhcpReserveFromLeaseRequest {
    return DhcpReserveFromLeaseRequestToJSONTyped(json, false);
}

export function DhcpReserveFromLeaseRequestToJSONTyped(value?: DhcpReserveFromLeaseRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'hostname': value['hostname'],
        'ip': value['ip'],
        'lease_ip': value['lease_ip'],
    };
}

