/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BindOverview } from './BindOverview';
import {
    BindOverviewFromJSON,
    BindOverviewFromJSONTyped,
    BindOverviewToJSON,
    BindOverviewToJSONTyped,
} from './BindOverview';

/**
 * 
 * @export
 * @interface DnsOverviewResponse
 */
export interface DnsOverviewResponse {
    /**
     * 
     * @type {Array<string>}
     * @memberof DnsOverviewResponse
     */
    allow_from?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof DnsOverviewResponse
     */
    mode: string;
    /**
     * 
     * @type {BindOverview}
     * @memberof DnsOverviewResponse
     */
    overview?: BindOverview;
    /**
     * 
     * @type {number}
     * @memberof DnsOverviewResponse
     */
    port: number;
    /**
     * 
     * @type {boolean}
     * @memberof DnsOverviewResponse
     */
    recurses: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof DnsOverviewResponse
     */
    upstreams?: Array<string>;
}

/**
 * Check if a given object implements the DnsOverviewResponse interface.
 */
export function instanceOfDnsOverviewResponse(value: object): value is DnsOverviewResponse {
    if (!('mode' in value) || value['mode'] === undefined) return false;
    if (!('port' in value) || value['port'] === undefined) return false;
    if (!('recurses' in value) || value['recurses'] === undefined) return false;
    return true;
}

export function DnsOverviewResponseFromJSON(json: any): DnsOverviewResponse {
    return DnsOverviewResponseFromJSONTyped(json, false);
}

export function DnsOverviewResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DnsOverviewResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'allow_from': json['allow_from'] == null ? undefined : json['allow_from'],
        'mode': json['mode'],
        'overview': json['overview'] == null ? undefined : BindOverviewFromJSON(json['overview']),
        'port': json['port'],
        'recurses': json['recurses'],
        'upstreams': json['upstreams'] == null ? undefined : json['upstreams'],
    };
}

export function DnsOverviewResponseToJSON(json: any): DnsOverviewResponse {
    return DnsOverviewResponseToJSONTyped(json, false);
}

export function DnsOverviewResponseToJSONTyped(value?: DnsOverviewResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'allow_from': value['allow_from'],
        'mode': value['mode'],
        'overview': BindOverviewToJSON(value['overview']),
        'port': value['port'],
        'recurses': value['recurses'],
        'upstreams': value['upstreams'],
    };
}

