/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IpcalcRangeCIDRs
 */
export interface IpcalcRangeCIDRs {
    /**
     * 
     * @type {Array<string>}
     * @memberof IpcalcRangeCIDRs
     */
    cidrs: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof IpcalcRangeCIDRs
     */
    family: string;
}

/**
 * Check if a given object implements the IpcalcRangeCIDRs interface.
 */
export function instanceOfIpcalcRangeCIDRs(value: object): value is IpcalcRangeCIDRs {
    if (!('cidrs' in value) || value['cidrs'] === undefined) return false;
    if (!('family' in value) || value['family'] === undefined) return false;
    return true;
}

export function IpcalcRangeCIDRsFromJSON(json: any): IpcalcRangeCIDRs {
    return IpcalcRangeCIDRsFromJSONTyped(json, false);
}

export function IpcalcRangeCIDRsFromJSONTyped(json: any, ignoreDiscriminator: boolean): IpcalcRangeCIDRs {
    if (json == null) {
        return json;
    }
    return {
        
        'cidrs': json['cidrs'],
        'family': json['family'],
    };
}

export function IpcalcRangeCIDRsToJSON(json: any): IpcalcRangeCIDRs {
    return IpcalcRangeCIDRsToJSONTyped(json, false);
}

export function IpcalcRangeCIDRsToJSONTyped(value?: IpcalcRangeCIDRs | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cidrs': value['cidrs'],
        'family': value['family'],
    };
}

