/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IpcalcSubnetInfo
 */
export interface IpcalcSubnetInfo {
    /**
     * 
     * @type {string}
     * @memberof IpcalcSubnetInfo
     */
    address: string;
    /**
     * 
     * @type {string}
     * @memberof IpcalcSubnetInfo
     */
    address_bits: string;
    /**
     * 
     * @type {string}
     * @memberof IpcalcSubnetInfo
     */
    broadcast?: string;
    /**
     * 
     * @type {string}
     * @memberof IpcalcSubnetInfo
     */
    broadcast_bits?: string;
    /**
     * 
     * @type {string}
     * @memberof IpcalcSubnetInfo
     */
    _class?: string;
    /**
     * 
     * @type {string}
     * @memberof IpcalcSubnetInfo
     */
    family: string;
    /**
     * 
     * @type {string}
     * @memberof IpcalcSubnetInfo
     */
    host_max: string;
    /**
     * 
     * @type {string}
     * @memberof IpcalcSubnetInfo
     */
    host_max_bits: string;
    /**
     * 
     * @type {string}
     * @memberof IpcalcSubnetInfo
     */
    host_min: string;
    /**
     * 
     * @type {string}
     * @memberof IpcalcSubnetInfo
     */
    host_min_bits: string;
    /**
     * 
     * @type {boolean}
     * @memberof IpcalcSubnetInfo
     */
    host_route?: boolean;
    /**
     * 
     * @type {string}
     * @memberof IpcalcSubnetInfo
     */
    hosts: string;
    /**
     * 
     * @type {string}
     * @memberof IpcalcSubnetInfo
     */
    netmask: string;
    /**
     * 
     * @type {string}
     * @memberof IpcalcSubnetInfo
     */
    netmask_bits: string;
    /**
     * 
     * @type {string}
     * @memberof IpcalcSubnetInfo
     */
    network: string;
    /**
     * 
     * @type {string}
     * @memberof IpcalcSubnetInfo
     */
    network_bits: string;
    /**
     * 
     * @type {number}
     * @memberof IpcalcSubnetInfo
     */
    prefix: number;
    /**
     * 
     * @type {string}
     * @memberof IpcalcSubnetInfo
     */
    scope: string;
    /**
     * 
     * @type {string}
     * @memberof IpcalcSubnetInfo
     */
    wildcard: string;
    /**
     * 
     * @type {string}
     * @memberof IpcalcSubnetInfo
     */
    wildcard_bits: string;
}

/**
 * Check if a given object implements the IpcalcSubnetInfo interface.
 */
export function instanceOfIpcalcSubnetInfo(value: object): value is IpcalcSubnetInfo {
    if (!('address' in value) || value['address'] === undefined) return false;
    if (!('address_bits' in value) || value['address_bits'] === undefined) return false;
    if (!('family' in value) || value['family'] === undefined) return false;
    if (!('host_max' in value) || value['host_max'] === undefined) return false;
    if (!('host_max_bits' in value) || value['host_max_bits'] === undefined) return false;
    if (!('host_min' in value) || value['host_min'] === undefined) return false;
    if (!('host_min_bits' in value) || value['host_min_bits'] === undefined) return false;
    if (!('hosts' in value) || value['hosts'] === undefined) return false;
    if (!('netmask' in value) || value['netmask'] === undefined) return false;
    if (!('netmask_bits' in value) || value['netmask_bits'] === undefined) return false;
    if (!('network' in value) || value['network'] === undefined) return false;
    if (!('network_bits' in value) || value['network_bits'] === undefined) return false;
    if (!('prefix' in value) || value['prefix'] === undefined) return false;
    if (!('scope' in value) || value['scope'] === undefined) return false;
    if (!('wildcard' in value) || value['wildcard'] === undefined) return false;
    if (!('wildcard_bits' in value) || value['wildcard_bits'] === undefined) return false;
    return true;
}

export function IpcalcSubnetInfoFromJSON(json: any): IpcalcSubnetInfo {
    return IpcalcSubnetInfoFromJSONTyped(json, false);
}

export function IpcalcSubnetInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): IpcalcSubnetInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'address': json['address'],
        'address_bits': json['address_bits'],
        'broadcast': json['broadcast'] == null ? undefined : json['broadcast'],
        'broadcast_bits': json['broadcast_bits'] == null ? undefined : json['broadcast_bits'],
        '_class': json['class'] == null ? undefined : json['class'],
        'family': json['family'],
        'host_max': json['host_max'],
        'host_max_bits': json['host_max_bits'],
        'host_min': json['host_min'],
        'host_min_bits': json['host_min_bits'],
        'host_route': json['host_route'] == null ? undefined : json['host_route'],
        'hosts': json['hosts'],
        'netmask': json['netmask'],
        'netmask_bits': json['netmask_bits'],
        'network': json['network'],
        'network_bits': json['network_bits'],
        'prefix': json['prefix'],
        'scope': json['scope'],
        'wildcard': json['wildcard'],
        'wildcard_bits': json['wildcard_bits'],
    };
}

export function IpcalcSubnetInfoToJSON(json: any): IpcalcSubnetInfo {
    return IpcalcSubnetInfoToJSONTyped(json, false);
}

export function IpcalcSubnetInfoToJSONTyped(value?: IpcalcSubnetInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'address': value['address'],
        'address_bits': value['address_bits'],
        'broadcast': value['broadcast'],
        'broadcast_bits': value['broadcast_bits'],
        'class': value['_class'],
        'family': value['family'],
        'host_max': value['host_max'],
        'host_max_bits': value['host_max_bits'],
        'host_min': value['host_min'],
        'host_min_bits': value['host_min_bits'],
        'host_route': value['host_route'],
        'hosts': value['hosts'],
        'netmask': value['netmask'],
        'netmask_bits': value['netmask_bits'],
        'network': value['network'],
        'network_bits': value['network_bits'],
        'prefix': value['prefix'],
        'scope': value['scope'],
        'wildcard': value['wildcard'],
        'wildcard_bits': value['wildcard_bits'],
    };
}

