/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface KeaLease
 */
export interface KeaLease {
    /**
     * 
     * @type {string}
     * @memberof KeaLease
     */
    duid: string;
    /**
     * 
     * @type {number}
     * @memberof KeaLease
     */
    expire: number;
    /**
     * 
     * @type {string}
     * @memberof KeaLease
     */
    hostname: string;
    /**
     * 
     * @type {string}
     * @memberof KeaLease
     */
    hw_address: string;
    /**
     * 
     * @type {string}
     * @memberof KeaLease
     */
    ip_address: string;
    /**
     * 
     * @type {number}
     * @memberof KeaLease
     */
    state: number;
    /**
     * 
     * @type {number}
     * @memberof KeaLease
     */
    subnet_id: number;
}

/**
 * Check if a given object implements the KeaLease interface.
 */
export function instanceOfKeaLease(value: object): value is KeaLease {
    if (!('duid' in value) || value['duid'] === undefined) return false;
    if (!('expire' in value) || value['expire'] === undefined) return false;
    if (!('hostname' in value) || value['hostname'] === undefined) return false;
    if (!('hw_address' in value) || value['hw_address'] === undefined) return false;
    if (!('ip_address' in value) || value['ip_address'] === undefined) return false;
    if (!('state' in value) || value['state'] === undefined) return false;
    if (!('subnet_id' in value) || value['subnet_id'] === undefined) return false;
    return true;
}

export function KeaLeaseFromJSON(json: any): KeaLease {
    return KeaLeaseFromJSONTyped(json, false);
}

export function KeaLeaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): KeaLease {
    if (json == null) {
        return json;
    }
    return {
        
        'duid': json['duid'],
        'expire': json['expire'],
        'hostname': json['hostname'],
        'hw_address': json['hw-address'],
        'ip_address': json['ip-address'],
        'state': json['state'],
        'subnet_id': json['subnet-id'],
    };
}

export function KeaLeaseToJSON(json: any): KeaLease {
    return KeaLeaseToJSONTyped(json, false);
}

export function KeaLeaseToJSONTyped(value?: KeaLease | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'duid': value['duid'],
        'expire': value['expire'],
        'hostname': value['hostname'],
        'hw-address': value['hw_address'],
        'ip-address': value['ip_address'],
        'state': value['state'],
        'subnet-id': value['subnet_id'],
    };
}

