/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ManagersPushResult
 */
export interface ManagersPushResult {
    /**
     * 
     * @type {string}
     * @memberof ManagersPushResult
     */
    error: string;
    /**
     * 
     * @type {string}
     * @memberof ManagersPushResult
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ManagersPushResult
     */
    url: string;
}

/**
 * Check if a given object implements the ManagersPushResult interface.
 */
export function instanceOfManagersPushResult(value: object): value is ManagersPushResult {
    if (!('error' in value) || value['error'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function ManagersPushResultFromJSON(json: any): ManagersPushResult {
    return ManagersPushResultFromJSONTyped(json, false);
}

export function ManagersPushResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): ManagersPushResult {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'],
        'name': json['name'],
        'url': json['url'],
    };
}

export function ManagersPushResultToJSON(json: any): ManagersPushResult {
    return ManagersPushResultToJSONTyped(json, false);
}

export function ManagersPushResultToJSONTyped(value?: ManagersPushResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
        'name': value['name'],
        'url': value['url'],
    };
}

