/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TypesLearnedRoute } from './TypesLearnedRoute';
import {
    TypesLearnedRouteFromJSON,
    TypesLearnedRouteFromJSONTyped,
    TypesLearnedRouteToJSON,
    TypesLearnedRouteToJSONTyped,
} from './TypesLearnedRoute';

/**
 * 
 * @export
 * @interface TypesLearnedRoutesResponse
 */
export interface TypesLearnedRoutesResponse {
    /**
     * 
     * @type {Array<TypesLearnedRoute>}
     * @memberof TypesLearnedRoutesResponse
     */
    bgp?: Array<TypesLearnedRoute>;
    /**
     * 
     * @type {Array<TypesLearnedRoute>}
     * @memberof TypesLearnedRoutesResponse
     */
    ospf?: Array<TypesLearnedRoute>;
}

/**
 * Check if a given object implements the TypesLearnedRoutesResponse interface.
 */
export function instanceOfTypesLearnedRoutesResponse(value: object): value is TypesLearnedRoutesResponse {
    return true;
}

export function TypesLearnedRoutesResponseFromJSON(json: any): TypesLearnedRoutesResponse {
    return TypesLearnedRoutesResponseFromJSONTyped(json, false);
}

export function TypesLearnedRoutesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesLearnedRoutesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'bgp': json['bgp'] == null ? undefined : ((json['bgp'] as Array<any>).map(TypesLearnedRouteFromJSON)),
        'ospf': json['ospf'] == null ? undefined : ((json['ospf'] as Array<any>).map(TypesLearnedRouteFromJSON)),
    };
}

export function TypesLearnedRoutesResponseToJSON(json: any): TypesLearnedRoutesResponse {
    return TypesLearnedRoutesResponseToJSONTyped(json, false);
}

export function TypesLearnedRoutesResponseToJSONTyped(value?: TypesLearnedRoutesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bgp': value['bgp'] == null ? undefined : ((value['bgp'] as Array<any>).map(TypesLearnedRouteToJSON)),
        'ospf': value['ospf'] == null ? undefined : ((value['ospf'] as Array<any>).map(TypesLearnedRouteToJSON)),
    };
}

