/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TypesFailuresResponse } from './TypesFailuresResponse';
import {
    TypesFailuresResponseFromJSON,
    TypesFailuresResponseFromJSONTyped,
    TypesFailuresResponseToJSON,
    TypesFailuresResponseToJSONTyped,
} from './TypesFailuresResponse';

/**
 * 
 * @export
 * @interface TypesResponseTypesFailuresResponse
 */
export interface TypesResponseTypesFailuresResponse {
    /**
     * 
     * @type {number}
     * @memberof TypesResponseTypesFailuresResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof TypesResponseTypesFailuresResponse
     */
    error?: string;
    /**
     * 
     * @type {TypesFailuresResponse}
     * @memberof TypesResponseTypesFailuresResponse
     */
    result?: TypesFailuresResponse;
    /**
     * 
     * @type {string}
     * @memberof TypesResponseTypesFailuresResponse
     */
    status?: string;
}

/**
 * Check if a given object implements the TypesResponseTypesFailuresResponse interface.
 */
export function instanceOfTypesResponseTypesFailuresResponse(value: object): value is TypesResponseTypesFailuresResponse {
    return true;
}

export function TypesResponseTypesFailuresResponseFromJSON(json: any): TypesResponseTypesFailuresResponse {
    return TypesResponseTypesFailuresResponseFromJSONTyped(json, false);
}

export function TypesResponseTypesFailuresResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesResponseTypesFailuresResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'error': json['error'] == null ? undefined : json['error'],
        'result': json['result'] == null ? undefined : TypesFailuresResponseFromJSON(json['result']),
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function TypesResponseTypesFailuresResponseToJSON(json: any): TypesResponseTypesFailuresResponse {
    return TypesResponseTypesFailuresResponseToJSONTyped(json, false);
}

export function TypesResponseTypesFailuresResponseToJSONTyped(value?: TypesResponseTypesFailuresResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'error': value['error'],
        'result': TypesFailuresResponseToJSON(value['result']),
        'status': value['status'],
    };
}

