/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TypesProtoHistoryPoint
 */
export interface TypesProtoHistoryPoint {
    /**
     * 
     * @type {number}
     * @memberof TypesProtoHistoryPoint
     */
    icmp_in_msgs: number;
    /**
     * 
     * @type {number}
     * @memberof TypesProtoHistoryPoint
     */
    icmp_out_msgs: number;
    /**
     * 
     * @type {number}
     * @memberof TypesProtoHistoryPoint
     */
    tcp_active_opens: number;
    /**
     * 
     * @type {number}
     * @memberof TypesProtoHistoryPoint
     */
    tcp_attempt_fails: number;
    /**
     * 
     * @type {number}
     * @memberof TypesProtoHistoryPoint
     */
    tcp_curr_estab: number;
    /**
     * 
     * @type {number}
     * @memberof TypesProtoHistoryPoint
     */
    tcp_estab_resets: number;
    /**
     * 
     * @type {number}
     * @memberof TypesProtoHistoryPoint
     */
    tcp_in_segs: number;
    /**
     * 
     * @type {number}
     * @memberof TypesProtoHistoryPoint
     */
    tcp_out_segs: number;
    /**
     * 
     * @type {number}
     * @memberof TypesProtoHistoryPoint
     */
    tcp_passive_opens: number;
    /**
     * 
     * @type {number}
     * @memberof TypesProtoHistoryPoint
     */
    tcp_retrans_segs: number;
    /**
     * 
     * @type {number}
     * @memberof TypesProtoHistoryPoint
     */
    ts: number;
    /**
     * 
     * @type {number}
     * @memberof TypesProtoHistoryPoint
     */
    udp_in_datagrams: number;
    /**
     * 
     * @type {number}
     * @memberof TypesProtoHistoryPoint
     */
    udp_in_errors: number;
    /**
     * 
     * @type {number}
     * @memberof TypesProtoHistoryPoint
     */
    udp_no_ports: number;
    /**
     * 
     * @type {number}
     * @memberof TypesProtoHistoryPoint
     */
    udp_out_datagrams: number;
}

/**
 * Check if a given object implements the TypesProtoHistoryPoint interface.
 */
export function instanceOfTypesProtoHistoryPoint(value: object): value is TypesProtoHistoryPoint {
    if (!('icmp_in_msgs' in value) || value['icmp_in_msgs'] === undefined) return false;
    if (!('icmp_out_msgs' in value) || value['icmp_out_msgs'] === undefined) return false;
    if (!('tcp_active_opens' in value) || value['tcp_active_opens'] === undefined) return false;
    if (!('tcp_attempt_fails' in value) || value['tcp_attempt_fails'] === undefined) return false;
    if (!('tcp_curr_estab' in value) || value['tcp_curr_estab'] === undefined) return false;
    if (!('tcp_estab_resets' in value) || value['tcp_estab_resets'] === undefined) return false;
    if (!('tcp_in_segs' in value) || value['tcp_in_segs'] === undefined) return false;
    if (!('tcp_out_segs' in value) || value['tcp_out_segs'] === undefined) return false;
    if (!('tcp_passive_opens' in value) || value['tcp_passive_opens'] === undefined) return false;
    if (!('tcp_retrans_segs' in value) || value['tcp_retrans_segs'] === undefined) return false;
    if (!('ts' in value) || value['ts'] === undefined) return false;
    if (!('udp_in_datagrams' in value) || value['udp_in_datagrams'] === undefined) return false;
    if (!('udp_in_errors' in value) || value['udp_in_errors'] === undefined) return false;
    if (!('udp_no_ports' in value) || value['udp_no_ports'] === undefined) return false;
    if (!('udp_out_datagrams' in value) || value['udp_out_datagrams'] === undefined) return false;
    return true;
}

export function TypesProtoHistoryPointFromJSON(json: any): TypesProtoHistoryPoint {
    return TypesProtoHistoryPointFromJSONTyped(json, false);
}

export function TypesProtoHistoryPointFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesProtoHistoryPoint {
    if (json == null) {
        return json;
    }
    return {
        
        'icmp_in_msgs': json['icmp_in_msgs'],
        'icmp_out_msgs': json['icmp_out_msgs'],
        'tcp_active_opens': json['tcp_active_opens'],
        'tcp_attempt_fails': json['tcp_attempt_fails'],
        'tcp_curr_estab': json['tcp_curr_estab'],
        'tcp_estab_resets': json['tcp_estab_resets'],
        'tcp_in_segs': json['tcp_in_segs'],
        'tcp_out_segs': json['tcp_out_segs'],
        'tcp_passive_opens': json['tcp_passive_opens'],
        'tcp_retrans_segs': json['tcp_retrans_segs'],
        'ts': json['ts'],
        'udp_in_datagrams': json['udp_in_datagrams'],
        'udp_in_errors': json['udp_in_errors'],
        'udp_no_ports': json['udp_no_ports'],
        'udp_out_datagrams': json['udp_out_datagrams'],
    };
}

export function TypesProtoHistoryPointToJSON(json: any): TypesProtoHistoryPoint {
    return TypesProtoHistoryPointToJSONTyped(json, false);
}

export function TypesProtoHistoryPointToJSONTyped(value?: TypesProtoHistoryPoint | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'icmp_in_msgs': value['icmp_in_msgs'],
        'icmp_out_msgs': value['icmp_out_msgs'],
        'tcp_active_opens': value['tcp_active_opens'],
        'tcp_attempt_fails': value['tcp_attempt_fails'],
        'tcp_curr_estab': value['tcp_curr_estab'],
        'tcp_estab_resets': value['tcp_estab_resets'],
        'tcp_in_segs': value['tcp_in_segs'],
        'tcp_out_segs': value['tcp_out_segs'],
        'tcp_passive_opens': value['tcp_passive_opens'],
        'tcp_retrans_segs': value['tcp_retrans_segs'],
        'ts': value['ts'],
        'udp_in_datagrams': value['udp_in_datagrams'],
        'udp_in_errors': value['udp_in_errors'],
        'udp_no_ports': value['udp_no_ports'],
        'udp_out_datagrams': value['udp_out_datagrams'],
    };
}

