/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TypesConfigureVRRPRequest
 */
export interface TypesConfigureVRRPRequest {
    /**
     * 
     * @type {string}
     * @memberof TypesConfigureVRRPRequest
     */
    friend_interface: string;
    /**
     * 
     * @type {string}
     * @memberof TypesConfigureVRRPRequest
     */
    local_interface: string;
    /**
     * 
     * @type {number}
     * @memberof TypesConfigureVRRPRequest
     */
    priority?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof TypesConfigureVRRPRequest
     */
    vips: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof TypesConfigureVRRPRequest
     */
    vrid: number;
}

/**
 * Check if a given object implements the TypesConfigureVRRPRequest interface.
 */
export function instanceOfTypesConfigureVRRPRequest(value: object): value is TypesConfigureVRRPRequest {
    if (!('friend_interface' in value) || value['friend_interface'] === undefined) return false;
    if (!('local_interface' in value) || value['local_interface'] === undefined) return false;
    if (!('vips' in value) || value['vips'] === undefined) return false;
    if (!('vrid' in value) || value['vrid'] === undefined) return false;
    return true;
}

export function TypesConfigureVRRPRequestFromJSON(json: any): TypesConfigureVRRPRequest {
    return TypesConfigureVRRPRequestFromJSONTyped(json, false);
}

export function TypesConfigureVRRPRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesConfigureVRRPRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'friend_interface': json['friend_interface'],
        'local_interface': json['local_interface'],
        'priority': json['priority'] == null ? undefined : json['priority'],
        'vips': json['vips'],
        'vrid': json['vrid'],
    };
}

export function TypesConfigureVRRPRequestToJSON(json: any): TypesConfigureVRRPRequest {
    return TypesConfigureVRRPRequestToJSONTyped(json, false);
}

export function TypesConfigureVRRPRequestToJSONTyped(value?: TypesConfigureVRRPRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'friend_interface': value['friend_interface'],
        'local_interface': value['local_interface'],
        'priority': value['priority'],
        'vips': value['vips'],
        'vrid': value['vrid'],
    };
}

