/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConfigConfig } from './ConfigConfig';
import {
    ConfigConfigFromJSON,
    ConfigConfigFromJSONTyped,
    ConfigConfigToJSON,
    ConfigConfigToJSONTyped,
} from './ConfigConfig';

/**
 * 
 * @export
 * @interface TypesResponseConfigConfig
 */
export interface TypesResponseConfigConfig {
    /**
     * 
     * @type {number}
     * @memberof TypesResponseConfigConfig
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof TypesResponseConfigConfig
     */
    error?: string;
    /**
     * 
     * @type {ConfigConfig}
     * @memberof TypesResponseConfigConfig
     */
    result?: ConfigConfig;
    /**
     * 
     * @type {string}
     * @memberof TypesResponseConfigConfig
     */
    status?: string;
}

/**
 * Check if a given object implements the TypesResponseConfigConfig interface.
 */
export function instanceOfTypesResponseConfigConfig(value: object): value is TypesResponseConfigConfig {
    return true;
}

export function TypesResponseConfigConfigFromJSON(json: any): TypesResponseConfigConfig {
    return TypesResponseConfigConfigFromJSONTyped(json, false);
}

export function TypesResponseConfigConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesResponseConfigConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'error': json['error'] == null ? undefined : json['error'],
        'result': json['result'] == null ? undefined : ConfigConfigFromJSON(json['result']),
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function TypesResponseConfigConfigToJSON(json: any): TypesResponseConfigConfig {
    return TypesResponseConfigConfigToJSONTyped(json, false);
}

export function TypesResponseConfigConfigToJSONTyped(value?: TypesResponseConfigConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'error': value['error'],
        'result': ConfigConfigToJSON(value['result']),
        'status': value['status'],
    };
}

