/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TypesProbeHistoryPoint
 */
export interface TypesProbeHistoryPoint {
    /**
     * 
     * @type {string}
     * @memberof TypesProbeHistoryPoint
     */
    name: string;
    /**
     * 
     * @type {boolean}
     * @memberof TypesProbeHistoryPoint
     */
    reachable: boolean;
    /**
     * 
     * @type {number}
     * @memberof TypesProbeHistoryPoint
     */
    rtt_avg_ms?: number;
    /**
     * 
     * @type {string}
     * @memberof TypesProbeHistoryPoint
     */
    target: string;
    /**
     * 
     * @type {number}
     * @memberof TypesProbeHistoryPoint
     */
    ts: number;
}

/**
 * Check if a given object implements the TypesProbeHistoryPoint interface.
 */
export function instanceOfTypesProbeHistoryPoint(value: object): value is TypesProbeHistoryPoint {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('reachable' in value) || value['reachable'] === undefined) return false;
    if (!('target' in value) || value['target'] === undefined) return false;
    if (!('ts' in value) || value['ts'] === undefined) return false;
    return true;
}

export function TypesProbeHistoryPointFromJSON(json: any): TypesProbeHistoryPoint {
    return TypesProbeHistoryPointFromJSONTyped(json, false);
}

export function TypesProbeHistoryPointFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesProbeHistoryPoint {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'reachable': json['reachable'],
        'rtt_avg_ms': json['rtt_avg_ms'] == null ? undefined : json['rtt_avg_ms'],
        'target': json['target'],
        'ts': json['ts'],
    };
}

export function TypesProbeHistoryPointToJSON(json: any): TypesProbeHistoryPoint {
    return TypesProbeHistoryPointToJSONTyped(json, false);
}

export function TypesProbeHistoryPointToJSONTyped(value?: TypesProbeHistoryPoint | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'reachable': value['reachable'],
        'rtt_avg_ms': value['rtt_avg_ms'],
        'target': value['target'],
        'ts': value['ts'],
    };
}

