/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TypesLoginResponse
 */
export interface TypesLoginResponse {
    /**
     * 
     * @type {string}
     * @memberof TypesLoginResponse
     */
    token: string;
}

/**
 * Check if a given object implements the TypesLoginResponse interface.
 */
export function instanceOfTypesLoginResponse(value: object): value is TypesLoginResponse {
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function TypesLoginResponseFromJSON(json: any): TypesLoginResponse {
    return TypesLoginResponseFromJSONTyped(json, false);
}

export function TypesLoginResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesLoginResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'],
    };
}

export function TypesLoginResponseToJSON(json: any): TypesLoginResponse {
    return TypesLoginResponseToJSONTyped(json, false);
}

export function TypesLoginResponseToJSONTyped(value?: TypesLoginResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
    };
}

