/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TypesFriendInfo } from './TypesFriendInfo';
import {
    TypesFriendInfoFromJSON,
    TypesFriendInfoFromJSONTyped,
    TypesFriendInfoToJSON,
    TypesFriendInfoToJSONTyped,
} from './TypesFriendInfo';

/**
 * 
 * @export
 * @interface TypesResponseTypesFriendInfo
 */
export interface TypesResponseTypesFriendInfo {
    /**
     * 
     * @type {number}
     * @memberof TypesResponseTypesFriendInfo
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof TypesResponseTypesFriendInfo
     */
    error?: string;
    /**
     * 
     * @type {TypesFriendInfo}
     * @memberof TypesResponseTypesFriendInfo
     */
    result?: TypesFriendInfo;
    /**
     * 
     * @type {string}
     * @memberof TypesResponseTypesFriendInfo
     */
    status?: string;
}

/**
 * Check if a given object implements the TypesResponseTypesFriendInfo interface.
 */
export function instanceOfTypesResponseTypesFriendInfo(value: object): value is TypesResponseTypesFriendInfo {
    return true;
}

export function TypesResponseTypesFriendInfoFromJSON(json: any): TypesResponseTypesFriendInfo {
    return TypesResponseTypesFriendInfoFromJSONTyped(json, false);
}

export function TypesResponseTypesFriendInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesResponseTypesFriendInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'error': json['error'] == null ? undefined : json['error'],
        'result': json['result'] == null ? undefined : TypesFriendInfoFromJSON(json['result']),
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function TypesResponseTypesFriendInfoToJSON(json: any): TypesResponseTypesFriendInfo {
    return TypesResponseTypesFriendInfoToJSONTyped(json, false);
}

export function TypesResponseTypesFriendInfoToJSONTyped(value?: TypesResponseTypesFriendInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'error': value['error'],
        'result': TypesFriendInfoToJSON(value['result']),
        'status': value['status'],
    };
}

