/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TypesConfigureVRRPResult } from './TypesConfigureVRRPResult';
import {
    TypesConfigureVRRPResultFromJSON,
    TypesConfigureVRRPResultFromJSONTyped,
    TypesConfigureVRRPResultToJSON,
    TypesConfigureVRRPResultToJSONTyped,
} from './TypesConfigureVRRPResult';

/**
 * 
 * @export
 * @interface TypesResponseTypesConfigureVRRPResult
 */
export interface TypesResponseTypesConfigureVRRPResult {
    /**
     * 
     * @type {number}
     * @memberof TypesResponseTypesConfigureVRRPResult
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof TypesResponseTypesConfigureVRRPResult
     */
    error?: string;
    /**
     * 
     * @type {TypesConfigureVRRPResult}
     * @memberof TypesResponseTypesConfigureVRRPResult
     */
    result?: TypesConfigureVRRPResult;
    /**
     * 
     * @type {string}
     * @memberof TypesResponseTypesConfigureVRRPResult
     */
    status?: string;
}

/**
 * Check if a given object implements the TypesResponseTypesConfigureVRRPResult interface.
 */
export function instanceOfTypesResponseTypesConfigureVRRPResult(value: object): value is TypesResponseTypesConfigureVRRPResult {
    return true;
}

export function TypesResponseTypesConfigureVRRPResultFromJSON(json: any): TypesResponseTypesConfigureVRRPResult {
    return TypesResponseTypesConfigureVRRPResultFromJSONTyped(json, false);
}

export function TypesResponseTypesConfigureVRRPResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesResponseTypesConfigureVRRPResult {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'error': json['error'] == null ? undefined : json['error'],
        'result': json['result'] == null ? undefined : TypesConfigureVRRPResultFromJSON(json['result']),
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function TypesResponseTypesConfigureVRRPResultToJSON(json: any): TypesResponseTypesConfigureVRRPResult {
    return TypesResponseTypesConfigureVRRPResultToJSONTyped(json, false);
}

export function TypesResponseTypesConfigureVRRPResultToJSONTyped(value?: TypesResponseTypesConfigureVRRPResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'error': value['error'],
        'result': TypesConfigureVRRPResultToJSON(value['result']),
        'status': value['status'],
    };
}

