/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TypesSetupStatus
 */
export interface TypesSetupStatus {
    /**
     * 
     * @type {boolean}
     * @memberof TypesSetupStatus
     */
    has_interfaces: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof TypesSetupStatus
     */
    needs_password_change: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof TypesSetupStatus
     */
    onboarding_complete: boolean;
}

/**
 * Check if a given object implements the TypesSetupStatus interface.
 */
export function instanceOfTypesSetupStatus(value: object): value is TypesSetupStatus {
    if (!('has_interfaces' in value) || value['has_interfaces'] === undefined) return false;
    if (!('needs_password_change' in value) || value['needs_password_change'] === undefined) return false;
    if (!('onboarding_complete' in value) || value['onboarding_complete'] === undefined) return false;
    return true;
}

export function TypesSetupStatusFromJSON(json: any): TypesSetupStatus {
    return TypesSetupStatusFromJSONTyped(json, false);
}

export function TypesSetupStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesSetupStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'has_interfaces': json['has_interfaces'],
        'needs_password_change': json['needs_password_change'],
        'onboarding_complete': json['onboarding_complete'],
    };
}

export function TypesSetupStatusToJSON(json: any): TypesSetupStatus {
    return TypesSetupStatusToJSONTyped(json, false);
}

export function TypesSetupStatusToJSONTyped(value?: TypesSetupStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'has_interfaces': value['has_interfaces'],
        'needs_password_change': value['needs_password_change'],
        'onboarding_complete': value['onboarding_complete'],
    };
}

