/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TypesFailureRecord } from './TypesFailureRecord';
import {
    TypesFailureRecordFromJSON,
    TypesFailureRecordFromJSONTyped,
    TypesFailureRecordToJSON,
    TypesFailureRecordToJSONTyped,
} from './TypesFailureRecord';

/**
 * 
 * @export
 * @interface TypesFailuresResponse
 */
export interface TypesFailuresResponse {
    /**
     * 
     * @type {Array<TypesFailureRecord>}
     * @memberof TypesFailuresResponse
     */
    failures?: Array<TypesFailureRecord>;
}

/**
 * Check if a given object implements the TypesFailuresResponse interface.
 */
export function instanceOfTypesFailuresResponse(value: object): value is TypesFailuresResponse {
    return true;
}

export function TypesFailuresResponseFromJSON(json: any): TypesFailuresResponse {
    return TypesFailuresResponseFromJSONTyped(json, false);
}

export function TypesFailuresResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesFailuresResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'failures': json['failures'] == null ? undefined : ((json['failures'] as Array<any>).map(TypesFailureRecordFromJSON)),
    };
}

export function TypesFailuresResponseToJSON(json: any): TypesFailuresResponse {
    return TypesFailuresResponseToJSONTyped(json, false);
}

export function TypesFailuresResponseToJSONTyped(value?: TypesFailuresResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'failures': value['failures'] == null ? undefined : ((value['failures'] as Array<any>).map(TypesFailureRecordToJSON)),
    };
}

