/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TypesPubKeyResponse } from './TypesPubKeyResponse';
import {
    TypesPubKeyResponseFromJSON,
    TypesPubKeyResponseFromJSONTyped,
    TypesPubKeyResponseToJSON,
    TypesPubKeyResponseToJSONTyped,
} from './TypesPubKeyResponse';

/**
 * 
 * @export
 * @interface TypesResponseTypesPubKeyResponse
 */
export interface TypesResponseTypesPubKeyResponse {
    /**
     * 
     * @type {number}
     * @memberof TypesResponseTypesPubKeyResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof TypesResponseTypesPubKeyResponse
     */
    error?: string;
    /**
     * 
     * @type {TypesPubKeyResponse}
     * @memberof TypesResponseTypesPubKeyResponse
     */
    result?: TypesPubKeyResponse;
    /**
     * 
     * @type {string}
     * @memberof TypesResponseTypesPubKeyResponse
     */
    status?: string;
}

/**
 * Check if a given object implements the TypesResponseTypesPubKeyResponse interface.
 */
export function instanceOfTypesResponseTypesPubKeyResponse(value: object): value is TypesResponseTypesPubKeyResponse {
    return true;
}

export function TypesResponseTypesPubKeyResponseFromJSON(json: any): TypesResponseTypesPubKeyResponse {
    return TypesResponseTypesPubKeyResponseFromJSONTyped(json, false);
}

export function TypesResponseTypesPubKeyResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesResponseTypesPubKeyResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'error': json['error'] == null ? undefined : json['error'],
        'result': json['result'] == null ? undefined : TypesPubKeyResponseFromJSON(json['result']),
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function TypesResponseTypesPubKeyResponseToJSON(json: any): TypesResponseTypesPubKeyResponse {
    return TypesResponseTypesPubKeyResponseToJSONTyped(json, false);
}

export function TypesResponseTypesPubKeyResponseToJSONTyped(value?: TypesResponseTypesPubKeyResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'error': value['error'],
        'result': TypesPubKeyResponseToJSON(value['result']),
        'status': value['status'],
    };
}

