/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TypesFriendDeleteResult } from './TypesFriendDeleteResult';
import {
    TypesFriendDeleteResultFromJSON,
    TypesFriendDeleteResultFromJSONTyped,
    TypesFriendDeleteResultToJSON,
    TypesFriendDeleteResultToJSONTyped,
} from './TypesFriendDeleteResult';

/**
 * 
 * @export
 * @interface TypesResponseTypesFriendDeleteResult
 */
export interface TypesResponseTypesFriendDeleteResult {
    /**
     * 
     * @type {number}
     * @memberof TypesResponseTypesFriendDeleteResult
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof TypesResponseTypesFriendDeleteResult
     */
    error?: string;
    /**
     * 
     * @type {TypesFriendDeleteResult}
     * @memberof TypesResponseTypesFriendDeleteResult
     */
    result?: TypesFriendDeleteResult;
    /**
     * 
     * @type {string}
     * @memberof TypesResponseTypesFriendDeleteResult
     */
    status?: string;
}

/**
 * Check if a given object implements the TypesResponseTypesFriendDeleteResult interface.
 */
export function instanceOfTypesResponseTypesFriendDeleteResult(value: object): value is TypesResponseTypesFriendDeleteResult {
    return true;
}

export function TypesResponseTypesFriendDeleteResultFromJSON(json: any): TypesResponseTypesFriendDeleteResult {
    return TypesResponseTypesFriendDeleteResultFromJSONTyped(json, false);
}

export function TypesResponseTypesFriendDeleteResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesResponseTypesFriendDeleteResult {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'error': json['error'] == null ? undefined : json['error'],
        'result': json['result'] == null ? undefined : TypesFriendDeleteResultFromJSON(json['result']),
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function TypesResponseTypesFriendDeleteResultToJSON(json: any): TypesResponseTypesFriendDeleteResult {
    return TypesResponseTypesFriendDeleteResultToJSONTyped(json, false);
}

export function TypesResponseTypesFriendDeleteResultToJSONTyped(value?: TypesResponseTypesFriendDeleteResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'error': value['error'],
        'result': TypesFriendDeleteResultToJSON(value['result']),
        'status': value['status'],
    };
}

