/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TypesPasswordHashRequest
 */
export interface TypesPasswordHashRequest {
    /**
     * 
     * @type {string}
     * @memberof TypesPasswordHashRequest
     */
    password: string;
}

/**
 * Check if a given object implements the TypesPasswordHashRequest interface.
 */
export function instanceOfTypesPasswordHashRequest(value: object): value is TypesPasswordHashRequest {
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function TypesPasswordHashRequestFromJSON(json: any): TypesPasswordHashRequest {
    return TypesPasswordHashRequestFromJSONTyped(json, false);
}

export function TypesPasswordHashRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesPasswordHashRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'password': json['password'],
    };
}

export function TypesPasswordHashRequestToJSON(json: any): TypesPasswordHashRequest {
    return TypesPasswordHashRequestToJSONTyped(json, false);
}

export function TypesPasswordHashRequestToJSONTyped(value?: TypesPasswordHashRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'password': value['password'],
    };
}

