/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TypesFriendPreview } from './TypesFriendPreview';
import {
    TypesFriendPreviewFromJSON,
    TypesFriendPreviewFromJSONTyped,
    TypesFriendPreviewToJSON,
    TypesFriendPreviewToJSONTyped,
} from './TypesFriendPreview';

/**
 * 
 * @export
 * @interface TypesResponseTypesFriendPreview
 */
export interface TypesResponseTypesFriendPreview {
    /**
     * 
     * @type {number}
     * @memberof TypesResponseTypesFriendPreview
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof TypesResponseTypesFriendPreview
     */
    error?: string;
    /**
     * 
     * @type {TypesFriendPreview}
     * @memberof TypesResponseTypesFriendPreview
     */
    result?: TypesFriendPreview;
    /**
     * 
     * @type {string}
     * @memberof TypesResponseTypesFriendPreview
     */
    status?: string;
}

/**
 * Check if a given object implements the TypesResponseTypesFriendPreview interface.
 */
export function instanceOfTypesResponseTypesFriendPreview(value: object): value is TypesResponseTypesFriendPreview {
    return true;
}

export function TypesResponseTypesFriendPreviewFromJSON(json: any): TypesResponseTypesFriendPreview {
    return TypesResponseTypesFriendPreviewFromJSONTyped(json, false);
}

export function TypesResponseTypesFriendPreviewFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesResponseTypesFriendPreview {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'error': json['error'] == null ? undefined : json['error'],
        'result': json['result'] == null ? undefined : TypesFriendPreviewFromJSON(json['result']),
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function TypesResponseTypesFriendPreviewToJSON(json: any): TypesResponseTypesFriendPreview {
    return TypesResponseTypesFriendPreviewToJSONTyped(json, false);
}

export function TypesResponseTypesFriendPreviewToJSONTyped(value?: TypesResponseTypesFriendPreview | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'error': value['error'],
        'result': TypesFriendPreviewToJSON(value['result']),
        'status': value['status'],
    };
}

