/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TypesNeighborStatsResponse } from './TypesNeighborStatsResponse';
import {
    TypesNeighborStatsResponseFromJSON,
    TypesNeighborStatsResponseFromJSONTyped,
    TypesNeighborStatsResponseToJSON,
    TypesNeighborStatsResponseToJSONTyped,
} from './TypesNeighborStatsResponse';

/**
 * 
 * @export
 * @interface TypesResponseTypesNeighborStatsResponse
 */
export interface TypesResponseTypesNeighborStatsResponse {
    /**
     * 
     * @type {number}
     * @memberof TypesResponseTypesNeighborStatsResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof TypesResponseTypesNeighborStatsResponse
     */
    error?: string;
    /**
     * 
     * @type {TypesNeighborStatsResponse}
     * @memberof TypesResponseTypesNeighborStatsResponse
     */
    result?: TypesNeighborStatsResponse;
    /**
     * 
     * @type {string}
     * @memberof TypesResponseTypesNeighborStatsResponse
     */
    status?: string;
}

/**
 * Check if a given object implements the TypesResponseTypesNeighborStatsResponse interface.
 */
export function instanceOfTypesResponseTypesNeighborStatsResponse(value: object): value is TypesResponseTypesNeighborStatsResponse {
    return true;
}

export function TypesResponseTypesNeighborStatsResponseFromJSON(json: any): TypesResponseTypesNeighborStatsResponse {
    return TypesResponseTypesNeighborStatsResponseFromJSONTyped(json, false);
}

export function TypesResponseTypesNeighborStatsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesResponseTypesNeighborStatsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'error': json['error'] == null ? undefined : json['error'],
        'result': json['result'] == null ? undefined : TypesNeighborStatsResponseFromJSON(json['result']),
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function TypesResponseTypesNeighborStatsResponseToJSON(json: any): TypesResponseTypesNeighborStatsResponse {
    return TypesResponseTypesNeighborStatsResponseToJSONTyped(json, false);
}

export function TypesResponseTypesNeighborStatsResponseToJSONTyped(value?: TypesResponseTypesNeighborStatsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'error': value['error'],
        'result': TypesNeighborStatsResponseToJSON(value['result']),
        'status': value['status'],
    };
}

