/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TypesKernelRoute } from './TypesKernelRoute';
import {
    TypesKernelRouteFromJSON,
    TypesKernelRouteFromJSONTyped,
    TypesKernelRouteToJSON,
    TypesKernelRouteToJSONTyped,
} from './TypesKernelRoute';

/**
 * 
 * @export
 * @interface TypesRoutesResponse
 */
export interface TypesRoutesResponse {
    /**
     * 
     * @type {Array<TypesKernelRoute>}
     * @memberof TypesRoutesResponse
     */
    routes?: Array<TypesKernelRoute>;
    /**
     * 
     * @type {number}
     * @memberof TypesRoutesResponse
     */
    total: number;
}

/**
 * Check if a given object implements the TypesRoutesResponse interface.
 */
export function instanceOfTypesRoutesResponse(value: object): value is TypesRoutesResponse {
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function TypesRoutesResponseFromJSON(json: any): TypesRoutesResponse {
    return TypesRoutesResponseFromJSONTyped(json, false);
}

export function TypesRoutesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesRoutesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'routes': json['routes'] == null ? undefined : ((json['routes'] as Array<any>).map(TypesKernelRouteFromJSON)),
        'total': json['total'],
    };
}

export function TypesRoutesResponseToJSON(json: any): TypesRoutesResponse {
    return TypesRoutesResponseToJSONTyped(json, false);
}

export function TypesRoutesResponseToJSONTyped(value?: TypesRoutesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'routes': value['routes'] == null ? undefined : ((value['routes'] as Array<any>).map(TypesKernelRouteToJSON)),
        'total': value['total'],
    };
}

