/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TypesNeighborsResponse } from './TypesNeighborsResponse';
import {
    TypesNeighborsResponseFromJSON,
    TypesNeighborsResponseFromJSONTyped,
    TypesNeighborsResponseToJSON,
    TypesNeighborsResponseToJSONTyped,
} from './TypesNeighborsResponse';

/**
 * 
 * @export
 * @interface TypesResponseTypesNeighborsResponse
 */
export interface TypesResponseTypesNeighborsResponse {
    /**
     * 
     * @type {number}
     * @memberof TypesResponseTypesNeighborsResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof TypesResponseTypesNeighborsResponse
     */
    error?: string;
    /**
     * 
     * @type {TypesNeighborsResponse}
     * @memberof TypesResponseTypesNeighborsResponse
     */
    result?: TypesNeighborsResponse;
    /**
     * 
     * @type {string}
     * @memberof TypesResponseTypesNeighborsResponse
     */
    status?: string;
}

/**
 * Check if a given object implements the TypesResponseTypesNeighborsResponse interface.
 */
export function instanceOfTypesResponseTypesNeighborsResponse(value: object): value is TypesResponseTypesNeighborsResponse {
    return true;
}

export function TypesResponseTypesNeighborsResponseFromJSON(json: any): TypesResponseTypesNeighborsResponse {
    return TypesResponseTypesNeighborsResponseFromJSONTyped(json, false);
}

export function TypesResponseTypesNeighborsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesResponseTypesNeighborsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'error': json['error'] == null ? undefined : json['error'],
        'result': json['result'] == null ? undefined : TypesNeighborsResponseFromJSON(json['result']),
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function TypesResponseTypesNeighborsResponseToJSON(json: any): TypesResponseTypesNeighborsResponse {
    return TypesResponseTypesNeighborsResponseToJSONTyped(json, false);
}

export function TypesResponseTypesNeighborsResponseToJSONTyped(value?: TypesResponseTypesNeighborsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'error': value['error'],
        'result': TypesNeighborsResponseToJSON(value['result']),
        'status': value['status'],
    };
}

