/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TypesBGPHistoryPoint
 */
export interface TypesBGPHistoryPoint {
    /**
     * 
     * @type {number}
     * @memberof TypesBGPHistoryPoint
     */
    msg_rcvd: number;
    /**
     * 
     * @type {number}
     * @memberof TypesBGPHistoryPoint
     */
    msg_sent: number;
    /**
     * 
     * @type {number}
     * @memberof TypesBGPHistoryPoint
     */
    prefixes: number;
    /**
     * 
     * @type {string}
     * @memberof TypesBGPHistoryPoint
     */
    state: string;
    /**
     * 
     * @type {number}
     * @memberof TypesBGPHistoryPoint
     */
    ts: number;
    /**
     * 
     * @type {string}
     * @memberof TypesBGPHistoryPoint
     */
    uptime: string;
}

/**
 * Check if a given object implements the TypesBGPHistoryPoint interface.
 */
export function instanceOfTypesBGPHistoryPoint(value: object): value is TypesBGPHistoryPoint {
    if (!('msg_rcvd' in value) || value['msg_rcvd'] === undefined) return false;
    if (!('msg_sent' in value) || value['msg_sent'] === undefined) return false;
    if (!('prefixes' in value) || value['prefixes'] === undefined) return false;
    if (!('state' in value) || value['state'] === undefined) return false;
    if (!('ts' in value) || value['ts'] === undefined) return false;
    if (!('uptime' in value) || value['uptime'] === undefined) return false;
    return true;
}

export function TypesBGPHistoryPointFromJSON(json: any): TypesBGPHistoryPoint {
    return TypesBGPHistoryPointFromJSONTyped(json, false);
}

export function TypesBGPHistoryPointFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesBGPHistoryPoint {
    if (json == null) {
        return json;
    }
    return {
        
        'msg_rcvd': json['msg_rcvd'],
        'msg_sent': json['msg_sent'],
        'prefixes': json['prefixes'],
        'state': json['state'],
        'ts': json['ts'],
        'uptime': json['uptime'],
    };
}

export function TypesBGPHistoryPointToJSON(json: any): TypesBGPHistoryPoint {
    return TypesBGPHistoryPointToJSONTyped(json, false);
}

export function TypesBGPHistoryPointToJSONTyped(value?: TypesBGPHistoryPoint | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'msg_rcvd': value['msg_rcvd'],
        'msg_sent': value['msg_sent'],
        'prefixes': value['prefixes'],
        'state': value['state'],
        'ts': value['ts'],
        'uptime': value['uptime'],
    };
}

