/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TypesAPIKey } from './TypesAPIKey';
import {
    TypesAPIKeyFromJSON,
    TypesAPIKeyFromJSONTyped,
    TypesAPIKeyToJSON,
    TypesAPIKeyToJSONTyped,
} from './TypesAPIKey';

/**
 * 
 * @export
 * @interface TypesResponseArrayTypesAPIKey
 */
export interface TypesResponseArrayTypesAPIKey {
    /**
     * 
     * @type {number}
     * @memberof TypesResponseArrayTypesAPIKey
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof TypesResponseArrayTypesAPIKey
     */
    error?: string;
    /**
     * 
     * @type {Array<TypesAPIKey>}
     * @memberof TypesResponseArrayTypesAPIKey
     */
    result?: Array<TypesAPIKey>;
    /**
     * 
     * @type {string}
     * @memberof TypesResponseArrayTypesAPIKey
     */
    status?: string;
}

/**
 * Check if a given object implements the TypesResponseArrayTypesAPIKey interface.
 */
export function instanceOfTypesResponseArrayTypesAPIKey(value: object): value is TypesResponseArrayTypesAPIKey {
    return true;
}

export function TypesResponseArrayTypesAPIKeyFromJSON(json: any): TypesResponseArrayTypesAPIKey {
    return TypesResponseArrayTypesAPIKeyFromJSONTyped(json, false);
}

export function TypesResponseArrayTypesAPIKeyFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesResponseArrayTypesAPIKey {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'error': json['error'] == null ? undefined : json['error'],
        'result': json['result'] == null ? undefined : ((json['result'] as Array<any>).map(TypesAPIKeyFromJSON)),
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function TypesResponseArrayTypesAPIKeyToJSON(json: any): TypesResponseArrayTypesAPIKey {
    return TypesResponseArrayTypesAPIKeyToJSONTyped(json, false);
}

export function TypesResponseArrayTypesAPIKeyToJSONTyped(value?: TypesResponseArrayTypesAPIKey | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'error': value['error'],
        'result': value['result'] == null ? undefined : ((value['result'] as Array<any>).map(TypesAPIKeyToJSON)),
        'status': value['status'],
    };
}

