/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TypesWGEndpoint
 */
export interface TypesWGEndpoint {
    /**
     * 
     * @type {string}
     * @memberof TypesWGEndpoint
     */
    address?: string;
    /**
     * 
     * @type {string}
     * @memberof TypesWGEndpoint
     */
    interface: string;
    /**
     * 
     * @type {number}
     * @memberof TypesWGEndpoint
     */
    listen_port?: number;
}

/**
 * Check if a given object implements the TypesWGEndpoint interface.
 */
export function instanceOfTypesWGEndpoint(value: object): value is TypesWGEndpoint {
    if (!('interface' in value) || value['interface'] === undefined) return false;
    return true;
}

export function TypesWGEndpointFromJSON(json: any): TypesWGEndpoint {
    return TypesWGEndpointFromJSONTyped(json, false);
}

export function TypesWGEndpointFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesWGEndpoint {
    if (json == null) {
        return json;
    }
    return {
        
        'address': json['address'] == null ? undefined : json['address'],
        'interface': json['interface'],
        'listen_port': json['listen_port'] == null ? undefined : json['listen_port'],
    };
}

export function TypesWGEndpointToJSON(json: any): TypesWGEndpoint {
    return TypesWGEndpointToJSONTyped(json, false);
}

export function TypesWGEndpointToJSONTyped(value?: TypesWGEndpoint | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'address': value['address'],
        'interface': value['interface'],
        'listen_port': value['listen_port'],
    };
}

