/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TypesVRRPPeer
 */
export interface TypesVRRPPeer {
    /**
     * 
     * @type {string}
     * @memberof TypesVRRPPeer
     */
    ip: string;
    /**
     * 
     * @type {string}
     * @memberof TypesVRRPPeer
     */
    last_seen?: string;
    /**
     * 
     * @type {number}
     * @memberof TypesVRRPPeer
     */
    priority: number;
}

/**
 * Check if a given object implements the TypesVRRPPeer interface.
 */
export function instanceOfTypesVRRPPeer(value: object): value is TypesVRRPPeer {
    if (!('ip' in value) || value['ip'] === undefined) return false;
    if (!('priority' in value) || value['priority'] === undefined) return false;
    return true;
}

export function TypesVRRPPeerFromJSON(json: any): TypesVRRPPeer {
    return TypesVRRPPeerFromJSONTyped(json, false);
}

export function TypesVRRPPeerFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesVRRPPeer {
    if (json == null) {
        return json;
    }
    return {
        
        'ip': json['ip'],
        'last_seen': json['last_seen'] == null ? undefined : json['last_seen'],
        'priority': json['priority'],
    };
}

export function TypesVRRPPeerToJSON(json: any): TypesVRRPPeer {
    return TypesVRRPPeerToJSONTyped(json, false);
}

export function TypesVRRPPeerToJSONTyped(value?: TypesVRRPPeer | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ip': value['ip'],
        'last_seen': value['last_seen'],
        'priority': value['priority'],
    };
}

