/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TypesFriendTaggedSection } from './TypesFriendTaggedSection';
import {
    TypesFriendTaggedSectionFromJSON,
    TypesFriendTaggedSectionFromJSONTyped,
    TypesFriendTaggedSectionToJSON,
    TypesFriendTaggedSectionToJSONTyped,
} from './TypesFriendTaggedSection';

/**
 * 
 * @export
 * @interface TypesFriendDeleteResult
 */
export interface TypesFriendDeleteResult {
    /**
     * 
     * @type {boolean}
     * @memberof TypesFriendDeleteResult
     */
    deleted: boolean;
    /**
     * 
     * @type {string}
     * @memberof TypesFriendDeleteResult
     */
    friend: string;
    /**
     * 
     * @type {Array<TypesFriendTaggedSection>}
     * @memberof TypesFriendDeleteResult
     */
    sections?: Array<TypesFriendTaggedSection>;
}

/**
 * Check if a given object implements the TypesFriendDeleteResult interface.
 */
export function instanceOfTypesFriendDeleteResult(value: object): value is TypesFriendDeleteResult {
    if (!('deleted' in value) || value['deleted'] === undefined) return false;
    if (!('friend' in value) || value['friend'] === undefined) return false;
    return true;
}

export function TypesFriendDeleteResultFromJSON(json: any): TypesFriendDeleteResult {
    return TypesFriendDeleteResultFromJSONTyped(json, false);
}

export function TypesFriendDeleteResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesFriendDeleteResult {
    if (json == null) {
        return json;
    }
    return {
        
        'deleted': json['deleted'],
        'friend': json['friend'],
        'sections': json['sections'] == null ? undefined : ((json['sections'] as Array<any>).map(TypesFriendTaggedSectionFromJSON)),
    };
}

export function TypesFriendDeleteResultToJSON(json: any): TypesFriendDeleteResult {
    return TypesFriendDeleteResultToJSONTyped(json, false);
}

export function TypesFriendDeleteResultToJSONTyped(value?: TypesFriendDeleteResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'deleted': value['deleted'],
        'friend': value['friend'],
        'sections': value['sections'] == null ? undefined : ((value['sections'] as Array<any>).map(TypesFriendTaggedSectionToJSON)),
    };
}

