/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TypesConfigureConntrackResult } from './TypesConfigureConntrackResult';
import {
    TypesConfigureConntrackResultFromJSON,
    TypesConfigureConntrackResultFromJSONTyped,
    TypesConfigureConntrackResultToJSON,
    TypesConfigureConntrackResultToJSONTyped,
} from './TypesConfigureConntrackResult';

/**
 * 
 * @export
 * @interface TypesResponseTypesConfigureConntrackResult
 */
export interface TypesResponseTypesConfigureConntrackResult {
    /**
     * 
     * @type {number}
     * @memberof TypesResponseTypesConfigureConntrackResult
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof TypesResponseTypesConfigureConntrackResult
     */
    error?: string;
    /**
     * 
     * @type {TypesConfigureConntrackResult}
     * @memberof TypesResponseTypesConfigureConntrackResult
     */
    result?: TypesConfigureConntrackResult;
    /**
     * 
     * @type {string}
     * @memberof TypesResponseTypesConfigureConntrackResult
     */
    status?: string;
}

/**
 * Check if a given object implements the TypesResponseTypesConfigureConntrackResult interface.
 */
export function instanceOfTypesResponseTypesConfigureConntrackResult(value: object): value is TypesResponseTypesConfigureConntrackResult {
    return true;
}

export function TypesResponseTypesConfigureConntrackResultFromJSON(json: any): TypesResponseTypesConfigureConntrackResult {
    return TypesResponseTypesConfigureConntrackResultFromJSONTyped(json, false);
}

export function TypesResponseTypesConfigureConntrackResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesResponseTypesConfigureConntrackResult {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'error': json['error'] == null ? undefined : json['error'],
        'result': json['result'] == null ? undefined : TypesConfigureConntrackResultFromJSON(json['result']),
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function TypesResponseTypesConfigureConntrackResultToJSON(json: any): TypesResponseTypesConfigureConntrackResult {
    return TypesResponseTypesConfigureConntrackResultToJSONTyped(json, false);
}

export function TypesResponseTypesConfigureConntrackResultToJSONTyped(value?: TypesResponseTypesConfigureConntrackResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'error': value['error'],
        'result': TypesConfigureConntrackResultToJSON(value['result']),
        'status': value['status'],
    };
}

