/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TypesChangePasswordRequest
 */
export interface TypesChangePasswordRequest {
    /**
     * 
     * @type {string}
     * @memberof TypesChangePasswordRequest
     */
    current: string;
    /**
     * 
     * @type {string}
     * @memberof TypesChangePasswordRequest
     */
    new: string;
}

/**
 * Check if a given object implements the TypesChangePasswordRequest interface.
 */
export function instanceOfTypesChangePasswordRequest(value: object): value is TypesChangePasswordRequest {
    if (!('current' in value) || value['current'] === undefined) return false;
    if (!('new' in value) || value['new'] === undefined) return false;
    return true;
}

export function TypesChangePasswordRequestFromJSON(json: any): TypesChangePasswordRequest {
    return TypesChangePasswordRequestFromJSONTyped(json, false);
}

export function TypesChangePasswordRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesChangePasswordRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'current': json['current'],
        'new': json['new'],
    };
}

export function TypesChangePasswordRequestToJSON(json: any): TypesChangePasswordRequest {
    return TypesChangePasswordRequestToJSONTyped(json, false);
}

export function TypesChangePasswordRequestToJSONTyped(value?: TypesChangePasswordRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'current': value['current'],
        'new': value['new'],
    };
}

