/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TypesApplyPendingResponse } from './TypesApplyPendingResponse';
import {
    TypesApplyPendingResponseFromJSON,
    TypesApplyPendingResponseFromJSONTyped,
    TypesApplyPendingResponseToJSON,
    TypesApplyPendingResponseToJSONTyped,
} from './TypesApplyPendingResponse';

/**
 * 
 * @export
 * @interface TypesResponseTypesApplyPendingResponse
 */
export interface TypesResponseTypesApplyPendingResponse {
    /**
     * 
     * @type {number}
     * @memberof TypesResponseTypesApplyPendingResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof TypesResponseTypesApplyPendingResponse
     */
    error?: string;
    /**
     * 
     * @type {TypesApplyPendingResponse}
     * @memberof TypesResponseTypesApplyPendingResponse
     */
    result?: TypesApplyPendingResponse;
    /**
     * 
     * @type {string}
     * @memberof TypesResponseTypesApplyPendingResponse
     */
    status?: string;
}

/**
 * Check if a given object implements the TypesResponseTypesApplyPendingResponse interface.
 */
export function instanceOfTypesResponseTypesApplyPendingResponse(value: object): value is TypesResponseTypesApplyPendingResponse {
    return true;
}

export function TypesResponseTypesApplyPendingResponseFromJSON(json: any): TypesResponseTypesApplyPendingResponse {
    return TypesResponseTypesApplyPendingResponseFromJSONTyped(json, false);
}

export function TypesResponseTypesApplyPendingResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesResponseTypesApplyPendingResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'error': json['error'] == null ? undefined : json['error'],
        'result': json['result'] == null ? undefined : TypesApplyPendingResponseFromJSON(json['result']),
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function TypesResponseTypesApplyPendingResponseToJSON(json: any): TypesResponseTypesApplyPendingResponse {
    return TypesResponseTypesApplyPendingResponseToJSONTyped(json, false);
}

export function TypesResponseTypesApplyPendingResponseToJSONTyped(value?: TypesResponseTypesApplyPendingResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'error': value['error'],
        'result': TypesApplyPendingResponseToJSON(value['result']),
        'status': value['status'],
    };
}

