/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IptoolsSubnetInfo } from './IptoolsSubnetInfo';
import {
    IptoolsSubnetInfoFromJSON,
    IptoolsSubnetInfoFromJSONTyped,
    IptoolsSubnetInfoToJSON,
    IptoolsSubnetInfoToJSONTyped,
} from './IptoolsSubnetInfo';

/**
 * 
 * @export
 * @interface TypesResponseIptoolsSubnetInfo
 */
export interface TypesResponseIptoolsSubnetInfo {
    /**
     * 
     * @type {number}
     * @memberof TypesResponseIptoolsSubnetInfo
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof TypesResponseIptoolsSubnetInfo
     */
    error?: string;
    /**
     * 
     * @type {IptoolsSubnetInfo}
     * @memberof TypesResponseIptoolsSubnetInfo
     */
    result?: IptoolsSubnetInfo;
    /**
     * 
     * @type {string}
     * @memberof TypesResponseIptoolsSubnetInfo
     */
    status?: string;
}

/**
 * Check if a given object implements the TypesResponseIptoolsSubnetInfo interface.
 */
export function instanceOfTypesResponseIptoolsSubnetInfo(value: object): value is TypesResponseIptoolsSubnetInfo {
    return true;
}

export function TypesResponseIptoolsSubnetInfoFromJSON(json: any): TypesResponseIptoolsSubnetInfo {
    return TypesResponseIptoolsSubnetInfoFromJSONTyped(json, false);
}

export function TypesResponseIptoolsSubnetInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesResponseIptoolsSubnetInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'error': json['error'] == null ? undefined : json['error'],
        'result': json['result'] == null ? undefined : IptoolsSubnetInfoFromJSON(json['result']),
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function TypesResponseIptoolsSubnetInfoToJSON(json: any): TypesResponseIptoolsSubnetInfo {
    return TypesResponseIptoolsSubnetInfoToJSONTyped(json, false);
}

export function TypesResponseIptoolsSubnetInfoToJSONTyped(value?: TypesResponseIptoolsSubnetInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'error': value['error'],
        'result': IptoolsSubnetInfoToJSON(value['result']),
        'status': value['status'],
    };
}

