/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SystemInterfaceStatus } from './SystemInterfaceStatus';
import {
    SystemInterfaceStatusFromJSON,
    SystemInterfaceStatusFromJSONTyped,
    SystemInterfaceStatusToJSON,
    SystemInterfaceStatusToJSONTyped,
} from './SystemInterfaceStatus';

/**
 * 
 * @export
 * @interface TypesResponseSystemInterfaceStatus
 */
export interface TypesResponseSystemInterfaceStatus {
    /**
     * 
     * @type {number}
     * @memberof TypesResponseSystemInterfaceStatus
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof TypesResponseSystemInterfaceStatus
     */
    error?: string;
    /**
     * 
     * @type {SystemInterfaceStatus}
     * @memberof TypesResponseSystemInterfaceStatus
     */
    result?: SystemInterfaceStatus;
    /**
     * 
     * @type {string}
     * @memberof TypesResponseSystemInterfaceStatus
     */
    status?: string;
}

/**
 * Check if a given object implements the TypesResponseSystemInterfaceStatus interface.
 */
export function instanceOfTypesResponseSystemInterfaceStatus(value: object): value is TypesResponseSystemInterfaceStatus {
    return true;
}

export function TypesResponseSystemInterfaceStatusFromJSON(json: any): TypesResponseSystemInterfaceStatus {
    return TypesResponseSystemInterfaceStatusFromJSONTyped(json, false);
}

export function TypesResponseSystemInterfaceStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesResponseSystemInterfaceStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'error': json['error'] == null ? undefined : json['error'],
        'result': json['result'] == null ? undefined : SystemInterfaceStatusFromJSON(json['result']),
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function TypesResponseSystemInterfaceStatusToJSON(json: any): TypesResponseSystemInterfaceStatus {
    return TypesResponseSystemInterfaceStatusToJSONTyped(json, false);
}

export function TypesResponseSystemInterfaceStatusToJSONTyped(value?: TypesResponseSystemInterfaceStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'error': value['error'],
        'result': SystemInterfaceStatusToJSON(value['result']),
        'status': value['status'],
    };
}

