/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TypesResponseAny
 */
export interface TypesResponseAny {
    /**
     * 
     * @type {number}
     * @memberof TypesResponseAny
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof TypesResponseAny
     */
    error?: string;
    /**
     * 
     * @type {any}
     * @memberof TypesResponseAny
     */
    result?: any | null;
    /**
     * 
     * @type {string}
     * @memberof TypesResponseAny
     */
    status?: string;
}

/**
 * Check if a given object implements the TypesResponseAny interface.
 */
export function instanceOfTypesResponseAny(value: object): value is TypesResponseAny {
    return true;
}

export function TypesResponseAnyFromJSON(json: any): TypesResponseAny {
    return TypesResponseAnyFromJSONTyped(json, false);
}

export function TypesResponseAnyFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesResponseAny {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'error': json['error'] == null ? undefined : json['error'],
        'result': json['result'] == null ? undefined : json['result'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function TypesResponseAnyToJSON(json: any): TypesResponseAny {
    return TypesResponseAnyToJSONTyped(json, false);
}

export function TypesResponseAnyToJSONTyped(value?: TypesResponseAny | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'error': value['error'],
        'result': value['result'],
        'status': value['status'],
    };
}

