/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TypesWGEndpoint } from './TypesWGEndpoint';
import {
    TypesWGEndpointFromJSON,
    TypesWGEndpointFromJSONTyped,
    TypesWGEndpointToJSON,
    TypesWGEndpointToJSONTyped,
} from './TypesWGEndpoint';

/**
 * 
 * @export
 * @interface TypesDeriveTunnelRequest
 */
export interface TypesDeriveTunnelRequest {
    /**
     * 
     * @type {TypesWGEndpoint}
     * @memberof TypesDeriveTunnelRequest
     */
    friend_endpoint: TypesWGEndpoint;
    /**
     * 
     * @type {TypesWGEndpoint}
     * @memberof TypesDeriveTunnelRequest
     */
    local_endpoint: TypesWGEndpoint;
    /**
     * 
     * @type {string}
     * @memberof TypesDeriveTunnelRequest
     */
    mode: string;
    /**
     * 
     * @type {string}
     * @memberof TypesDeriveTunnelRequest
     */
    subnet: string;
}

/**
 * Check if a given object implements the TypesDeriveTunnelRequest interface.
 */
export function instanceOfTypesDeriveTunnelRequest(value: object): value is TypesDeriveTunnelRequest {
    if (!('friend_endpoint' in value) || value['friend_endpoint'] === undefined) return false;
    if (!('local_endpoint' in value) || value['local_endpoint'] === undefined) return false;
    if (!('mode' in value) || value['mode'] === undefined) return false;
    if (!('subnet' in value) || value['subnet'] === undefined) return false;
    return true;
}

export function TypesDeriveTunnelRequestFromJSON(json: any): TypesDeriveTunnelRequest {
    return TypesDeriveTunnelRequestFromJSONTyped(json, false);
}

export function TypesDeriveTunnelRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesDeriveTunnelRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'friend_endpoint': TypesWGEndpointFromJSON(json['friend_endpoint']),
        'local_endpoint': TypesWGEndpointFromJSON(json['local_endpoint']),
        'mode': json['mode'],
        'subnet': json['subnet'],
    };
}

export function TypesDeriveTunnelRequestToJSON(json: any): TypesDeriveTunnelRequest {
    return TypesDeriveTunnelRequestToJSONTyped(json, false);
}

export function TypesDeriveTunnelRequestToJSONTyped(value?: TypesDeriveTunnelRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'friend_endpoint': TypesWGEndpointToJSON(value['friend_endpoint']),
        'local_endpoint': TypesWGEndpointToJSON(value['local_endpoint']),
        'mode': value['mode'],
        'subnet': value['subnet'],
    };
}

