/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BindZoneView } from './BindZoneView';
import {
    BindZoneViewFromJSON,
    BindZoneViewFromJSONTyped,
    BindZoneViewToJSON,
    BindZoneViewToJSONTyped,
} from './BindZoneView';

/**
 * 
 * @export
 * @interface TypesResponseBindZoneView
 */
export interface TypesResponseBindZoneView {
    /**
     * 
     * @type {number}
     * @memberof TypesResponseBindZoneView
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof TypesResponseBindZoneView
     */
    error?: string;
    /**
     * 
     * @type {BindZoneView}
     * @memberof TypesResponseBindZoneView
     */
    result?: BindZoneView;
    /**
     * 
     * @type {string}
     * @memberof TypesResponseBindZoneView
     */
    status?: string;
}

/**
 * Check if a given object implements the TypesResponseBindZoneView interface.
 */
export function instanceOfTypesResponseBindZoneView(value: object): value is TypesResponseBindZoneView {
    return true;
}

export function TypesResponseBindZoneViewFromJSON(json: any): TypesResponseBindZoneView {
    return TypesResponseBindZoneViewFromJSONTyped(json, false);
}

export function TypesResponseBindZoneViewFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesResponseBindZoneView {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'error': json['error'] == null ? undefined : json['error'],
        'result': json['result'] == null ? undefined : BindZoneViewFromJSON(json['result']),
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function TypesResponseBindZoneViewToJSON(json: any): TypesResponseBindZoneView {
    return TypesResponseBindZoneViewToJSONTyped(json, false);
}

export function TypesResponseBindZoneViewToJSONTyped(value?: TypesResponseBindZoneView | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'error': value['error'],
        'result': BindZoneViewToJSON(value['result']),
        'status': value['status'],
    };
}

