/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TypesApplyLogRecord
 */
export interface TypesApplyLogRecord {
    /**
     * 
     * @type {string}
     * @memberof TypesApplyLogRecord
     */
    config_path?: string;
    /**
     * 
     * @type {string}
     * @memberof TypesApplyLogRecord
     */
    confirmed_at?: string;
    /**
     * 
     * @type {string}
     * @memberof TypesApplyLogRecord
     */
    finished_at?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TypesApplyLogRecord
     */
    has_bundle?: boolean;
    /**
     * 
     * @type {string}
     * @memberof TypesApplyLogRecord
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof TypesApplyLogRecord
     */
    result?: string;
    /**
     * 
     * @type {string}
     * @memberof TypesApplyLogRecord
     */
    rolledback_at?: string;
    /**
     * 
     * @type {string}
     * @memberof TypesApplyLogRecord
     */
    snap_id?: string;
    /**
     * 
     * @type {string}
     * @memberof TypesApplyLogRecord
     */
    source: string;
    /**
     * 
     * @type {string}
     * @memberof TypesApplyLogRecord
     */
    started_at: string;
}

/**
 * Check if a given object implements the TypesApplyLogRecord interface.
 */
export function instanceOfTypesApplyLogRecord(value: object): value is TypesApplyLogRecord {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('source' in value) || value['source'] === undefined) return false;
    if (!('started_at' in value) || value['started_at'] === undefined) return false;
    return true;
}

export function TypesApplyLogRecordFromJSON(json: any): TypesApplyLogRecord {
    return TypesApplyLogRecordFromJSONTyped(json, false);
}

export function TypesApplyLogRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesApplyLogRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'config_path': json['config_path'] == null ? undefined : json['config_path'],
        'confirmed_at': json['confirmed_at'] == null ? undefined : json['confirmed_at'],
        'finished_at': json['finished_at'] == null ? undefined : json['finished_at'],
        'has_bundle': json['has_bundle'] == null ? undefined : json['has_bundle'],
        'id': json['id'],
        'result': json['result'] == null ? undefined : json['result'],
        'rolledback_at': json['rolledback_at'] == null ? undefined : json['rolledback_at'],
        'snap_id': json['snap_id'] == null ? undefined : json['snap_id'],
        'source': json['source'],
        'started_at': json['started_at'],
    };
}

export function TypesApplyLogRecordToJSON(json: any): TypesApplyLogRecord {
    return TypesApplyLogRecordToJSONTyped(json, false);
}

export function TypesApplyLogRecordToJSONTyped(value?: TypesApplyLogRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'config_path': value['config_path'],
        'confirmed_at': value['confirmed_at'],
        'finished_at': value['finished_at'],
        'has_bundle': value['has_bundle'],
        'id': value['id'],
        'result': value['result'],
        'rolledback_at': value['rolledback_at'],
        'snap_id': value['snap_id'],
        'source': value['source'],
        'started_at': value['started_at'],
    };
}

