/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TypesSetupStatus } from './TypesSetupStatus';
import {
    TypesSetupStatusFromJSON,
    TypesSetupStatusFromJSONTyped,
    TypesSetupStatusToJSON,
    TypesSetupStatusToJSONTyped,
} from './TypesSetupStatus';

/**
 * 
 * @export
 * @interface TypesResponseTypesSetupStatus
 */
export interface TypesResponseTypesSetupStatus {
    /**
     * 
     * @type {number}
     * @memberof TypesResponseTypesSetupStatus
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof TypesResponseTypesSetupStatus
     */
    error?: string;
    /**
     * 
     * @type {TypesSetupStatus}
     * @memberof TypesResponseTypesSetupStatus
     */
    result?: TypesSetupStatus;
    /**
     * 
     * @type {string}
     * @memberof TypesResponseTypesSetupStatus
     */
    status?: string;
}

/**
 * Check if a given object implements the TypesResponseTypesSetupStatus interface.
 */
export function instanceOfTypesResponseTypesSetupStatus(value: object): value is TypesResponseTypesSetupStatus {
    return true;
}

export function TypesResponseTypesSetupStatusFromJSON(json: any): TypesResponseTypesSetupStatus {
    return TypesResponseTypesSetupStatusFromJSONTyped(json, false);
}

export function TypesResponseTypesSetupStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesResponseTypesSetupStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'error': json['error'] == null ? undefined : json['error'],
        'result': json['result'] == null ? undefined : TypesSetupStatusFromJSON(json['result']),
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function TypesResponseTypesSetupStatusToJSON(json: any): TypesResponseTypesSetupStatus {
    return TypesResponseTypesSetupStatusToJSONTyped(json, false);
}

export function TypesResponseTypesSetupStatusToJSONTyped(value?: TypesResponseTypesSetupStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'error': value['error'],
        'result': TypesSetupStatusToJSON(value['result']),
        'status': value['status'],
    };
}

