/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TypesIfaceHistoryPoint
 */
export interface TypesIfaceHistoryPoint {
    /**
     * 
     * @type {string}
     * @memberof TypesIfaceHistoryPoint
     */
    operstate: string;
    /**
     * 
     * @type {number}
     * @memberof TypesIfaceHistoryPoint
     */
    rx_bps: number;
    /**
     * 
     * @type {number}
     * @memberof TypesIfaceHistoryPoint
     */
    rx_bytes: number;
    /**
     * 
     * @type {number}
     * @memberof TypesIfaceHistoryPoint
     */
    rx_errs: number;
    /**
     * 
     * @type {number}
     * @memberof TypesIfaceHistoryPoint
     */
    rx_pkts: number;
    /**
     * 
     * @type {number}
     * @memberof TypesIfaceHistoryPoint
     */
    rx_pps: number;
    /**
     * 
     * @type {number}
     * @memberof TypesIfaceHistoryPoint
     */
    ts: number;
    /**
     * 
     * @type {number}
     * @memberof TypesIfaceHistoryPoint
     */
    tx_bps: number;
    /**
     * 
     * @type {number}
     * @memberof TypesIfaceHistoryPoint
     */
    tx_bytes: number;
    /**
     * 
     * @type {number}
     * @memberof TypesIfaceHistoryPoint
     */
    tx_errs: number;
    /**
     * 
     * @type {number}
     * @memberof TypesIfaceHistoryPoint
     */
    tx_pkts: number;
    /**
     * 
     * @type {number}
     * @memberof TypesIfaceHistoryPoint
     */
    tx_pps: number;
}

/**
 * Check if a given object implements the TypesIfaceHistoryPoint interface.
 */
export function instanceOfTypesIfaceHistoryPoint(value: object): value is TypesIfaceHistoryPoint {
    if (!('operstate' in value) || value['operstate'] === undefined) return false;
    if (!('rx_bps' in value) || value['rx_bps'] === undefined) return false;
    if (!('rx_bytes' in value) || value['rx_bytes'] === undefined) return false;
    if (!('rx_errs' in value) || value['rx_errs'] === undefined) return false;
    if (!('rx_pkts' in value) || value['rx_pkts'] === undefined) return false;
    if (!('rx_pps' in value) || value['rx_pps'] === undefined) return false;
    if (!('ts' in value) || value['ts'] === undefined) return false;
    if (!('tx_bps' in value) || value['tx_bps'] === undefined) return false;
    if (!('tx_bytes' in value) || value['tx_bytes'] === undefined) return false;
    if (!('tx_errs' in value) || value['tx_errs'] === undefined) return false;
    if (!('tx_pkts' in value) || value['tx_pkts'] === undefined) return false;
    if (!('tx_pps' in value) || value['tx_pps'] === undefined) return false;
    return true;
}

export function TypesIfaceHistoryPointFromJSON(json: any): TypesIfaceHistoryPoint {
    return TypesIfaceHistoryPointFromJSONTyped(json, false);
}

export function TypesIfaceHistoryPointFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesIfaceHistoryPoint {
    if (json == null) {
        return json;
    }
    return {
        
        'operstate': json['operstate'],
        'rx_bps': json['rx_bps'],
        'rx_bytes': json['rx_bytes'],
        'rx_errs': json['rx_errs'],
        'rx_pkts': json['rx_pkts'],
        'rx_pps': json['rx_pps'],
        'ts': json['ts'],
        'tx_bps': json['tx_bps'],
        'tx_bytes': json['tx_bytes'],
        'tx_errs': json['tx_errs'],
        'tx_pkts': json['tx_pkts'],
        'tx_pps': json['tx_pps'],
    };
}

export function TypesIfaceHistoryPointToJSON(json: any): TypesIfaceHistoryPoint {
    return TypesIfaceHistoryPointToJSONTyped(json, false);
}

export function TypesIfaceHistoryPointToJSONTyped(value?: TypesIfaceHistoryPoint | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'operstate': value['operstate'],
        'rx_bps': value['rx_bps'],
        'rx_bytes': value['rx_bytes'],
        'rx_errs': value['rx_errs'],
        'rx_pkts': value['rx_pkts'],
        'rx_pps': value['rx_pps'],
        'ts': value['ts'],
        'tx_bps': value['tx_bps'],
        'tx_bytes': value['tx_bytes'],
        'tx_errs': value['tx_errs'],
        'tx_pkts': value['tx_pkts'],
        'tx_pps': value['tx_pps'],
    };
}

