/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TypesIfaceStats
 */
export interface TypesIfaceStats {
    /**
     * 
     * @type {string}
     * @memberof TypesIfaceStats
     */
    operstate: string;
    /**
     * 
     * @type {number}
     * @memberof TypesIfaceStats
     */
    rx_bytes: number;
    /**
     * 
     * @type {number}
     * @memberof TypesIfaceStats
     */
    rx_errors: number;
    /**
     * 
     * @type {number}
     * @memberof TypesIfaceStats
     */
    rx_packets: number;
    /**
     * 
     * @type {number}
     * @memberof TypesIfaceStats
     */
    tx_bytes: number;
    /**
     * 
     * @type {number}
     * @memberof TypesIfaceStats
     */
    tx_errors: number;
    /**
     * 
     * @type {number}
     * @memberof TypesIfaceStats
     */
    tx_packets: number;
}

/**
 * Check if a given object implements the TypesIfaceStats interface.
 */
export function instanceOfTypesIfaceStats(value: object): value is TypesIfaceStats {
    if (!('operstate' in value) || value['operstate'] === undefined) return false;
    if (!('rx_bytes' in value) || value['rx_bytes'] === undefined) return false;
    if (!('rx_errors' in value) || value['rx_errors'] === undefined) return false;
    if (!('rx_packets' in value) || value['rx_packets'] === undefined) return false;
    if (!('tx_bytes' in value) || value['tx_bytes'] === undefined) return false;
    if (!('tx_errors' in value) || value['tx_errors'] === undefined) return false;
    if (!('tx_packets' in value) || value['tx_packets'] === undefined) return false;
    return true;
}

export function TypesIfaceStatsFromJSON(json: any): TypesIfaceStats {
    return TypesIfaceStatsFromJSONTyped(json, false);
}

export function TypesIfaceStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesIfaceStats {
    if (json == null) {
        return json;
    }
    return {
        
        'operstate': json['operstate'],
        'rx_bytes': json['rx_bytes'],
        'rx_errors': json['rx_errors'],
        'rx_packets': json['rx_packets'],
        'tx_bytes': json['tx_bytes'],
        'tx_errors': json['tx_errors'],
        'tx_packets': json['tx_packets'],
    };
}

export function TypesIfaceStatsToJSON(json: any): TypesIfaceStats {
    return TypesIfaceStatsToJSONTyped(json, false);
}

export function TypesIfaceStatsToJSONTyped(value?: TypesIfaceStats | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'operstate': value['operstate'],
        'rx_bytes': value['rx_bytes'],
        'rx_errors': value['rx_errors'],
        'rx_packets': value['rx_packets'],
        'tx_bytes': value['tx_bytes'],
        'tx_errors': value['tx_errors'],
        'tx_packets': value['tx_packets'],
    };
}

