/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TypesProcessInfo } from './TypesProcessInfo';
import {
    TypesProcessInfoFromJSON,
    TypesProcessInfoFromJSONTyped,
    TypesProcessInfoToJSON,
    TypesProcessInfoToJSONTyped,
} from './TypesProcessInfo';

/**
 * 
 * @export
 * @interface TypesProcessesResponse
 */
export interface TypesProcessesResponse {
    /**
     * 
     * @type {Array<TypesProcessInfo>}
     * @memberof TypesProcessesResponse
     */
    processes?: Array<TypesProcessInfo>;
}

/**
 * Check if a given object implements the TypesProcessesResponse interface.
 */
export function instanceOfTypesProcessesResponse(value: object): value is TypesProcessesResponse {
    return true;
}

export function TypesProcessesResponseFromJSON(json: any): TypesProcessesResponse {
    return TypesProcessesResponseFromJSONTyped(json, false);
}

export function TypesProcessesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesProcessesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'processes': json['processes'] == null ? undefined : ((json['processes'] as Array<any>).map(TypesProcessInfoFromJSON)),
    };
}

export function TypesProcessesResponseToJSON(json: any): TypesProcessesResponse {
    return TypesProcessesResponseToJSONTyped(json, false);
}

export function TypesProcessesResponseToJSONTyped(value?: TypesProcessesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'processes': value['processes'] == null ? undefined : ((value['processes'] as Array<any>).map(TypesProcessInfoToJSON)),
    };
}

