/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DnsOverviewResponse } from './DnsOverviewResponse';
import {
    DnsOverviewResponseFromJSON,
    DnsOverviewResponseFromJSONTyped,
    DnsOverviewResponseToJSON,
    DnsOverviewResponseToJSONTyped,
} from './DnsOverviewResponse';

/**
 * 
 * @export
 * @interface TypesResponseDnsOverviewResponse
 */
export interface TypesResponseDnsOverviewResponse {
    /**
     * 
     * @type {number}
     * @memberof TypesResponseDnsOverviewResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof TypesResponseDnsOverviewResponse
     */
    error?: string;
    /**
     * 
     * @type {DnsOverviewResponse}
     * @memberof TypesResponseDnsOverviewResponse
     */
    result?: DnsOverviewResponse;
    /**
     * 
     * @type {string}
     * @memberof TypesResponseDnsOverviewResponse
     */
    status?: string;
}

/**
 * Check if a given object implements the TypesResponseDnsOverviewResponse interface.
 */
export function instanceOfTypesResponseDnsOverviewResponse(value: object): value is TypesResponseDnsOverviewResponse {
    return true;
}

export function TypesResponseDnsOverviewResponseFromJSON(json: any): TypesResponseDnsOverviewResponse {
    return TypesResponseDnsOverviewResponseFromJSONTyped(json, false);
}

export function TypesResponseDnsOverviewResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesResponseDnsOverviewResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'error': json['error'] == null ? undefined : json['error'],
        'result': json['result'] == null ? undefined : DnsOverviewResponseFromJSON(json['result']),
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function TypesResponseDnsOverviewResponseToJSON(json: any): TypesResponseDnsOverviewResponse {
    return TypesResponseDnsOverviewResponseToJSONTyped(json, false);
}

export function TypesResponseDnsOverviewResponseToJSONTyped(value?: TypesResponseDnsOverviewResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'error': value['error'],
        'result': DnsOverviewResponseToJSON(value['result']),
        'status': value['status'],
    };
}

