/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TypesConfigureConntrackRequest
 */
export interface TypesConfigureConntrackRequest {
    /**
     * 
     * @type {boolean}
     * @memberof TypesConfigureConntrackRequest
     */
    allow_inbound?: boolean;
    /**
     * 
     * @type {string}
     * @memberof TypesConfigureConntrackRequest
     */
    friend_address: string;
    /**
     * 
     * @type {string}
     * @memberof TypesConfigureConntrackRequest
     */
    friend_interface: string;
    /**
     * 
     * @type {string}
     * @memberof TypesConfigureConntrackRequest
     */
    local_address: string;
    /**
     * 
     * @type {string}
     * @memberof TypesConfigureConntrackRequest
     */
    local_interface: string;
    /**
     * 
     * @type {number}
     * @memberof TypesConfigureConntrackRequest
     */
    port?: number;
}

/**
 * Check if a given object implements the TypesConfigureConntrackRequest interface.
 */
export function instanceOfTypesConfigureConntrackRequest(value: object): value is TypesConfigureConntrackRequest {
    if (!('friend_address' in value) || value['friend_address'] === undefined) return false;
    if (!('friend_interface' in value) || value['friend_interface'] === undefined) return false;
    if (!('local_address' in value) || value['local_address'] === undefined) return false;
    if (!('local_interface' in value) || value['local_interface'] === undefined) return false;
    return true;
}

export function TypesConfigureConntrackRequestFromJSON(json: any): TypesConfigureConntrackRequest {
    return TypesConfigureConntrackRequestFromJSONTyped(json, false);
}

export function TypesConfigureConntrackRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesConfigureConntrackRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'allow_inbound': json['allow_inbound'] == null ? undefined : json['allow_inbound'],
        'friend_address': json['friend_address'],
        'friend_interface': json['friend_interface'],
        'local_address': json['local_address'],
        'local_interface': json['local_interface'],
        'port': json['port'] == null ? undefined : json['port'],
    };
}

export function TypesConfigureConntrackRequestToJSON(json: any): TypesConfigureConntrackRequest {
    return TypesConfigureConntrackRequestToJSONTyped(json, false);
}

export function TypesConfigureConntrackRequestToJSONTyped(value?: TypesConfigureConntrackRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'allow_inbound': value['allow_inbound'],
        'friend_address': value['friend_address'],
        'friend_interface': value['friend_interface'],
        'local_address': value['local_address'],
        'local_interface': value['local_interface'],
        'port': value['port'],
    };
}

