/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TypesArtifactContent } from './TypesArtifactContent';
import {
    TypesArtifactContentFromJSON,
    TypesArtifactContentFromJSONTyped,
    TypesArtifactContentToJSON,
    TypesArtifactContentToJSONTyped,
} from './TypesArtifactContent';

/**
 * 
 * @export
 * @interface TypesResponseTypesArtifactContent
 */
export interface TypesResponseTypesArtifactContent {
    /**
     * 
     * @type {number}
     * @memberof TypesResponseTypesArtifactContent
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof TypesResponseTypesArtifactContent
     */
    error?: string;
    /**
     * 
     * @type {TypesArtifactContent}
     * @memberof TypesResponseTypesArtifactContent
     */
    result?: TypesArtifactContent;
    /**
     * 
     * @type {string}
     * @memberof TypesResponseTypesArtifactContent
     */
    status?: string;
}

/**
 * Check if a given object implements the TypesResponseTypesArtifactContent interface.
 */
export function instanceOfTypesResponseTypesArtifactContent(value: object): value is TypesResponseTypesArtifactContent {
    return true;
}

export function TypesResponseTypesArtifactContentFromJSON(json: any): TypesResponseTypesArtifactContent {
    return TypesResponseTypesArtifactContentFromJSONTyped(json, false);
}

export function TypesResponseTypesArtifactContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesResponseTypesArtifactContent {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'error': json['error'] == null ? undefined : json['error'],
        'result': json['result'] == null ? undefined : TypesArtifactContentFromJSON(json['result']),
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function TypesResponseTypesArtifactContentToJSON(json: any): TypesResponseTypesArtifactContent {
    return TypesResponseTypesArtifactContentToJSONTyped(json, false);
}

export function TypesResponseTypesArtifactContentToJSONTyped(value?: TypesResponseTypesArtifactContent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'error': value['error'],
        'result': TypesArtifactContentToJSON(value['result']),
        'status': value['status'],
    };
}

