/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TypesLLDPNeighborsResponse } from './TypesLLDPNeighborsResponse';
import {
    TypesLLDPNeighborsResponseFromJSON,
    TypesLLDPNeighborsResponseFromJSONTyped,
    TypesLLDPNeighborsResponseToJSON,
    TypesLLDPNeighborsResponseToJSONTyped,
} from './TypesLLDPNeighborsResponse';

/**
 * 
 * @export
 * @interface TypesResponseTypesLLDPNeighborsResponse
 */
export interface TypesResponseTypesLLDPNeighborsResponse {
    /**
     * 
     * @type {number}
     * @memberof TypesResponseTypesLLDPNeighborsResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof TypesResponseTypesLLDPNeighborsResponse
     */
    error?: string;
    /**
     * 
     * @type {TypesLLDPNeighborsResponse}
     * @memberof TypesResponseTypesLLDPNeighborsResponse
     */
    result?: TypesLLDPNeighborsResponse;
    /**
     * 
     * @type {string}
     * @memberof TypesResponseTypesLLDPNeighborsResponse
     */
    status?: string;
}

/**
 * Check if a given object implements the TypesResponseTypesLLDPNeighborsResponse interface.
 */
export function instanceOfTypesResponseTypesLLDPNeighborsResponse(value: object): value is TypesResponseTypesLLDPNeighborsResponse {
    return true;
}

export function TypesResponseTypesLLDPNeighborsResponseFromJSON(json: any): TypesResponseTypesLLDPNeighborsResponse {
    return TypesResponseTypesLLDPNeighborsResponseFromJSONTyped(json, false);
}

export function TypesResponseTypesLLDPNeighborsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesResponseTypesLLDPNeighborsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'error': json['error'] == null ? undefined : json['error'],
        'result': json['result'] == null ? undefined : TypesLLDPNeighborsResponseFromJSON(json['result']),
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function TypesResponseTypesLLDPNeighborsResponseToJSON(json: any): TypesResponseTypesLLDPNeighborsResponse {
    return TypesResponseTypesLLDPNeighborsResponseToJSONTyped(json, false);
}

export function TypesResponseTypesLLDPNeighborsResponseToJSONTyped(value?: TypesResponseTypesLLDPNeighborsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'error': value['error'],
        'result': TypesLLDPNeighborsResponseToJSON(value['result']),
        'status': value['status'],
    };
}

