/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TypesOSPFNeighborSummary } from './TypesOSPFNeighborSummary';
import {
    TypesOSPFNeighborSummaryFromJSON,
    TypesOSPFNeighborSummaryFromJSONTyped,
    TypesOSPFNeighborSummaryToJSON,
    TypesOSPFNeighborSummaryToJSONTyped,
} from './TypesOSPFNeighborSummary';

/**
 * 
 * @export
 * @interface TypesOSPFStats
 */
export interface TypesOSPFStats {
    /**
     * 
     * @type {Array<TypesOSPFNeighborSummary>}
     * @memberof TypesOSPFStats
     */
    neighbors?: Array<TypesOSPFNeighborSummary>;
    /**
     * 
     * @type {string}
     * @memberof TypesOSPFStats
     */
    router_id: string;
}

/**
 * Check if a given object implements the TypesOSPFStats interface.
 */
export function instanceOfTypesOSPFStats(value: object): value is TypesOSPFStats {
    if (!('router_id' in value) || value['router_id'] === undefined) return false;
    return true;
}

export function TypesOSPFStatsFromJSON(json: any): TypesOSPFStats {
    return TypesOSPFStatsFromJSONTyped(json, false);
}

export function TypesOSPFStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesOSPFStats {
    if (json == null) {
        return json;
    }
    return {
        
        'neighbors': json['neighbors'] == null ? undefined : ((json['neighbors'] as Array<any>).map(TypesOSPFNeighborSummaryFromJSON)),
        'router_id': json['router_id'],
    };
}

export function TypesOSPFStatsToJSON(json: any): TypesOSPFStats {
    return TypesOSPFStatsToJSONTyped(json, false);
}

export function TypesOSPFStatsToJSONTyped(value?: TypesOSPFStats | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'neighbors': value['neighbors'] == null ? undefined : ((value['neighbors'] as Array<any>).map(TypesOSPFNeighborSummaryToJSON)),
        'router_id': value['router_id'],
    };
}

