/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TypesFriendPreview
 */
export interface TypesFriendPreview {
    /**
     * 
     * @type {boolean}
     * @memberof TypesFriendPreview
     */
    already_exists: boolean;
    /**
     * 
     * @type {string}
     * @memberof TypesFriendPreview
     */
    error?: string;
    /**
     * 
     * @type {string}
     * @memberof TypesFriendPreview
     */
    hostname?: string;
    /**
     * 
     * @type {string}
     * @memberof TypesFriendPreview
     */
    identity_fingerprint?: string;
    /**
     * 
     * @type {string}
     * @memberof TypesFriendPreview
     */
    identity_public_key?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TypesFriendPreview
     */
    is_self: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof TypesFriendPreview
     */
    reachable: boolean;
    /**
     * 
     * @type {string}
     * @memberof TypesFriendPreview
     */
    version?: string;
}

/**
 * Check if a given object implements the TypesFriendPreview interface.
 */
export function instanceOfTypesFriendPreview(value: object): value is TypesFriendPreview {
    if (!('already_exists' in value) || value['already_exists'] === undefined) return false;
    if (!('is_self' in value) || value['is_self'] === undefined) return false;
    if (!('reachable' in value) || value['reachable'] === undefined) return false;
    return true;
}

export function TypesFriendPreviewFromJSON(json: any): TypesFriendPreview {
    return TypesFriendPreviewFromJSONTyped(json, false);
}

export function TypesFriendPreviewFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesFriendPreview {
    if (json == null) {
        return json;
    }
    return {
        
        'already_exists': json['already_exists'],
        'error': json['error'] == null ? undefined : json['error'],
        'hostname': json['hostname'] == null ? undefined : json['hostname'],
        'identity_fingerprint': json['identity_fingerprint'] == null ? undefined : json['identity_fingerprint'],
        'identity_public_key': json['identity_public_key'] == null ? undefined : json['identity_public_key'],
        'is_self': json['is_self'],
        'reachable': json['reachable'],
        'version': json['version'] == null ? undefined : json['version'],
    };
}

export function TypesFriendPreviewToJSON(json: any): TypesFriendPreview {
    return TypesFriendPreviewToJSONTyped(json, false);
}

export function TypesFriendPreviewToJSONTyped(value?: TypesFriendPreview | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'already_exists': value['already_exists'],
        'error': value['error'],
        'hostname': value['hostname'],
        'identity_fingerprint': value['identity_fingerprint'],
        'identity_public_key': value['identity_public_key'],
        'is_self': value['is_self'],
        'reachable': value['reachable'],
        'version': value['version'],
    };
}

