/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TypesSystemNic } from './TypesSystemNic';
import {
    TypesSystemNicFromJSON,
    TypesSystemNicFromJSONTyped,
    TypesSystemNicToJSON,
    TypesSystemNicToJSONTyped,
} from './TypesSystemNic';

/**
 * 
 * @export
 * @interface TypesResponseArrayTypesSystemNic
 */
export interface TypesResponseArrayTypesSystemNic {
    /**
     * 
     * @type {number}
     * @memberof TypesResponseArrayTypesSystemNic
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof TypesResponseArrayTypesSystemNic
     */
    error?: string;
    /**
     * 
     * @type {Array<TypesSystemNic>}
     * @memberof TypesResponseArrayTypesSystemNic
     */
    result?: Array<TypesSystemNic>;
    /**
     * 
     * @type {string}
     * @memberof TypesResponseArrayTypesSystemNic
     */
    status?: string;
}

/**
 * Check if a given object implements the TypesResponseArrayTypesSystemNic interface.
 */
export function instanceOfTypesResponseArrayTypesSystemNic(value: object): value is TypesResponseArrayTypesSystemNic {
    return true;
}

export function TypesResponseArrayTypesSystemNicFromJSON(json: any): TypesResponseArrayTypesSystemNic {
    return TypesResponseArrayTypesSystemNicFromJSONTyped(json, false);
}

export function TypesResponseArrayTypesSystemNicFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesResponseArrayTypesSystemNic {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'error': json['error'] == null ? undefined : json['error'],
        'result': json['result'] == null ? undefined : ((json['result'] as Array<any>).map(TypesSystemNicFromJSON)),
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function TypesResponseArrayTypesSystemNicToJSON(json: any): TypesResponseArrayTypesSystemNic {
    return TypesResponseArrayTypesSystemNicToJSONTyped(json, false);
}

export function TypesResponseArrayTypesSystemNicToJSONTyped(value?: TypesResponseArrayTypesSystemNic | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'error': value['error'],
        'result': value['result'] == null ? undefined : ((value['result'] as Array<any>).map(TypesSystemNicToJSON)),
        'status': value['status'],
    };
}

