/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TypesMacroApplyRequest
 */
export interface TypesMacroApplyRequest {
    /**
     * 
     * @type {boolean}
     * @memberof TypesMacroApplyRequest
     */
    force: boolean;
}

/**
 * Check if a given object implements the TypesMacroApplyRequest interface.
 */
export function instanceOfTypesMacroApplyRequest(value: object): value is TypesMacroApplyRequest {
    if (!('force' in value) || value['force'] === undefined) return false;
    return true;
}

export function TypesMacroApplyRequestFromJSON(json: any): TypesMacroApplyRequest {
    return TypesMacroApplyRequestFromJSONTyped(json, false);
}

export function TypesMacroApplyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesMacroApplyRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'force': json['force'],
    };
}

export function TypesMacroApplyRequestToJSON(json: any): TypesMacroApplyRequest {
    return TypesMacroApplyRequestToJSONTyped(json, false);
}

export function TypesMacroApplyRequestToJSONTyped(value?: TypesMacroApplyRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'force': value['force'],
    };
}

