/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IpcalcRangeCIDRs } from './IpcalcRangeCIDRs';
import {
    IpcalcRangeCIDRsFromJSON,
    IpcalcRangeCIDRsFromJSONTyped,
    IpcalcRangeCIDRsToJSON,
    IpcalcRangeCIDRsToJSONTyped,
} from './IpcalcRangeCIDRs';

/**
 * 
 * @export
 * @interface TypesResponseIpcalcRangeCIDRs
 */
export interface TypesResponseIpcalcRangeCIDRs {
    /**
     * 
     * @type {number}
     * @memberof TypesResponseIpcalcRangeCIDRs
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof TypesResponseIpcalcRangeCIDRs
     */
    error?: string;
    /**
     * 
     * @type {IpcalcRangeCIDRs}
     * @memberof TypesResponseIpcalcRangeCIDRs
     */
    result?: IpcalcRangeCIDRs;
    /**
     * 
     * @type {string}
     * @memberof TypesResponseIpcalcRangeCIDRs
     */
    status?: string;
}

/**
 * Check if a given object implements the TypesResponseIpcalcRangeCIDRs interface.
 */
export function instanceOfTypesResponseIpcalcRangeCIDRs(value: object): value is TypesResponseIpcalcRangeCIDRs {
    return true;
}

export function TypesResponseIpcalcRangeCIDRsFromJSON(json: any): TypesResponseIpcalcRangeCIDRs {
    return TypesResponseIpcalcRangeCIDRsFromJSONTyped(json, false);
}

export function TypesResponseIpcalcRangeCIDRsFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesResponseIpcalcRangeCIDRs {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'error': json['error'] == null ? undefined : json['error'],
        'result': json['result'] == null ? undefined : IpcalcRangeCIDRsFromJSON(json['result']),
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function TypesResponseIpcalcRangeCIDRsToJSON(json: any): TypesResponseIpcalcRangeCIDRs {
    return TypesResponseIpcalcRangeCIDRsToJSONTyped(json, false);
}

export function TypesResponseIpcalcRangeCIDRsToJSONTyped(value?: TypesResponseIpcalcRangeCIDRs | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'error': value['error'],
        'result': IpcalcRangeCIDRsToJSON(value['result']),
        'status': value['status'],
    };
}

