/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TypesAPIKey } from './TypesAPIKey';
import {
    TypesAPIKeyFromJSON,
    TypesAPIKeyFromJSONTyped,
    TypesAPIKeyToJSON,
    TypesAPIKeyToJSONTyped,
} from './TypesAPIKey';

/**
 * 
 * @export
 * @interface TypesCreateAPIKeyResponse
 */
export interface TypesCreateAPIKeyResponse {
    /**
     * 
     * @type {TypesAPIKey}
     * @memberof TypesCreateAPIKeyResponse
     */
    api_key: TypesAPIKey;
    /**
     * 
     * @type {string}
     * @memberof TypesCreateAPIKeyResponse
     */
    token: string;
}

/**
 * Check if a given object implements the TypesCreateAPIKeyResponse interface.
 */
export function instanceOfTypesCreateAPIKeyResponse(value: object): value is TypesCreateAPIKeyResponse {
    if (!('api_key' in value) || value['api_key'] === undefined) return false;
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function TypesCreateAPIKeyResponseFromJSON(json: any): TypesCreateAPIKeyResponse {
    return TypesCreateAPIKeyResponseFromJSONTyped(json, false);
}

export function TypesCreateAPIKeyResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesCreateAPIKeyResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'api_key': TypesAPIKeyFromJSON(json['api_key']),
        'token': json['token'],
    };
}

export function TypesCreateAPIKeyResponseToJSON(json: any): TypesCreateAPIKeyResponse {
    return TypesCreateAPIKeyResponseToJSONTyped(json, false);
}

export function TypesCreateAPIKeyResponseToJSONTyped(value?: TypesCreateAPIKeyResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'api_key': TypesAPIKeyToJSON(value['api_key']),
        'token': value['token'],
    };
}

