/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TypesFriendPairRequest
 */
export interface TypesFriendPairRequest {
    /**
     * 
     * @type {string}
     * @memberof TypesFriendPairRequest
     */
    hostname: string;
    /**
     * 
     * @type {string}
     * @memberof TypesFriendPairRequest
     */
    identity_fingerprint: string;
    /**
     * 
     * @type {string}
     * @memberof TypesFriendPairRequest
     */
    identity_public_key: string;
    /**
     * 
     * @type {number}
     * @memberof TypesFriendPairRequest
     */
    port?: number;
    /**
     * 
     * @type {string}
     * @memberof TypesFriendPairRequest
     */
    scheme?: TypesFriendPairRequestSchemeEnum;
    /**
     * 
     * @type {string}
     * @memberof TypesFriendPairRequest
     */
    signature: string;
    /**
     * 
     * @type {string}
     * @memberof TypesFriendPairRequest
     */
    x25519_public_key?: string;
}


/**
 * @export
 */
export const TypesFriendPairRequestSchemeEnum = {
    Http: 'http',
    Https: 'https'
} as const;
export type TypesFriendPairRequestSchemeEnum = typeof TypesFriendPairRequestSchemeEnum[keyof typeof TypesFriendPairRequestSchemeEnum];


/**
 * Check if a given object implements the TypesFriendPairRequest interface.
 */
export function instanceOfTypesFriendPairRequest(value: object): value is TypesFriendPairRequest {
    if (!('hostname' in value) || value['hostname'] === undefined) return false;
    if (!('identity_fingerprint' in value) || value['identity_fingerprint'] === undefined) return false;
    if (!('identity_public_key' in value) || value['identity_public_key'] === undefined) return false;
    if (!('signature' in value) || value['signature'] === undefined) return false;
    return true;
}

export function TypesFriendPairRequestFromJSON(json: any): TypesFriendPairRequest {
    return TypesFriendPairRequestFromJSONTyped(json, false);
}

export function TypesFriendPairRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesFriendPairRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'hostname': json['hostname'],
        'identity_fingerprint': json['identity_fingerprint'],
        'identity_public_key': json['identity_public_key'],
        'port': json['port'] == null ? undefined : json['port'],
        'scheme': json['scheme'] == null ? undefined : json['scheme'],
        'signature': json['signature'],
        'x25519_public_key': json['x25519_public_key'] == null ? undefined : json['x25519_public_key'],
    };
}

export function TypesFriendPairRequestToJSON(json: any): TypesFriendPairRequest {
    return TypesFriendPairRequestToJSONTyped(json, false);
}

export function TypesFriendPairRequestToJSONTyped(value?: TypesFriendPairRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'hostname': value['hostname'],
        'identity_fingerprint': value['identity_fingerprint'],
        'identity_public_key': value['identity_public_key'],
        'port': value['port'],
        'scheme': value['scheme'],
        'signature': value['signature'],
        'x25519_public_key': value['x25519_public_key'],
    };
}

