/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TypesFriendsHello } from './TypesFriendsHello';
import {
    TypesFriendsHelloFromJSON,
    TypesFriendsHelloFromJSONTyped,
    TypesFriendsHelloToJSON,
    TypesFriendsHelloToJSONTyped,
} from './TypesFriendsHello';
import type { TypesFriendVar } from './TypesFriendVar';
import {
    TypesFriendVarFromJSON,
    TypesFriendVarFromJSONTyped,
    TypesFriendVarToJSON,
    TypesFriendVarToJSONTyped,
} from './TypesFriendVar';
import type { TypesFriendInterface } from './TypesFriendInterface';
import {
    TypesFriendInterfaceFromJSON,
    TypesFriendInterfaceFromJSONTyped,
    TypesFriendInterfaceToJSON,
    TypesFriendInterfaceToJSONTyped,
} from './TypesFriendInterface';

/**
 * 
 * @export
 * @interface TypesFriendPoll
 */
export interface TypesFriendPoll {
    /**
     * 
     * @type {Array<number>}
     * @memberof TypesFriendPoll
     */
    config?: Array<number>;
    /**
     * 
     * @type {string}
     * @memberof TypesFriendPoll
     */
    config_hash: string;
    /**
     * 
     * @type {Array<TypesFriendVar>}
     * @memberof TypesFriendPoll
     */
    exports?: Array<TypesFriendVar>;
    /**
     * 
     * @type {TypesFriendsHello}
     * @memberof TypesFriendPoll
     */
    hello: TypesFriendsHello;
    /**
     * 
     * @type {Array<TypesFriendInterface>}
     * @memberof TypesFriendPoll
     */
    interfaces?: Array<TypesFriendInterface>;
}

/**
 * Check if a given object implements the TypesFriendPoll interface.
 */
export function instanceOfTypesFriendPoll(value: object): value is TypesFriendPoll {
    if (!('config_hash' in value) || value['config_hash'] === undefined) return false;
    if (!('hello' in value) || value['hello'] === undefined) return false;
    return true;
}

export function TypesFriendPollFromJSON(json: any): TypesFriendPoll {
    return TypesFriendPollFromJSONTyped(json, false);
}

export function TypesFriendPollFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesFriendPoll {
    if (json == null) {
        return json;
    }
    return {
        
        'config': json['config'] == null ? undefined : json['config'],
        'config_hash': json['config_hash'],
        'exports': json['exports'] == null ? undefined : ((json['exports'] as Array<any>).map(TypesFriendVarFromJSON)),
        'hello': TypesFriendsHelloFromJSON(json['hello']),
        'interfaces': json['interfaces'] == null ? undefined : ((json['interfaces'] as Array<any>).map(TypesFriendInterfaceFromJSON)),
    };
}

export function TypesFriendPollToJSON(json: any): TypesFriendPoll {
    return TypesFriendPollToJSONTyped(json, false);
}

export function TypesFriendPollToJSONTyped(value?: TypesFriendPoll | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'config': value['config'],
        'config_hash': value['config_hash'],
        'exports': value['exports'] == null ? undefined : ((value['exports'] as Array<any>).map(TypesFriendVarToJSON)),
        'hello': TypesFriendsHelloToJSON(value['hello']),
        'interfaces': value['interfaces'] == null ? undefined : ((value['interfaces'] as Array<any>).map(TypesFriendInterfaceToJSON)),
    };
}

