/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TypesFriendVar
 */
export interface TypesFriendVar {
    /**
     * 
     * @type {string}
     * @memberof TypesFriendVar
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof TypesFriendVar
     */
    value: string;
}

/**
 * Check if a given object implements the TypesFriendVar interface.
 */
export function instanceOfTypesFriendVar(value: object): value is TypesFriendVar {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function TypesFriendVarFromJSON(json: any): TypesFriendVar {
    return TypesFriendVarFromJSONTyped(json, false);
}

export function TypesFriendVarFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesFriendVar {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'value': json['value'],
    };
}

export function TypesFriendVarToJSON(json: any): TypesFriendVar {
    return TypesFriendVarToJSONTyped(json, false);
}

export function TypesFriendVarToJSONTyped(value?: TypesFriendVar | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'value': value['value'],
    };
}

