/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TypesPasswordHashResponse
 */
export interface TypesPasswordHashResponse {
    /**
     * 
     * @type {string}
     * @memberof TypesPasswordHashResponse
     */
    hash: string;
}

/**
 * Check if a given object implements the TypesPasswordHashResponse interface.
 */
export function instanceOfTypesPasswordHashResponse(value: object): value is TypesPasswordHashResponse {
    if (!('hash' in value) || value['hash'] === undefined) return false;
    return true;
}

export function TypesPasswordHashResponseFromJSON(json: any): TypesPasswordHashResponse {
    return TypesPasswordHashResponseFromJSONTyped(json, false);
}

export function TypesPasswordHashResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesPasswordHashResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'hash': json['hash'],
    };
}

export function TypesPasswordHashResponseToJSON(json: any): TypesPasswordHashResponse {
    return TypesPasswordHashResponseToJSONTyped(json, false);
}

export function TypesPasswordHashResponseToJSONTyped(value?: TypesPasswordHashResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'hash': value['hash'],
    };
}

