/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TypesSnapshotInfo
 */
export interface TypesSnapshotInfo {
    /**
     * 
     * @type {Array<string>}
     * @memberof TypesSnapshotInfo
     */
    files?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof TypesSnapshotInfo
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof TypesSnapshotInfo
     */
    time: string;
}

/**
 * Check if a given object implements the TypesSnapshotInfo interface.
 */
export function instanceOfTypesSnapshotInfo(value: object): value is TypesSnapshotInfo {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('time' in value) || value['time'] === undefined) return false;
    return true;
}

export function TypesSnapshotInfoFromJSON(json: any): TypesSnapshotInfo {
    return TypesSnapshotInfoFromJSONTyped(json, false);
}

export function TypesSnapshotInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesSnapshotInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'files': json['files'] == null ? undefined : json['files'],
        'id': json['id'],
        'time': json['time'],
    };
}

export function TypesSnapshotInfoToJSON(json: any): TypesSnapshotInfo {
    return TypesSnapshotInfoToJSONTyped(json, false);
}

export function TypesSnapshotInfoToJSONTyped(value?: TypesSnapshotInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'files': value['files'],
        'id': value['id'],
        'time': value['time'],
    };
}

