/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TypesProtoHistoryPoint } from './TypesProtoHistoryPoint';
import {
    TypesProtoHistoryPointFromJSON,
    TypesProtoHistoryPointFromJSONTyped,
    TypesProtoHistoryPointToJSON,
    TypesProtoHistoryPointToJSONTyped,
} from './TypesProtoHistoryPoint';
import type { TypesSystemHistoryPoint } from './TypesSystemHistoryPoint';
import {
    TypesSystemHistoryPointFromJSON,
    TypesSystemHistoryPointFromJSONTyped,
    TypesSystemHistoryPointToJSON,
    TypesSystemHistoryPointToJSONTyped,
} from './TypesSystemHistoryPoint';
import type { TypesBGPHistoryPoint } from './TypesBGPHistoryPoint';
import {
    TypesBGPHistoryPointFromJSON,
    TypesBGPHistoryPointFromJSONTyped,
    TypesBGPHistoryPointToJSON,
    TypesBGPHistoryPointToJSONTyped,
} from './TypesBGPHistoryPoint';
import type { TypesUsageSummary } from './TypesUsageSummary';
import {
    TypesUsageSummaryFromJSON,
    TypesUsageSummaryFromJSONTyped,
    TypesUsageSummaryToJSON,
    TypesUsageSummaryToJSONTyped,
} from './TypesUsageSummary';
import type { TypesIfaceTotalPoint } from './TypesIfaceTotalPoint';
import {
    TypesIfaceTotalPointFromJSON,
    TypesIfaceTotalPointFromJSONTyped,
    TypesIfaceTotalPointToJSON,
    TypesIfaceTotalPointToJSONTyped,
} from './TypesIfaceTotalPoint';
import type { TypesIfaceHistoryPoint } from './TypesIfaceHistoryPoint';
import {
    TypesIfaceHistoryPointFromJSON,
    TypesIfaceHistoryPointFromJSONTyped,
    TypesIfaceHistoryPointToJSON,
    TypesIfaceHistoryPointToJSONTyped,
} from './TypesIfaceHistoryPoint';

/**
 * 
 * @export
 * @interface TypesStatsHistoryResponse
 */
export interface TypesStatsHistoryResponse {
    /**
     * 
     * @type {{ [key: string]: Array<TypesBGPHistoryPoint>; }}
     * @memberof TypesStatsHistoryResponse
     */
    bgp_peers?: { [key: string]: Array<TypesBGPHistoryPoint>; };
    /**
     * 
     * @type {{ [key: string]: Array<TypesIfaceHistoryPoint>; }}
     * @memberof TypesStatsHistoryResponse
     */
    interfaces?: { [key: string]: Array<TypesIfaceHistoryPoint>; };
    /**
     * 
     * @type {Array<TypesProtoHistoryPoint>}
     * @memberof TypesStatsHistoryResponse
     */
    proto?: Array<TypesProtoHistoryPoint>;
    /**
     * 
     * @type {Array<TypesSystemHistoryPoint>}
     * @memberof TypesStatsHistoryResponse
     */
    system?: Array<TypesSystemHistoryPoint>;
    /**
     * 
     * @type {Array<TypesIfaceTotalPoint>}
     * @memberof TypesStatsHistoryResponse
     */
    total?: Array<TypesIfaceTotalPoint>;
    /**
     * 
     * @type {TypesUsageSummary}
     * @memberof TypesStatsHistoryResponse
     */
    usage?: TypesUsageSummary;
}

/**
 * Check if a given object implements the TypesStatsHistoryResponse interface.
 */
export function instanceOfTypesStatsHistoryResponse(value: object): value is TypesStatsHistoryResponse {
    return true;
}

export function TypesStatsHistoryResponseFromJSON(json: any): TypesStatsHistoryResponse {
    return TypesStatsHistoryResponseFromJSONTyped(json, false);
}

export function TypesStatsHistoryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesStatsHistoryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'bgp_peers': json['bgp_peers'] == null ? undefined : json['bgp_peers'],
        'interfaces': json['interfaces'] == null ? undefined : json['interfaces'],
        'proto': json['proto'] == null ? undefined : ((json['proto'] as Array<any>).map(TypesProtoHistoryPointFromJSON)),
        'system': json['system'] == null ? undefined : ((json['system'] as Array<any>).map(TypesSystemHistoryPointFromJSON)),
        'total': json['total'] == null ? undefined : ((json['total'] as Array<any>).map(TypesIfaceTotalPointFromJSON)),
        'usage': json['usage'] == null ? undefined : TypesUsageSummaryFromJSON(json['usage']),
    };
}

export function TypesStatsHistoryResponseToJSON(json: any): TypesStatsHistoryResponse {
    return TypesStatsHistoryResponseToJSONTyped(json, false);
}

export function TypesStatsHistoryResponseToJSONTyped(value?: TypesStatsHistoryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bgp_peers': value['bgp_peers'],
        'interfaces': value['interfaces'],
        'proto': value['proto'] == null ? undefined : ((value['proto'] as Array<any>).map(TypesProtoHistoryPointToJSON)),
        'system': value['system'] == null ? undefined : ((value['system'] as Array<any>).map(TypesSystemHistoryPointToJSON)),
        'total': value['total'] == null ? undefined : ((value['total'] as Array<any>).map(TypesIfaceTotalPointToJSON)),
        'usage': TypesUsageSummaryToJSON(value['usage']),
    };
}

