/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TypesFriendVRRPRole } from './TypesFriendVRRPRole';
import {
    TypesFriendVRRPRoleFromJSON,
    TypesFriendVRRPRoleFromJSONTyped,
    TypesFriendVRRPRoleToJSON,
    TypesFriendVRRPRoleToJSONTyped,
} from './TypesFriendVRRPRole';

/**
 * 
 * @export
 * @interface TypesFriendStatus
 */
export interface TypesFriendStatus {
    /**
     * 
     * @type {boolean}
     * @memberof TypesFriendStatus
     */
    conntrackd_running?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof TypesFriendStatus
     */
    encryption: boolean;
    /**
     * 
     * @type {string}
     * @memberof TypesFriendStatus
     */
    fingerprint?: string;
    /**
     * 
     * @type {string}
     * @memberof TypesFriendStatus
     */
    hostname?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TypesFriendStatus
     */
    identity_match: boolean;
    /**
     * 
     * @type {string}
     * @memberof TypesFriendStatus
     */
    last_error?: string;
    /**
     * 
     * @type {string}
     * @memberof TypesFriendStatus
     */
    last_seen?: string;
    /**
     * 
     * @type {string}
     * @memberof TypesFriendStatus
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof TypesFriendStatus
     */
    os?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TypesFriendStatus
     */
    reachable: boolean;
    /**
     * 
     * @type {number}
     * @memberof TypesFriendStatus
     */
    rtt_ms?: number;
    /**
     * 
     * @type {string}
     * @memberof TypesFriendStatus
     */
    version?: string;
    /**
     * 
     * @type {Array<TypesFriendVRRPRole>}
     * @memberof TypesFriendStatus
     */
    vrrp?: Array<TypesFriendVRRPRole>;
}

/**
 * Check if a given object implements the TypesFriendStatus interface.
 */
export function instanceOfTypesFriendStatus(value: object): value is TypesFriendStatus {
    if (!('encryption' in value) || value['encryption'] === undefined) return false;
    if (!('identity_match' in value) || value['identity_match'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('reachable' in value) || value['reachable'] === undefined) return false;
    return true;
}

export function TypesFriendStatusFromJSON(json: any): TypesFriendStatus {
    return TypesFriendStatusFromJSONTyped(json, false);
}

export function TypesFriendStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesFriendStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'conntrackd_running': json['conntrackd_running'] == null ? undefined : json['conntrackd_running'],
        'encryption': json['encryption'],
        'fingerprint': json['fingerprint'] == null ? undefined : json['fingerprint'],
        'hostname': json['hostname'] == null ? undefined : json['hostname'],
        'identity_match': json['identity_match'],
        'last_error': json['last_error'] == null ? undefined : json['last_error'],
        'last_seen': json['last_seen'] == null ? undefined : json['last_seen'],
        'name': json['name'],
        'os': json['os'] == null ? undefined : json['os'],
        'reachable': json['reachable'],
        'rtt_ms': json['rtt_ms'] == null ? undefined : json['rtt_ms'],
        'version': json['version'] == null ? undefined : json['version'],
        'vrrp': json['vrrp'] == null ? undefined : ((json['vrrp'] as Array<any>).map(TypesFriendVRRPRoleFromJSON)),
    };
}

export function TypesFriendStatusToJSON(json: any): TypesFriendStatus {
    return TypesFriendStatusToJSONTyped(json, false);
}

export function TypesFriendStatusToJSONTyped(value?: TypesFriendStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'conntrackd_running': value['conntrackd_running'],
        'encryption': value['encryption'],
        'fingerprint': value['fingerprint'],
        'hostname': value['hostname'],
        'identity_match': value['identity_match'],
        'last_error': value['last_error'],
        'last_seen': value['last_seen'],
        'name': value['name'],
        'os': value['os'],
        'reachable': value['reachable'],
        'rtt_ms': value['rtt_ms'],
        'version': value['version'],
        'vrrp': value['vrrp'] == null ? undefined : ((value['vrrp'] as Array<any>).map(TypesFriendVRRPRoleToJSON)),
    };
}

