/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DhcpLeaseView } from './DhcpLeaseView';
import {
    DhcpLeaseViewFromJSON,
    DhcpLeaseViewFromJSONTyped,
    DhcpLeaseViewToJSON,
    DhcpLeaseViewToJSONTyped,
} from './DhcpLeaseView';

/**
 * 
 * @export
 * @interface TypesResponseArrayDhcpLeaseView
 */
export interface TypesResponseArrayDhcpLeaseView {
    /**
     * 
     * @type {number}
     * @memberof TypesResponseArrayDhcpLeaseView
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof TypesResponseArrayDhcpLeaseView
     */
    error?: string;
    /**
     * 
     * @type {Array<DhcpLeaseView>}
     * @memberof TypesResponseArrayDhcpLeaseView
     */
    result?: Array<DhcpLeaseView>;
    /**
     * 
     * @type {string}
     * @memberof TypesResponseArrayDhcpLeaseView
     */
    status?: string;
}

/**
 * Check if a given object implements the TypesResponseArrayDhcpLeaseView interface.
 */
export function instanceOfTypesResponseArrayDhcpLeaseView(value: object): value is TypesResponseArrayDhcpLeaseView {
    return true;
}

export function TypesResponseArrayDhcpLeaseViewFromJSON(json: any): TypesResponseArrayDhcpLeaseView {
    return TypesResponseArrayDhcpLeaseViewFromJSONTyped(json, false);
}

export function TypesResponseArrayDhcpLeaseViewFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesResponseArrayDhcpLeaseView {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'error': json['error'] == null ? undefined : json['error'],
        'result': json['result'] == null ? undefined : ((json['result'] as Array<any>).map(DhcpLeaseViewFromJSON)),
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function TypesResponseArrayDhcpLeaseViewToJSON(json: any): TypesResponseArrayDhcpLeaseView {
    return TypesResponseArrayDhcpLeaseViewToJSONTyped(json, false);
}

export function TypesResponseArrayDhcpLeaseViewToJSONTyped(value?: TypesResponseArrayDhcpLeaseView | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'error': value['error'],
        'result': value['result'] == null ? undefined : ((value['result'] as Array<any>).map(DhcpLeaseViewToJSON)),
        'status': value['status'],
    };
}

