/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TypesFriendVRRPRole
 */
export interface TypesFriendVRRPRole {
    /**
     * 
     * @type {string}
     * @memberof TypesFriendVRRPRole
     */
    instance: string;
    /**
     * 
     * @type {string}
     * @memberof TypesFriendVRRPRole
     */
    state: string;
}

/**
 * Check if a given object implements the TypesFriendVRRPRole interface.
 */
export function instanceOfTypesFriendVRRPRole(value: object): value is TypesFriendVRRPRole {
    if (!('instance' in value) || value['instance'] === undefined) return false;
    if (!('state' in value) || value['state'] === undefined) return false;
    return true;
}

export function TypesFriendVRRPRoleFromJSON(json: any): TypesFriendVRRPRole {
    return TypesFriendVRRPRoleFromJSONTyped(json, false);
}

export function TypesFriendVRRPRoleFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesFriendVRRPRole {
    if (json == null) {
        return json;
    }
    return {
        
        'instance': json['instance'],
        'state': json['state'],
    };
}

export function TypesFriendVRRPRoleToJSON(json: any): TypesFriendVRRPRole {
    return TypesFriendVRRPRoleToJSONTyped(json, false);
}

export function TypesFriendVRRPRoleToJSONTyped(value?: TypesFriendVRRPRole | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'instance': value['instance'],
        'state': value['state'],
    };
}

