/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TypesProcessesResponse } from './TypesProcessesResponse';
import {
    TypesProcessesResponseFromJSON,
    TypesProcessesResponseFromJSONTyped,
    TypesProcessesResponseToJSON,
    TypesProcessesResponseToJSONTyped,
} from './TypesProcessesResponse';

/**
 * 
 * @export
 * @interface TypesResponseTypesProcessesResponse
 */
export interface TypesResponseTypesProcessesResponse {
    /**
     * 
     * @type {number}
     * @memberof TypesResponseTypesProcessesResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof TypesResponseTypesProcessesResponse
     */
    error?: string;
    /**
     * 
     * @type {TypesProcessesResponse}
     * @memberof TypesResponseTypesProcessesResponse
     */
    result?: TypesProcessesResponse;
    /**
     * 
     * @type {string}
     * @memberof TypesResponseTypesProcessesResponse
     */
    status?: string;
}

/**
 * Check if a given object implements the TypesResponseTypesProcessesResponse interface.
 */
export function instanceOfTypesResponseTypesProcessesResponse(value: object): value is TypesResponseTypesProcessesResponse {
    return true;
}

export function TypesResponseTypesProcessesResponseFromJSON(json: any): TypesResponseTypesProcessesResponse {
    return TypesResponseTypesProcessesResponseFromJSONTyped(json, false);
}

export function TypesResponseTypesProcessesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesResponseTypesProcessesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'error': json['error'] == null ? undefined : json['error'],
        'result': json['result'] == null ? undefined : TypesProcessesResponseFromJSON(json['result']),
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function TypesResponseTypesProcessesResponseToJSON(json: any): TypesResponseTypesProcessesResponse {
    return TypesResponseTypesProcessesResponseToJSONTyped(json, false);
}

export function TypesResponseTypesProcessesResponseToJSONTyped(value?: TypesResponseTypesProcessesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'error': value['error'],
        'result': TypesProcessesResponseToJSON(value['result']),
        'status': value['status'],
    };
}

