/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TypesStatsResponse } from './TypesStatsResponse';
import {
    TypesStatsResponseFromJSON,
    TypesStatsResponseFromJSONTyped,
    TypesStatsResponseToJSON,
    TypesStatsResponseToJSONTyped,
} from './TypesStatsResponse';

/**
 * 
 * @export
 * @interface TypesResponseTypesStatsResponse
 */
export interface TypesResponseTypesStatsResponse {
    /**
     * 
     * @type {number}
     * @memberof TypesResponseTypesStatsResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof TypesResponseTypesStatsResponse
     */
    error?: string;
    /**
     * 
     * @type {TypesStatsResponse}
     * @memberof TypesResponseTypesStatsResponse
     */
    result?: TypesStatsResponse;
    /**
     * 
     * @type {string}
     * @memberof TypesResponseTypesStatsResponse
     */
    status?: string;
}

/**
 * Check if a given object implements the TypesResponseTypesStatsResponse interface.
 */
export function instanceOfTypesResponseTypesStatsResponse(value: object): value is TypesResponseTypesStatsResponse {
    return true;
}

export function TypesResponseTypesStatsResponseFromJSON(json: any): TypesResponseTypesStatsResponse {
    return TypesResponseTypesStatsResponseFromJSONTyped(json, false);
}

export function TypesResponseTypesStatsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesResponseTypesStatsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'error': json['error'] == null ? undefined : json['error'],
        'result': json['result'] == null ? undefined : TypesStatsResponseFromJSON(json['result']),
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function TypesResponseTypesStatsResponseToJSON(json: any): TypesResponseTypesStatsResponse {
    return TypesResponseTypesStatsResponseToJSONTyped(json, false);
}

export function TypesResponseTypesStatsResponseToJSONTyped(value?: TypesResponseTypesStatsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'error': value['error'],
        'result': TypesStatsResponseToJSON(value['result']),
        'status': value['status'],
    };
}

