/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TypesDeriveWireguardResult } from './TypesDeriveWireguardResult';
import {
    TypesDeriveWireguardResultFromJSON,
    TypesDeriveWireguardResultFromJSONTyped,
    TypesDeriveWireguardResultToJSON,
    TypesDeriveWireguardResultToJSONTyped,
} from './TypesDeriveWireguardResult';

/**
 * 
 * @export
 * @interface TypesResponseTypesDeriveWireguardResult
 */
export interface TypesResponseTypesDeriveWireguardResult {
    /**
     * 
     * @type {number}
     * @memberof TypesResponseTypesDeriveWireguardResult
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof TypesResponseTypesDeriveWireguardResult
     */
    error?: string;
    /**
     * 
     * @type {TypesDeriveWireguardResult}
     * @memberof TypesResponseTypesDeriveWireguardResult
     */
    result?: TypesDeriveWireguardResult;
    /**
     * 
     * @type {string}
     * @memberof TypesResponseTypesDeriveWireguardResult
     */
    status?: string;
}

/**
 * Check if a given object implements the TypesResponseTypesDeriveWireguardResult interface.
 */
export function instanceOfTypesResponseTypesDeriveWireguardResult(value: object): value is TypesResponseTypesDeriveWireguardResult {
    return true;
}

export function TypesResponseTypesDeriveWireguardResultFromJSON(json: any): TypesResponseTypesDeriveWireguardResult {
    return TypesResponseTypesDeriveWireguardResultFromJSONTyped(json, false);
}

export function TypesResponseTypesDeriveWireguardResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesResponseTypesDeriveWireguardResult {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'error': json['error'] == null ? undefined : json['error'],
        'result': json['result'] == null ? undefined : TypesDeriveWireguardResultFromJSON(json['result']),
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function TypesResponseTypesDeriveWireguardResultToJSON(json: any): TypesResponseTypesDeriveWireguardResult {
    return TypesResponseTypesDeriveWireguardResultToJSONTyped(json, false);
}

export function TypesResponseTypesDeriveWireguardResultToJSONTyped(value?: TypesResponseTypesDeriveWireguardResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'error': value['error'],
        'result': TypesDeriveWireguardResultToJSON(value['result']),
        'status': value['status'],
    };
}

