/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TypesNftValidateResult } from './TypesNftValidateResult';
import {
    TypesNftValidateResultFromJSON,
    TypesNftValidateResultFromJSONTyped,
    TypesNftValidateResultToJSON,
    TypesNftValidateResultToJSONTyped,
} from './TypesNftValidateResult';

/**
 * 
 * @export
 * @interface TypesResponseTypesNftValidateResult
 */
export interface TypesResponseTypesNftValidateResult {
    /**
     * 
     * @type {number}
     * @memberof TypesResponseTypesNftValidateResult
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof TypesResponseTypesNftValidateResult
     */
    error?: string;
    /**
     * 
     * @type {TypesNftValidateResult}
     * @memberof TypesResponseTypesNftValidateResult
     */
    result?: TypesNftValidateResult;
    /**
     * 
     * @type {string}
     * @memberof TypesResponseTypesNftValidateResult
     */
    status?: string;
}

/**
 * Check if a given object implements the TypesResponseTypesNftValidateResult interface.
 */
export function instanceOfTypesResponseTypesNftValidateResult(value: object): value is TypesResponseTypesNftValidateResult {
    return true;
}

export function TypesResponseTypesNftValidateResultFromJSON(json: any): TypesResponseTypesNftValidateResult {
    return TypesResponseTypesNftValidateResultFromJSONTyped(json, false);
}

export function TypesResponseTypesNftValidateResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesResponseTypesNftValidateResult {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'error': json['error'] == null ? undefined : json['error'],
        'result': json['result'] == null ? undefined : TypesNftValidateResultFromJSON(json['result']),
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function TypesResponseTypesNftValidateResultToJSON(json: any): TypesResponseTypesNftValidateResult {
    return TypesResponseTypesNftValidateResultToJSONTyped(json, false);
}

export function TypesResponseTypesNftValidateResultToJSONTyped(value?: TypesResponseTypesNftValidateResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'error': value['error'],
        'result': TypesNftValidateResultToJSON(value['result']),
        'status': value['status'],
    };
}

