/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TypesStatsHistoryResponse } from './TypesStatsHistoryResponse';
import {
    TypesStatsHistoryResponseFromJSON,
    TypesStatsHistoryResponseFromJSONTyped,
    TypesStatsHistoryResponseToJSON,
    TypesStatsHistoryResponseToJSONTyped,
} from './TypesStatsHistoryResponse';

/**
 * 
 * @export
 * @interface TypesResponseTypesStatsHistoryResponse
 */
export interface TypesResponseTypesStatsHistoryResponse {
    /**
     * 
     * @type {number}
     * @memberof TypesResponseTypesStatsHistoryResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof TypesResponseTypesStatsHistoryResponse
     */
    error?: string;
    /**
     * 
     * @type {TypesStatsHistoryResponse}
     * @memberof TypesResponseTypesStatsHistoryResponse
     */
    result?: TypesStatsHistoryResponse;
    /**
     * 
     * @type {string}
     * @memberof TypesResponseTypesStatsHistoryResponse
     */
    status?: string;
}

/**
 * Check if a given object implements the TypesResponseTypesStatsHistoryResponse interface.
 */
export function instanceOfTypesResponseTypesStatsHistoryResponse(value: object): value is TypesResponseTypesStatsHistoryResponse {
    return true;
}

export function TypesResponseTypesStatsHistoryResponseFromJSON(json: any): TypesResponseTypesStatsHistoryResponse {
    return TypesResponseTypesStatsHistoryResponseFromJSONTyped(json, false);
}

export function TypesResponseTypesStatsHistoryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesResponseTypesStatsHistoryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'error': json['error'] == null ? undefined : json['error'],
        'result': json['result'] == null ? undefined : TypesStatsHistoryResponseFromJSON(json['result']),
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function TypesResponseTypesStatsHistoryResponseToJSON(json: any): TypesResponseTypesStatsHistoryResponse {
    return TypesResponseTypesStatsHistoryResponseToJSONTyped(json, false);
}

export function TypesResponseTypesStatsHistoryResponseToJSONTyped(value?: TypesResponseTypesStatsHistoryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'error': value['error'],
        'result': TypesStatsHistoryResponseToJSON(value['result']),
        'status': value['status'],
    };
}

