/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TypesNeighborStat } from './TypesNeighborStat';
import {
    TypesNeighborStatFromJSON,
    TypesNeighborStatFromJSONTyped,
    TypesNeighborStatToJSON,
    TypesNeighborStatToJSONTyped,
} from './TypesNeighborStat';

/**
 * 
 * @export
 * @interface TypesNeighborStatsResponse
 */
export interface TypesNeighborStatsResponse {
    /**
     * 
     * @type {Array<TypesNeighborStat>}
     * @memberof TypesNeighborStatsResponse
     */
    neighbors?: Array<TypesNeighborStat>;
    /**
     * 
     * @type {number}
     * @memberof TypesNeighborStatsResponse
     */
    ts: number;
}

/**
 * Check if a given object implements the TypesNeighborStatsResponse interface.
 */
export function instanceOfTypesNeighborStatsResponse(value: object): value is TypesNeighborStatsResponse {
    if (!('ts' in value) || value['ts'] === undefined) return false;
    return true;
}

export function TypesNeighborStatsResponseFromJSON(json: any): TypesNeighborStatsResponse {
    return TypesNeighborStatsResponseFromJSONTyped(json, false);
}

export function TypesNeighborStatsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesNeighborStatsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'neighbors': json['neighbors'] == null ? undefined : ((json['neighbors'] as Array<any>).map(TypesNeighborStatFromJSON)),
        'ts': json['ts'],
    };
}

export function TypesNeighborStatsResponseToJSON(json: any): TypesNeighborStatsResponse {
    return TypesNeighborStatsResponseToJSONTyped(json, false);
}

export function TypesNeighborStatsResponseToJSONTyped(value?: TypesNeighborStatsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'neighbors': value['neighbors'] == null ? undefined : ((value['neighbors'] as Array<any>).map(TypesNeighborStatToJSON)),
        'ts': value['ts'],
    };
}

