/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TypesMacroInfo } from './TypesMacroInfo';
import {
    TypesMacroInfoFromJSON,
    TypesMacroInfoFromJSONTyped,
    TypesMacroInfoToJSON,
    TypesMacroInfoToJSONTyped,
} from './TypesMacroInfo';

/**
 * 
 * @export
 * @interface TypesResponseTypesMacroInfo
 */
export interface TypesResponseTypesMacroInfo {
    /**
     * 
     * @type {number}
     * @memberof TypesResponseTypesMacroInfo
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof TypesResponseTypesMacroInfo
     */
    error?: string;
    /**
     * 
     * @type {TypesMacroInfo}
     * @memberof TypesResponseTypesMacroInfo
     */
    result?: TypesMacroInfo;
    /**
     * 
     * @type {string}
     * @memberof TypesResponseTypesMacroInfo
     */
    status?: string;
}

/**
 * Check if a given object implements the TypesResponseTypesMacroInfo interface.
 */
export function instanceOfTypesResponseTypesMacroInfo(value: object): value is TypesResponseTypesMacroInfo {
    return true;
}

export function TypesResponseTypesMacroInfoFromJSON(json: any): TypesResponseTypesMacroInfo {
    return TypesResponseTypesMacroInfoFromJSONTyped(json, false);
}

export function TypesResponseTypesMacroInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesResponseTypesMacroInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'error': json['error'] == null ? undefined : json['error'],
        'result': json['result'] == null ? undefined : TypesMacroInfoFromJSON(json['result']),
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function TypesResponseTypesMacroInfoToJSON(json: any): TypesResponseTypesMacroInfo {
    return TypesResponseTypesMacroInfoToJSONTyped(json, false);
}

export function TypesResponseTypesMacroInfoToJSONTyped(value?: TypesResponseTypesMacroInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'error': value['error'],
        'result': TypesMacroInfoToJSON(value['result']),
        'status': value['status'],
    };
}

