/* tslint:disable */
/* eslint-disable */
/**
 * Routier API
 * Configuration and monitoring API for a Routier node.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BindZoneView } from './BindZoneView';
import {
    BindZoneViewFromJSON,
    BindZoneViewFromJSONTyped,
    BindZoneViewToJSON,
    BindZoneViewToJSONTyped,
} from './BindZoneView';

/**
 * 
 * @export
 * @interface TypesResponseArrayBindZoneView
 */
export interface TypesResponseArrayBindZoneView {
    /**
     * 
     * @type {number}
     * @memberof TypesResponseArrayBindZoneView
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof TypesResponseArrayBindZoneView
     */
    error?: string;
    /**
     * 
     * @type {Array<BindZoneView>}
     * @memberof TypesResponseArrayBindZoneView
     */
    result?: Array<BindZoneView>;
    /**
     * 
     * @type {string}
     * @memberof TypesResponseArrayBindZoneView
     */
    status?: string;
}

/**
 * Check if a given object implements the TypesResponseArrayBindZoneView interface.
 */
export function instanceOfTypesResponseArrayBindZoneView(value: object): value is TypesResponseArrayBindZoneView {
    return true;
}

export function TypesResponseArrayBindZoneViewFromJSON(json: any): TypesResponseArrayBindZoneView {
    return TypesResponseArrayBindZoneViewFromJSONTyped(json, false);
}

export function TypesResponseArrayBindZoneViewFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesResponseArrayBindZoneView {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'error': json['error'] == null ? undefined : json['error'],
        'result': json['result'] == null ? undefined : ((json['result'] as Array<any>).map(BindZoneViewFromJSON)),
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function TypesResponseArrayBindZoneViewToJSON(json: any): TypesResponseArrayBindZoneView {
    return TypesResponseArrayBindZoneViewToJSONTyped(json, false);
}

export function TypesResponseArrayBindZoneViewToJSONTyped(value?: TypesResponseArrayBindZoneView | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'error': value['error'],
        'result': value['result'] == null ? undefined : ((value['result'] as Array<any>).map(BindZoneViewToJSON)),
        'status': value['status'],
    };
}

